### ISSUE TITLE
Prevent loosing work on AJAX/server side error

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1009]
Currently when a connection is lost or server side error/exception occurs, the unsaved data from components like CRUD are lost.

This is a feature request to prevent this bad behaviour for most common use-cases and to offer a possibility to return back to the unsaved data for retry/fix.

**Comment by romaninsh** [comment]
Form will not submit on error and will give you opportunity to submit itself again. Crud is only edited by form. Do you suggest something more radical here?

**Comment by mvorisek** [comment]
Closing this, exact steps to replicate on demos must be provided
