### ISSUE TITLE
Grid - search returns JSON but with content-type = text/html

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1013]
Fix to return content type: `application/json` and fix other JSON responses if they are affected too.

**Comment by ibelar** [comment]
I am not able to reproduce this. Can you share a little more details?

**Comment by mvorisek** [comment]
@ibelar Steps to reproduce:
1. open https://ui.agiletoolkit.org/demos/grid.php
2. open `developer tools > network` in your browser
3. try to search something like `x`
4. notice the AJAX request - https://ui.agiletoolkit.org/demos/grid.php?__atk_reload=atk_admin_grid_view&_q=x
5. notice the response headers:
![image](https://user-images.githubusercontent.com/2228672/77858377-7add1900-7203-11ea-80c5-2588b93654fb.png)

**Comment by ibelar** [comment]
https://ui.agiletoolkit.org/demos/grid.php use old atk4/ui version 1.7.1

This was refactored in version 2.0

**Comment by mvorisek** [comment]
@ibelar You are right, not sure how I came to it in the latest version, but then I retested it in the demo/1.7.1...

related with https://github.com/atk4/ui/pull/873
