### ISSUE TITLE
Using static::addTo results in unexpected behavior when called from child classes

### ISSUE THREAD

**Issue by georgehristov** [atk4/ui#1015]
As example in `Menu` methods `addMenu`, `addGroup`, `addMenuRight` use `static::addTo`.
I had defined a child class `NavMenu` extending `Menu`. 
When calling the `addMenu` method within the new class the expected behavior is that a `Menu` is added (as original behavior) and not `NavMenu` (as happens now).

Using `self` instead of `static` in `Menu` methods does not solve the issue. Only using `Menu::addTo` results in expected behavior. That is because `static` is used in `addTo` method as well.

All classes using `addTo` must be checked for this.

**Comment by mvorisek** [comment]
There are a lot of usages of `addTo` and only for these reasons I strictly isolated manual fixes vs. fixes applied by custom refactoring script/tool.

Please see commits history:
- https://github.com/atk4/ui/pull/991/commits
- https://github.com/atk4/ui/pull/1004/commits

Manual check were done by hand or semi-automated. Automated/large changes should be 100% back-compatible, i.e. 1:1, i.e. static for static, self for self etc.

As for the `static`/`self` difference - committed in https://github.com/atk4/ui/pull/1004/commits/1744324984af52caacf980c384e031bf46f5a194#diff-d1b2b70dc450f42ab1aed7b47ed90cfeR94 - for some reasons I changed `self` to `static` and I think it is like a typo from me. Please go thru the manual changes and feel free to create a PR for any mistake you find and I will review it or fix/explain.

**Comment by georgehristov** [comment]
Yes, it looks like issue was introduced in 1744324.
But unfortunately fix is not that straight forward.
Normally replacing `static` with `self` should fix the issue but maybe due to a php bug (I could not find anything about it) the `static` in the `addTo` method is interpreted as the child class and not as expected the parent. 
Only using explicitly `Menu` (which should be same as `self` but is not) solves the issue.
Then comes the issue that StyleCI automatically wants to change `Menu` to `self` when applying style fixes.
I had the same issue when applying features to the atk4/migration.

**Comment by mvorisek** [comment]
> Normally replacing static with self should fix the issue but maybe due to a php bug

You must be doing something wrong. `static` is always resolved to the class name that you are refering, `self` to the class name where it is used. Please note, that if you call `self::some method` and then use `static::something` in that method, then the later static means the first `self`.

Please check the manual changes from me and open a PR and will comment each exact case.

**Comment by georgehristov** [comment]
> if you call self::some method and then use static::something in that method, then the later static means the first self.

This is what you would expect but it does not work like that (php 7.3)

**Comment by georgehristov** [comment]
See here:
http://sandbox.onlinephpfunctions.com/code/48c6194fbb8ae85830328fe6a41ea1a43a4e18c0

**Comment by mvorisek** [comment]
@georgehristov Very interesting - probably a bug or some very weird behaviour of PHP - I just opened an issue for it directly in PHP - https://bugs.php.net/bug.php?id=79419

**Comment by mvorisek** [comment]
Probably here is some explanation - https://wiki.php.net/rfc/lsb_parentself_forwarding

So `self` can be used safely only with `self::class` which resolves to the expected current (where defined) class name and then you can call any static method explicitely with this class name.

**Comment by georgehristov** [comment]
Yes, I believe this explains the issue. Not sure why PHP team went this non-intuitive way.
But explanation is not a solution.

The only way to solve it stable is to somehow force StyleCI to ignore the `Menu` and not try to replace it with `self`. Any suggestions?

**Comment by mvorisek** [comment]
> 
> 
> Yes, I believe this explains the issue. Not sure why PHP team went this non-intuitive way.
> But explanation is not a solution.
> 
> The only way to solve it stable is to somehow force StyleCI to ignore the `Menu` and not try to replace it with `self`. Any suggestions?

Yes, see my sandpit code, use: `(self::class)::className();` instead of `self::className();`. Currently, I do not see a better possible fix, but refactoring will not work. I may write some hack for this later (using backtrace for example), but there are only a few uses of `self` currently...
