### ISSUE TITLE
Remove DropDownButton

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1021]
Is there any strong use case for `DropDownButton` - https://github.com/atk4/ui/blob/develop/src/DropDownButton.php ?

If not, mark it deprecated and remove it later.

**Comment by georgehristov** [comment]
There is a very strong use case for `DrobDownButton` when drop down needs to be attached to a button.

Attached one of my use cases

![DropDownButton](https://user-images.githubusercontent.com/8128250/77818069-e756fb80-70cf-11ea-91fc-be9edc56ddac.png)

**Comment by mvorisek** [comment]
If `Lookup` will be implemeted as an extension of `DropDown`, then removing this class will be more than needed - see issue #1020 - for now, leaving this open, should be decided.

Feedback is welcomed anytime.

**Comment by mvorisek** [comment]
closing as this is purely non Form Control
