### ISSUE TITLE
Merge/extend deeper levels of seed like "ui" or "class"

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1023]
What is currently the best way to merge/extend "ui" seed?

Related with: https://github.com/atk4/ui/issues/1021

Example code:
```
$dropdownButton = new \atk4\ui\DropDown(['ui' => <something>'button']);
var_dump($dropdownButton->ui);
```

**Comment by romaninsh** [comment]
Through class[] property / addclass

**Comment by mvorisek** [comment]
related with https://github.com/atk4/core/pull/245, this is too broad, thus closing
