### ISSUE TITLE
Simplify/fix names like DropDown to Dropdown

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1024]
Class names likes `DropDown` should be changed to `Dropdown`. This is a standard across almost every UI framework - just google "DropDown".

`Drop` class will never exists or it will mean something totally different. In contrast and for this reason classes like `CardSection` are legit.

Normally, this will be a huge BC break, but as PHP classes are case-insensitive, this change should be only cosmetic cleanup.

Please provide also feedback for renaming `jsXxx` classes to `JsXxx` as required by PSR-1 standard:

> Class names MUST be declared in `StudlyCaps`.

Is PR for this welcomed?

rule:
### use capital letter when you will use it in snake case - ex. `mysql`, not `my_s_q_l`

**Comment by romaninsh** [comment]
We had some internal policy for this but not for DropDown specifically. I agree with your proposal as long as it is BC

**Comment by mvorisek** [comment]
implemented
