### ISSUE TITLE
UploadImg inside Modal / CRUD

### ISSUE THREAD

**Issue by arrochado** [atk4/ui#1029]
I tried to customize the default modal form in a CRUD. Used a custom Form/Executor class: MyForm and MyExecutor.
```
class MyForm extends \atk4\ui\Form
    public function init(){      
        parent::init();
     }
    
    function setModel($m, $fields = null) {
       
        parent::setModel($m, false);
        $this->addField('name');
        $img = $this->addField('image', ['UploadImg']);
        $img->onDelete(function ($files){
               //code goes here
              });
        $img->onUpload(function ($files) {
              //code goes here
              });
        $img->setThumbnailSrc( $m['image']);
        return $this->model;
    }
}
```
```
class MyExecutor extends atk4\ui\ActionExecutor\UserAction
    {
        public $form  = HazardsForm::class;
        public function init()
        {
            parent::init();
            
        }
    };
```

```
$crud->executor = MyExecutor::class;
$crud->setModel($m);
```
The modal displays correctly the custom form. But when I delete an previous uploaded picture, or try to upload a new one I get the following error:

Critical Error<\/div>\n atk4\\ui\\Exception \n onUpload and onDelete callback must be called to use file upload.

The order by witch I declare onDelete or onUpload callbacks afects the delete/upload error.

**Comment by ibelar** [comment]
May be the onDelete, onUpload callback are not run because it's arguments are not kept when activated. 
Try to set the UploadImg callback stickyApp property to true. 

```
$img = $this->addField('image', ['UploadImg']);
$img->cb->appSticky = true
$img->onDelete(function ($files){
      //code goes here
});
$img->onUpload(function ($files) {
       //code goes here
 });
```

**Comment by arrochado** [comment]
Thanks @ibelar. Your suggestion didn't work.

My improvised solution was to re-register the onUpdate callback inside the onDelete closure, and vice-versa. 
PS.: I'm quite new to agiletoolkit, sorry for my noob questions

```
$img->onDelete(function ($files) use ($img){

      $img->onUpload(function ($files) {
       //code goes here
       });

      //code goes here
});

$img->onUpload(function ($files) use ($img) {

      $img->onDelete(function ($files){
         //code goes here
       });

      //code goes here
});
```
