### ISSUE TITLE
Content-type is not reset to text/html when an exception is thrown

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1040]
![image](https://user-images.githubusercontent.com/2228672/77976190-87916800-72fc-11ea-87d0-57532c57819f.png)

Steps to reproduce:
1. open network tab in developer tools in browser
2. click on any `Lookup` - you should see `200` and `content-type: application/json`, fine
3. now emit (break the code manually) an exception right before the output in the `Lookup` API virtual page
4. repeat step 2. and you should see `500` but still `content-type: application/json` which is wrong when a html error page is outputed

Important for easier debug - when mime is not (re)set to html, error pages are very hard to read.

**Comment by ibelar** [comment]
> 3. now emit (break the code manually) an exception right before the output in the `Lookup` API virtual page

What does `Lookup` refer to? Can you point out the proper demos file or code you are using for this?

**Comment by mvorisek** [comment]
Related with #1050
