### ISSUE TITLE
new version 2.1 of atk4/ui has dependency problem

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1042]
Hey,

the just released version 2.1 of atk4/ui depends on a yet unreleased version of atk4/core.

e.g.: StaticAddToTrait is not in the current release of atk4/core.

Why aren't all the dependencies automatically checked when releasing a new version???

You must NOT release a new version of anything when dependencies can't be met!

**Comment by mvorisek** [comment]
> You must NOT release a new version of anything when dependencies can't be met!

Yes, all tests need to pass lately before tagging. When releasing any `atk4/*` package.

**Comment by mvorisek** [comment]
To mitigate this issue:
a) I renamed the released `2.1.0` tag to `2.1.0-alpha1`
b) and to update Packagist I tagged the latest stable `2.0.4` as `2.1.0`, pushed it, and removed this tag from this repo.

Later, the `2.1.0-alpha1` may be renamed back to `2.1.0`.

### Renaming tags is normally very bad practice. The fixed release should never use `2.1.0`, i.e. it should be at least tagged as `2.1.1`.

@karakal Did this (temporary) mitigated your issue?

**Comment by karakal** [comment]
Somehow. Right now 2.1 is not installable because of the missing release of atk4/core... There should be no release if dependencies are not met....

**Comment by mvorisek** [comment]
@karakal Maybe your tag `2.1.0` was not updated. If you clean all your caches (git & composer), the `atk/ui` should be installable:
![image](https://user-images.githubusercontent.com/2228672/78267223-022dd380-7507-11ea-87ea-acd6c4ed0671.png)
which is the point of my fix. The real 2.1.x release needs to be done by @romaninsh.

**Comment by karakal** [comment]
Yeah, but the problem is, that it loads atk4/core:2.0.1 which is wrong! Because the new ui Version isn't working with atk4/core:2.0.1....
So the dependency in the release is wrong set....

![grafik](https://user-images.githubusercontent.com/2448293/78281184-948ba280-751a-11ea-918a-f990f3b0714f.png)

**Comment by mvorisek** [comment]
Delete everything and reinstall, the `View` should like:
![image](https://user-images.githubusercontent.com/2228672/78283608-51cbc980-751e-11ea-9af8-ed3e90df9900.png)
there is no that trait usage on line 27. Composer can not handle changed tags. You need to delete the vendor folder fully and also the local caches.

**Comment by karakal** [comment]
I always deleted the vendor file. So, to describe what I did:
I created a new empty folder. copied my created classes in there, created a new composer.json

`{
    "require": {
        "atk4/ui": "2.1.0-alpha1",
        "atk4/login": "^2.0",
        "atk4/filestore": "^0.1.0"
    }
}`

Then I did a composer clearcache and then a composer install.

This is the output:
`C:\tools\xampp\htdocs\atk4>composer clearcache
Cache directory does not exist (cache-vcs-dir):
Clearing cache (cache-repo-dir): C:\Users\lhp\AppData\Local\Composer\repo
Clearing cache (cache-files-dir): C:\Users\lhp\AppData\Local\Composer\files
Clearing cache (cache-dir): C:\Users\lhp\AppData\Local\Composer
All caches cleared.

C:\tools\xampp\htdocs\atk4>composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing league/flysystem (1.0.66): Downloading (100%)
  - Installing psr/log (1.1.3): Downloading (100%)
  - Installing atk4/core (2.0.1): Downloading (100%)
  - Installing atk4/dsql (2.0.1): Downloading (100%)
  - Installing atk4/data (2.0.2): Downloading (100%)
  - Installing atk4/ui (2.1.0-alpha1): Downloading (100%)
  - Installing atk4/filestore (0.1.0): Downloading (100%)
  - Installing atk4/schema (2.0.2): Downloading (100%)
  - Installing atk4/login (2.0.2): Downloading (100%)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
atk4/core suggests installing symfony/yaml (~2.1|~3.0|~4.0)
atk4/dsql suggests installing jdorn/sql-formatter (*)
atk4/schema suggests installing jdorn/sql-formatter (*)
Writing lock file
Generating autoload files`

When I then have a look at the View.php in the folder \vendor\atk4\ui\src I have the following lines of code in the header:

`use atk4\core\AppScopeTrait;
use atk4\core\ContainerTrait;
use atk4\core\DIContainerTrait;
use atk4\core\Exception;
use atk4\core\FactoryTrait;
use atk4\core\InitializerTrait;
use atk4\core\StaticAddToTrait;
...`

and that is clearly also the case when you have a look at the file in the repo https://github.com/atk4/ui/blob/2.1.0-alpha1/src/View.php

So, my issue stands: A version of ui was released with a wrong dependency.

When I look into the code at https://github.com/atk4/core/tree/2.0.1/src there is no StaticAddToTrait.

So the release has the wrong dependency on core. I also can't use the dev-develop branch of atk4/core because then all the others components I rely on (login, filestore, mastercrud) are not working any more.

And I don't want to create a proprietary vendor folder where I copy all kind of things together (which will work, but I cann't use for delivery...)

And I am dependend on features of the 2.1 version.

So is there a possibility to release either a working atk4/core version or fix the dependencies in the other modules?

**Comment by mvorisek** [comment]
@karakal Why not to use `2.0.4` before proper 2.1,x release is made?

**Comment by karakal** [comment]
Because 2.1 WAS released and there is a lot of functionality that is either broken in 2.0.4 or non existing.
WHY release a version that can't be installed correctly?

**Comment by mvorisek** [comment]
Sure, it will get released. I just hotfixed it solely make this repo installable without specifing version (which for some reasons does currently not work for you and I do not know/have the time to further debug it).

**Comment by DarkSide666** [comment]
@karakal Should be fixed now by releasing core 2.0.2 https://github.com/atk4/core/releases/tag/2.0.2

**Comment by karakal** [comment]
Yeah. Version 2.1.0-alpha1 is playing nicely with atk4/core:2.0.2!
