### ISSUE TITLE
Non minified .js is not available in releases

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1045]
See:
![image](https://user-images.githubusercontent.com/2228672/78013531-e8459280-7346-11ea-8589-ae162ad7ea5e.png)
(the diff is actually inverted, but GitKraken somehow shows it always this way not matter what commit is selected for compare first)

**Comment by romaninsh** [comment]
Do you mean - it's not bundled in ZIP file?

**Comment by mvorisek** [comment]
Also in tagged releases, without non-minified version/map debugging is not that easy.

**Comment by mvorisek** [comment]
@ibelar wdyt?
