### ISSUE TITLE
Forms don't respect field caption

### ISSUE THREAD

**Issue by skondakov** [atk4/ui#106]
When in the form's model there is a field with a 'caption', the caption is not  used for this field's label, but the default caption is used instead.

**Comment by DarkSide666** [comment]
canyou give short testcase?

**Comment by romaninsh** [comment]
Caused by https://github.com/atk4/data/issues/215

**Comment by acicovic** [comment]
@skondakov according to Romans this is solved in #105 and #215 is closed as well. If you have time to confirm this, please do.

I will propose to close this issue but feel free to intervene if this is not fixed.

**Comment by DarkSide666** [comment]
I would say - close it, but Romans wanted to close issues himself during weekly hangout so adding label.
