### ISSUE TITLE
Validation Exception is not shown right

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1060]
ValidationException was already shown "nicely". (the field red and the message beneath the field)
I just changed to 2.0.4 and the Validation Exception is not shown in that way but with a really ugly exception. Why is that?

![grafik](https://user-images.githubusercontent.com/2448293/78256039-58dfe100-74f8-11ea-9c1b-55b865150725.png)

**Comment by ibelar** [comment]
This was fix in #896 and is part of the 2.1 release.

**Comment by karakal** [comment]
Yeah I figured. It did a manual overwrite of atk4/core because right now 2.1 is not installable via composer (and therefore not really usable for any customer project...) and there it is available. I opened an issue in atk4/core...
