### ISSUE TITLE
CRUD with multiple values Dropdown field

### ISSUE THREAD

**Issue by nocelab** [atk4/ui#1061]
I would like to store multiple selection from Dropdown into a single field using a CRUD model. I've tried with string, array and json type but seems to not be implemented.
How can I do this?

**Comment by ibelar** [comment]
Something like this should work. By setting the ui['form'] key when adding field to your model.

By setting another model to the DropDown input:
```
$this->addField('multiple', ['ui' => ['form' => ['DropDown', 'isMultiple' => true, 'model' => new MyModel()]],]);
```
or using array with values:
```
$this->addField('multiple', ['ui' => ['form' => ['DropDown', 'isMultiple' => true],  'values' => ['1' => '1', '2'=>'2']]);
```

**Comment by nocelab** [comment]
> ```
> $this->addField('multiple', ['ui' => ['form' => ['DropDown', 'isMultiple' => true]],  'values' => ['1' => '1', '2'=>'2']);
> ```
with TEXT type field (mysql) I got:
![image](https://user-images.githubusercontent.com/9341832/78381431-a3835b00-75d5-11ea-992f-108650f941f9.png)

**Comment by nocelab** [comment]
> ```
> $this->addField('multiple', ['ui' => ['form' => ['DropDown', 'isMultiple' => true, 'model' => new MyModel()]],]);
> ```
I don't understand what MyModel means... model based on Dropdown class?

**Comment by ibelar** [comment]
My bad. Values should be in DropDown seed.
````
 $this->addField('serial', ['ui' => ['form' => ['DropDown', 'isMultiple' => true,'values' => ['1' => '1', '2'=>'2']]]]);
````

When you set a Model with a DropDown field, it will load value from the model instead of manually entering them. MyModel was just a sample name.

**Comment by nocelab** [comment]
nooo... that's amazing... it works!!!
![image](https://user-images.githubusercontent.com/9341832/78406499-0808df00-7603-11ea-904b-bed68d55469e.png)
![image](https://user-images.githubusercontent.com/9341832/78406533-19ea8200-7603-11ea-9097-c89e729c8218.png)
Thanks!!!
