### ISSUE TITLE
https://master.osa.agiletoolkit.org:port GH webhook is not working

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1063]
![image](https://user-images.githubusercontent.com/2228672/78385575-59ea3e80-75dc-11ea-81aa-b86bfe7c232f.png)

not sure for what it is, but it is red

**Comment by romaninsh** [comment]
Removed, thanks for spotting.

**Comment by mvorisek** [comment]
@romaninsh I see I can not add labels in this repo now, did you changed it? I would kindly ask you to go thru https://github.com/atk4/ui/pull/1162 history and double check to what I reacted, For ex. you have stated that the compiled files are not part of the repo, but they were etc. You might be not aware of it, ok, let's go over it, but please try to understand it from both sides.

**Comment by romaninsh** [comment]
@mvorisek you should have that now. I'll send you details no the upcoming ATK meeting too.
