### ISSUE TITLE
Grid configuration for overload=auto and limit column content max width

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1068]
If you put in a „ribbon“ tag to the first column in a row, the outer part of the ribbon is missing. This works well with a table, but not with a grid.

Furthermore, the drop down arrows for quick filtering in the top header row are aligned left to the column name (and not right as in other tools like Excel etc.).

see https://media.discordapp.net/attachments/664569505950990382/695625749641691196/unknown.png
![unknown](https://user-images.githubusercontent.com/1969119/78584680-412e9280-7841-11ea-81ba-9657989b7b82.png)

**Comment by ibelar** [comment]
@mkrecek234 - this is normal behaviour. 

Because table in grid are place within a div that use .atk-overflow-auto class. This means that the div holding the table use overflow property, thus, hiding extra ribbon content. 

Since overflow is important in our case because it allow to scroll overflow content in a grid, it will not be changed.

You can manually change or alter css by setting overflow property in you own grid.

As far as table filtering icon, it was move there in order to have better control on them. And this because it is difficult for us to know what size column is required to have.

Again you can customize to your need using css class ark-table-dropdown.

**Comment by mkrecek234** [comment]
Hi Alan,

Thank you for the explanation. Is there a reason why grid then uses overflow auto by default and table not? Thank you,
Michael

**Comment by ibelar** [comment]
Well, in fact, it is the table container that uses the overflow property, not the table itself.
I think it was created this way so when Crud (grid) uses a lot of columns, you can still reach the edit and delete button by scrolling the container.

**Comment by mkrecek234** [comment]
I see. The action column should also be set to reduce the remaining columns width, and not make the table scrollable as with table, don't you think? And have the action buttons be set in a separate row if the width of the screen is too narrow. Minor stuff, but seemed inconsistent to me between table  and grid/CRUD behaviour.  Instead of scrolling for the action column, everything should shrink and move to vertical, as implemented in table.

**Comment by mkrecek234** [comment]
On the second point I still would vote for the drop-down arrows in the column header line to be right-adjusted (I think as they were before), that looked better and more to other UI standards like in Excel to me. Just personal opinion.

**Comment by georgehristov** [comment]
Dropdown arrows are on the left as they refer to filtering of columns. The sort order indication is on the right.
Big discussion here https://github.com/atk4/ui/issues/554

**Comment by mkrecek234** [comment]
Thank you, I'm fine either way, just talking from a Excel business user perspective. Here there is a joint drop-down arrow for both sorting and filtering.

**Comment by mkrecek234** [comment]
Just a last thought on this, as grids are a central part of each app:
Why can't we just make it more versatile and configurable:
1) Allow to set maxwidth sizes for columns (CSS) - and eventually maxchars for each column (to prevent line-breaks/cut off too long text). 
2) Let programmer decide in the grid model if vertical scrolling (overload=auto) is active or not?

**Comment by mvorisek** [comment]
@mkrecek234 Update the title and mark the issue in the printscreen to make it clear at the first sight.
