### ISSUE TITLE
Each phpunit test takes about 600 ms

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1069]
There are about 370 tests and phpunit takes 220 seconds, which equals to about 600 ms per test.

Analyse why the tests are so slow. Is that due webserver based on built-in php webserver?

Each basic atk4 ui response should not take longer than 60 ms.

**Comment by DarkSide666** [comment]
I guess it's because it rebuilds some environment on each test, but not sure. It's just a wild guess. Maybe some caching could help with that.

**Comment by abbadon1334** [comment]
i rewrite the unit testing via builtin webserver, because few times we see stupid bugs only after merge, running tests on demos raises our confidence on testing.
I search everywhere and found only that way to use the builtin webserver to test with `exit()` and without, if you know another one feel free to post and let's discuss it.
If i remember correctly the problem is the `exit()` function.

**Comment by mvorisek** [comment]
@abbadon1334 The tests with and without callExit are great! But single test currently takes way more than it should. Maybe the coverage driver is slowing it down which can not be currently turned of - see https://github.com/atk4/ui/issues/1071 . Not sure if the test time will by cut in half with coverage removed, but as long as the coverage is reported only from one version, it makes sense to be disabled for every version except one which is reported. And then the other versions can be used for a quick reference.

**Comment by abbadon1334** [comment]
I think we have 2 options :

1. Implementing PSR7 and PSR17. We can remove many $_GET/$_POST/$_SERVER and get it from a single static object Persistence\Request like Persistence\UI 
In ATK we have an entry point which is usually App::run and an exit point which is terminate and output. Probably it will be much more easy to move from a file routing to a true routing and we can test it much easier without the builtin webserver
2. Adding variable for exit demos like NO_COVERAGE=1 directly in the uri

First solve the problem if is the builtin, second cut half duration if is coverage

**Comment by mvorisek** [comment]
Evaluation with mature webserver like Apache needs to be done. We can very easily capture all request URLs and test the total time externally.

The coverage has likely some degree of impact, see:
- https://phpunit.readthedocs.io/en/9.0/code-coverage-analysis.html#speeding-up-code-coverage-with-xdebug
- https://medium.com/@nicocabot/speed-up-phpunit-code-coverage-analysis-4e35345b3dad
and if so, it can be very easily disable when the webserver is started, no need for extra variable.

The testing need some time to start up. So running everything in single PHP process may be the fastest option, but it will never test things like flushing, headers, ... I have fixed 95% of this issues in past days, but the current tests helped a lot. So if we can cut the run time let say below 30 seconds, the setup time will almost never decrease and faster testing will not provide any significant value.

**Comment by mvorisek** [comment]
The main slowdown is the coverage generated for each webserver phpunit test request - see https://github.com/atk4/ui/runs/618627747#step:11:15 , related PR cut the test times of non-latest php version 10 times (from 4 minutes to 25 seconds).

**Comment by mvorisek** [comment]
Reopening this. I think we should add an option to quickly test without the full solution with internal webserver. This can be probably also default locally, but full testing like now should be kept in GH testing - currently there is no way to call `exit()` in php multiple times.

The total testing time locally should be below 5 seconds.

**Comment by mvorisek** [comment]
We should probably fake the HTTP client for this require the target files directly with some help with modified global variables (`$_GET`, ...) and `App`.
