### ISSUE TITLE
Custom CRUD add/edit form

### ISSUE THREAD

**Issue by nocelab** [atk4/ui#1081]
I would like to have a different form for edit CRUD rows.
I saw old (<= 1.7.1) `formDefault` property... what is equivalent in new version (>= 2.0.0)?
I didn't find any indication in docs and demo

**Comment by ibelar** [comment]
For now, you need to extend ActionExecutor\UserAction class in UI and override method 
 `UserAction::addFormTo(View $view)`

This method passe the Modal view and you can add your own form to it.
You would also need to set this new executor class to the model action on which you need this form.

For example, you want to use this new form on edit action:
`$m-getAction('edit')->ui['executor'] = MyExecutor::class;`

You can see a sample of this in demos/crud.php file.

**Comment by nocelab** [comment]
Thank you... very difficult for me guess it!

I saw demos/crud.php and now I understand the sample, but my need is to apply a form class based on a model (with fields organized in groups/columns). With this form class:

```
// form to edit File model (demos/database.php)
class MyFile extends \atk4\ui\Form {
    function setModel($m, $fields = null) {
        parent::setModel($m, false);
        
        $gr = $this->addGroup('Group one');
        $gr->addField('name');
        $gr->addField('type');
        $gr = $this->addGroup('Other group');
        
        return $this->model;
    }
}
```
I want to use it in edit mode. I tried `addFormTo` with no success... documentation doesn't help too much

**Comment by ibelar** [comment]
I see. Then this should work.

1- Setup your form class in your custom action executor via the form property.
```
class MyExecutor extends UserAction
{
    public $form = MyForm::class;
}
```
2 -  Pass this executor to your edit action.
```
$m = new Model($db);
$m->getAction('edit')->ui['executor'] = MyExecutor::class;
// if you need specific field for edit, then set them here.
// $m->getAction('edit')->fields = ['name'];
```
3 - setup Crud
```
$crud = \atk4\ui\CRUD::addTo($app);
$crud->setModel($m);
```

## Other option

If you need to setup all your model action using the same executor, then you can forget step 2 and setup your CRUD like below, doing so will use your form for all model action that require this executor.

```
$crud = \atk4\ui\CRUD::addTo($app, ['executor'=> MyExecutor::class);
$crud->setModel($m);
```

Hope this help!

**Comment by nocelab** [comment]
ok... now more clear!
I write this sample (myCrud.php runnable in atk4ui\demos path):

```
<?php

require 'init.php';
require 'database.php';

class MyForm extends \atk4\ui\Form {
    function setModel($m, $fields = null) {
        parent::setModel($m, false);
        
        $gr = $this->addGroup('Group one');
        $gr->addField('name');
        $gr->addField('iso');
        //$gr = $this->addGroup('Other group');
        
        return $this->model;
    }
}

class MyExecutor extends atk4\ui\ActionExecutor\UserAction {
    public $form = MyForm::class;
}

$m = new Country($db);

// SINGLE OPERATION OPTION
$m->getAction('edit')->ui['executor'] = MyExecutor::class;
$crud = $app->add(['CRUD']);

// GENERIC OPERATION OPTION
//$crud = $app->add(['CRUD', 'executor' => MyExecutor::class]);

$crud->setModel($m);

?>
```

but I have this error:

`Error: Class 'atk4\ui\MyForm' not found (in C:\temp\xampp\htdocs\atk4ui\vendor\atk4\core\src\FactoryTrait.php:153)`

I'm trying somethig like `myCrud\MyForm::class` without success

**Comment by DarkSide666** [comment]
Try `public $form = '\' . MyForm::class;` in `MyExecutor` class

**Comment by nocelab** [comment]
with **double** backslash... it works!!!

`public $form = '\\'.MyForm::class;`

I finally have my custom form apply to CRUD:

![image](https://user-images.githubusercontent.com/9341832/79159278-0f38a580-7dd8-11ea-91b2-cd4d19022faa.png)

... now I analyze why field captions aren't shown in group section... or perhaps I have to use Column (put in line several fields)

**Comment by DarkSide666** [comment]
That's as expected - field captions will not show in group section.
Try using columns

**Comment by nocelab** [comment]
why group in demos/form.php have captions?

![image](https://user-images.githubusercontent.com/9341832/79225138-93347100-7e5c-11ea-802e-187d168af21a.png)

...because are not based on Model?

**Comment by DarkSide666** [comment]
hmmm... maybe.

**Comment by nocelab** [comment]
finally result using `Columns`

![image](https://user-images.githubusercontent.com/9341832/79385538-0c20ef00-7f69-11ea-9786-482d8606e9c2.png)

[Here](https://gist.github.com/nocelab/ba2c8b1925f87043168b9efaabdf3eff) the complete sample

**Comment by nocelab** [comment]
> hmmm... maybe.

I will open a ticket for this... thanks!
