### ISSUE TITLE
Delete button disappears from table following refresh after delete

### ISSUE THREAD

**Issue by TheNetworkIsDown** [atk4/ui#1086]
The table declaration is pretty straight-forward

```
$table = $this->add('Table');
$table->setModel($cred);
$table->addColumn(null, ['Delete']);
```

This is how it looks initially

![image](https://user-images.githubusercontent.com/277893/79043417-5ae42700-7bff-11ea-80ba-268ba7d19e5c.png)

When I click on Delete, after confirmation, the entry is deleted, and the table is reloaded. However the reloaded table no longer contains the Delete column.

![image](https://user-images.githubusercontent.com/277893/79043423-6899ac80-7bff-11ea-818c-62ef5aa6c17f.png)

The Delete column and button reappears when I refresh the page.

**Comment by TheNetworkIsDown** [comment]
I would like to add that it only seems to happen if the table containing the "Delete" column is located inside a view which is loaded into the current page, like

```
...
if (isset($id) && $id>0) {
  $app->add(['Header', sprintf('Identity #%s', $id)]);

  $m = new myModel($app->db);
  $m->load($id);

  $app->add(new myDetailsView)->setModel($m);  // using "Delete" column in here triggers what I described
...
```

**Expected behavior:** Everything should just work whether it is loaded directly into the app, or a view, or a modal, or a modal inside a modal or whatever the layer.

**Comment by DarkSide666** [comment]
@NotAProfessionalDeveloper please re-test this with latest UI dev branch.
Probably this is also fixed by #1155

**Comment by TheNetworkIsDown** [comment]
~~Tested with dev-master downloaded today. No change.~~

~~Funny thing is: After item deletion (which reloads the table with "Delete" button missing) and then using my "Add" modal to again add an item (which also reloads the table), then the Delete button reappears.~~

**UPDATE** Uh wait a sec, compser "dev-master" version (3fdbd86cca) seems to be the same as "2.1.0-alpha1" (and not "develop"). However since #1155 has been committed later... I need to test with actual "develop" again.

**Comment by DarkSide666** [comment]
`dev-master` should be equal to last released version.

You should test on `dev-develop` branch.

**Comment by mvorisek** [comment]
Closing as no reaction - if still valid, clone latest ui and describe step by step how to replicate on demos. We can fix issues very quickly.
