### ISSUE TITLE
Paginator links don't work because of missing spinner() from atk4JS.js

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#109]
When I click on paginator items, then links don't work because of missing spinner() method from JS library:

```
grid.php:77 Uncaught TypeError: $(...).spinner is not a function
    at HTMLAnchorElement.<anonymous> (grid.php:77)
    at HTMLDivElement.dispatch (jquery-3.1.1.js:5201)
    at HTMLDivElement.elemData.handle (jquery-3.1.1.js:5009)
```

from line
```
  $("#atk_admin_grid_view_paginator").on("click",".item",function(event) {
    event.preventDefault();
    event.stopPropagation();
    $("#atk_admin_grid").spinner({"loaderText":"","active":true,"inline":true,"centered":true,"replace":true}).reloadView({"uri":"?atk_admin_grid_callbacklater_2=callback","uri_options":{"atk_admin_grid_view_paginator":$(this).data("page")}});
  });
```

Issue is because by default developer doesn't have ready to use atk4JS.js library (see below).

**Comment by DarkSide666** [comment]
Workaround:
* install node.js and see js/readme
or
* use this: http://ui.agiletoolkit.org/js/lib/atk4JS.js

but need to use CDN or some other way how to get it up and running without messing with additional installs.

**Comment by romaninsh** [comment]
For the "develop" branch you'll have to compile jS yourself (see js/readme), but for stable releases I'll have it pre-compiled and bundled in a minified form.

**Comment by DarkSide666** [comment]
Ok, but need a bit more documentation how to compile js in js/readme. For example that you have to install node.js which includes npm etc.

**Comment by romaninsh** [comment]
People who intend to develop ATK should be able to look it up. Others won't need it because file will be there :)

**Comment by romaninsh** [comment]
Related to #82

**Comment by DarkSide666** [comment]
ok fine - can do that in #82 so this "bug" can be closed.
