### ISSUE TITLE
call to non existing method addJsSearch() in demo/jssearch.php

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#1107]
in /demos/jssearch.php there is a call to a method addJsSearch(). However, this method does not exist for Grid, nor was I able to find it anywhere else in atk4/ui repo. Seems addQuickSearch() was meant instead.

**Comment by mvorisek** [comment]
Closing as there is no method called `addJsSearch` - if still valid, clone latest ui and describe step by step how to replicate on demos. We can fix issues very quickly.

**Comment by mvorisek** [comment]
Closing as there is no longer method called `addJsSearch` - if still valid, clone latest ui and describe step by step how to replicate on demos. We can fix issues very quickly.
