### ISSUE TITLE
Form demo page allows to change 'GB' causing error on next load

### ISSUE THREAD

**Issue by KraKraDooh** [atk4/ui#111]
http://ui.agiletoolkit.org/demos/form2.php

Fatal Error
atk4\data\Exception: No matching records were found Code404
Exception Parameters
model: Object Country
conditions: [["iso","GB"]]
Stack Trace
File	Object	Method
/www/ui/vendor/atk4/data/src/Model.php:1097	-	atk4\data\Persistence_SQL::loadAny()
/www/ui/vendor/atk4/data/src/Model.php:1151	-	atk4\data\Model::loadAny()
/www/ui/demos/form2.php: 12	-	atk4\data\Model::loadBy
( "iso", "GB")

**Comment by romaninsh** [comment]
see also #114
