### ISSUE TITLE
Html tags in field

### ISSUE THREAD

**Issue by nocelab** [atk4/ui#1117]
How can I render html tags in CRUD column saved in a table field? I tried `Template `class:

`$crud->addDecorator("html_field", ['Template', '<b>{$html_field}</b>']`

but it renders only `<b>` outside the field and not its content

**Comment by DarkSide666** [comment]
This should do the trick.
Please show how you define your data model and how to associate it with your CRUD.

**Comment by nocelab** [comment]
field in Model definition:

` $this->addField('html_field');`

and this is CRUD:

```
$m = new ModelHtml($app->db);
$c = $app->add(['CRUD']);
$c->setModel($m);
$c->addDecorator("field_html", ["Template", '<b>{$field_html}</b>']);
```

assuming field value is `"<code>Test Html</code>"`... this is the output:

![image](https://user-images.githubusercontent.com/9341832/79858281-75708a00-83cf-11ea-91ee-7b26d55f4908.png)

only `<b>` are rendered

**Comment by DarkSide666** [comment]
Ah I see - thing is that value is always html encoded and that's why it do not render as HTML `<code>` tags.
You can try to use `Text` decorator instead of `Template`.

**Comment by PhilippGrashoff** [comment]
Hi, there is an open issue with a working solution for it: https://github.com/atk4/ui/issues/875
I just didnt turn that into a PR yet

**Comment by nocelab** [comment]
> You can try to use `Text` decorator instead of `Template`.

with:
`$c->addDecorator("field_html", ["Text", '<b>{$field_html}</b>']);`

I got:
`ErrorException: Invalid argument supplied for foreach()`

**Comment by nocelab** [comment]
> Hi, there is an open issue with a working solution for it: #875

Wow... now I have:

![image](https://user-images.githubusercontent.com/9341832/79890219-76b9ab00-83ff-11ea-84e5-e55e6d6b7066.png)

... thank you very much!!!

**Comment by DarkSide666** [comment]
Will be added in main UI repo soon - https://github.com/atk4/ui/pull/1121.
