### ISSUE TITLE
Admin layout with wrong footer stickyness

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1129]
Current version positions the "Made with Agile Toolkit" footer on the bottom, but keeps it anchored at that page position when scrolling

![image](https://user-images.githubusercontent.com/28671486/80199408-8f091000-8621-11ea-8cc0-d30bd4786d13.png)

**Comment by mkrecek234** [comment]
I think I could resolve it with a CSS change removing the height of the footer:

`  .ui.visible.left.sidebar ~ .atk-mainContainer,
  .ui.visible.left.sidebar ~ footer.atk-footer {
    height: unset;
  }`

**Comment by ibelar** [comment]
We probably do not need this css height rule anymore, since the last change. I will check.
