### ISSUE TITLE
Deduplicate typecasting code using `atk4/data`

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1132]
This is a feature request to deduplicate all typecasting/normalization to code to one place - `atk4/data`.

Currently the typecasting/normalization is coded twice or even 4 times (for save/restore, for ex. datetime) and all versions behaves slightly different.

**Comment by georgehristov** [comment]
We are working on the new Field setup that should streamline typecasting/normalization

**Comment by mvorisek** [comment]
done
