### ISSUE TITLE
Any special names should use constants

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1134]
Any special names like `add` in `Model->getAction('add')` should use not the special name directly, but it should be put in the owning class as a public constant and this constant should be used with that class name everywhere where needed.

**Comment by romaninsh** [comment]
This was consideration at some point. (probably few years ago) - should we use constants or literals. We decided to keep literals, however with the state of IDEs situation may be different now. Something we could reconsider.

**Comment by mvorisek** [comment]
@romaninsh May I know the reason?

**Comment by DarkSide666** [comment]
@mvorisek I guess it was because of simplicity. It's simpler to write:
`$model->getAction('add')`
than
`$model->getAction(Model::ACTION_ADD)`
:)

**Comment by mvorisek** [comment]
closing as too broad
