### ISSUE TITLE
Proper etago escaping in style/script

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1136]
Currently there is crazy code like:
`$this->encodeHTML(strip_tags($value));`
which seems to be not usefull at all - stripping tags is something totally different than escaping.
Example from https://github.com/atk4/ui/pull/1111

The right solution for script/css element bodies is to escape "etago" tags, see:
- https://mathiasbynens.be/notes/etago
- https://www.man42.net/blog/2016/12/safely-escape-user-data-in-a-script-tag/#solution
- https://www.w3.org/TR/css-syntax-3/#escaping
- https://stackoverflow.com/a/25612313/5153116 (there can not be any child elements)

There should be a better review on these PRs and all security PRs should have tests.

**Comment by DarkSide666** [comment]
Oh I made a bug there.
It supposed to be like this:
```
$value = $encodeValue ? $this->encodeHTML($value) : strip_tags($value);
```

Will that be OK?

**Comment by mvorisek** [comment]
> 
> 
> Oh I made a bug there.
> It supposed to be like this:
> 
> ```
> $value = $encodeValue ? $this->encodeHTML($value) : strip_tags($value);
> ```
> 
> Will that be OK?

It still look not good to me - `$encodeValue` should always imply no encoding at all, no strip tags. See my PR https://github.com/atk4/ui/pull/1137 with proposed fix.
