### ISSUE TITLE
Move everything related with demo deploy to demos/

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1138]
- /atk4-ui-helm/
- /.codefresh/
- /Dockerfile
- /.dockerignore

Important for better overview in the root directory.

What is the `/Makefile` file for, where it is used?

**Comment by bedengler** [comment]
I don't see Dockerfile and .dockerignore. 

What about
- .codeclimate.yml
- .php_cs.dist
- .travis.yml
- behat-travis.yml
- codecov.yml
- phpunit.xml.dist

The contain partially data like "localhost:8888" etc. which seems to be removable.

**Comment by mvorisek** [comment]
> 
> 
> I don't see Dockerfile and .dockerignore.

Already move by me to /demos, other files you mention are probably needed (ex. `behat-travis.yml`), but it should be stay as it is used for /features and some oter files (.travis.yml, etc.).
