### ISSUE TITLE
Check for required=true for float is not correct

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1147]
I have the following problem:
I have a field defined in my model:
`$this->addField('min',['caption'=>'Min-Wert','type'=>'float','required'=>'true']);`

When I try to input 0 in my UI, I get the following error:
![grafik](https://user-images.githubusercontent.com/2448293/80589941-60bd7300-8a1b-11ea-9deb-53425f5a95ca.png)

But 0 IS NOT Null, so the check is wrong.

I am using atk4/ui:2.1.0-alpha1

**Comment by mvorisek** [comment]
@karakal You must use `mandatory`, see docs https://agile-ui.readthedocs.io/en/latest/form.html#mandatory-and-required-fields
