### ISSUE TITLE
Implement sticky GET arguments

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#115]
Sometimes we want to preserve certain GET arguments, this way if UI adds more arguments, then it would not loose some important arguments in the process.

Certainly one way is to use `/cookie/edit/4` pretty URL but we should provide other option.

This option is Sticky GET. Ability to specify to the App class that certain arguments should be preserved.

**Comment by romaninsh** [comment]
After implemented - fix #110.

**Comment by DarkSide666** [comment]
`stickyGet` and `stickyForget` is already implemented in App.
I think this issue can be closed now.
