### ISSUE TITLE
Some Exception are not display at all

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#1150]
Throwing an exception early in a file is not displayed to user.

Using any of the demo file,
Simply throwing an exception: 

```
throw new Exception('test');
```

or making a mistake:

```
\atk4\ui\Header::addTo($app, ['Basic Button', 'size' => 2, 'noproperty' => 'try me']);
```

**Comment by mvorisek** [comment]
When I was developing this PR https://github.com/atk4/ui/pull/1065/files about a month ago I did not notice any issues.

It app fully initialized before? Otherwise there is no handler installed and Atk can not catch it of course.

**Comment by ibelar** [comment]
Yes, App is initialized. Just take any demo file and throw an exception and nothing is shown.
