### ISSUE TITLE
Implement session memorize

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#116]
If session is available through the App we can use it to store various information such as current pagination page or quicksearch. 

Memorization mechanism should be implemented on per-view level through

http://agile-core.readthedocs.io/en/develop/overview.html#session

**Comment by DarkSide666** [comment]
`stickyGet` is implemented

**Comment by romaninsh** [comment]
memorize is implemented, just add:

``` php
    use \atk4\core\SessionTrait;
```
