### ISSUE TITLE
On click in grid error: "Callback requested, but never reached."

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#1161]
My model: 
```
class BetoolsUserList extends \atk4\data\Model {
  public $table = "betools_users";
  public $id_field = "user_ID";
  public $caption = 'Benutzerliste';

  function init(): void {
    parent::init();

    $this->title_field = 'user_Username';
    $this->addField('user_Name1', ['caption'=>t("Firstname"), 'type'=>'string']);
    $this->addField('user_Name2', ['caption'=>t("Lastname"), 'type'=>'string']);
    $this->addField('user_Username', ['caption'=>t("Username"), 'type'=>'string']);
    $this->addField('user_Email', ['caption'=>t("Email"), 'type'=>'string']);

    //$this->lock();
  }
}
```

When I call a grid with a "Test" button, I'm getting the error, that the callback is missing.
```
if(isset($_REQUEST['sub'])) {
  $g = \atk4\ui\Grid::addTo($app);
  $m = new Betools\_General\Models\BetoolsUserList($app->db);

  $m->addAction('test', function ($m) {
      return 'test from ' . $m->getTitle() . ' was successful!';
  });
  $g->setModel($m);
  $g->addActionButton('test');
}
```

When clicking the test button on the grid, I'm getting the error: "!! ATK4 UI ERROR: Callback requested, but never reached. You may be missing some arguments in request URL. !! "

I compared it to the demo file where it is working and tried to implement the Lock trait etc. but there's still something missing.

What am I missing?

**Comment by bedengler** [comment]
Very strange thing that I found out now:
when I remove the 

`if(isset($_REQUEST['sub'])) {`

it works. But keeping it, breaks it...

WTF?

**Comment by DarkSide666** [comment]
Why you need this `if` statement? What's the purpose of it?

**Comment by bedengler** [comment]
I'm loading content or setting filters (in tables and views) depending of the submitted variables (e.g. user clicks a link and I'd like to submit a value through this link to my app).
I'm feeling like the only person needing that. 
So there must be another approach of achieving the same. 
What is the best practice for that purpose?

I also opened a gist: https://gist.github.com/bedengler/36775f2f964266ad08c3a4187bbf5d4f

**Comment by bedengler** [comment]
Example: www.myapp.com/?showme=pictureTable
This could for example show a grid where you just see entries with pictures.

**Comment by DarkSide666** [comment]
Ah I see.
Try setting this argument as sticky so it's not lost in callbacks.
`$this->app->stickyGet('showme');`

**Comment by bedengler** [comment]
Ok, that did the trick. 
My final code looks like this now: 
```
$app->stickyGet('sub');

if(isset($_GET['sub'])) {
  $g = \atk4\ui\Grid::addTo($app);
  $m = new Betools\_General\Models\BetoolsUserList($app->db);

  $m->addAction('test', function ($m) {
      return 'test from ' . $m->getTitle() . ' was successful!';
  });
  $g->setModel($m);
  $g->addActionButton('test');
}
```
I just added "$app->stickyGet('sub');" before calling $_GET
