### ISSUE TITLE
"View Source" in Agile UI Demo v2.1.0 is not working

### ISSUE THREAD

**Issue by TheNetworkIsDown** [atk4/ui#1163]
For example, clicking "View Source" on https://ui.agiletoolkit.org/demos/form.php sends me to https://github.com/atk4/ui/blob/develop/demos/form.php,  which results in a "page not found".

As a sidenote: It would be great if it was possible to open the source in a different window/tab.

**Comment by DarkSide666** [comment]
Demo files was reorganized, so need to fix this too accordingly

**Comment by ibelar** [comment]
Because v2.1 still point to develop and demos file where reorganize there. It will be ok when we issue the next release.
