### ISSUE TITLE
How to link an image properly?

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#1165]
How do I link an image? 
`$logoLeft = atk4\ui\Image::addTo($leftmenu, ['images/mebLogo.gif']); `
should link to index.php

`$logoLeft = atk4\ui\Image::addTo($leftmenu, ['images/mebLogo.gif'])->link("index.php");`
doesn't work

`$logoLeft = atk4\ui\Image::addTo($leftmenu, [$rootdir.'html_public/MAM/images/mebLogo.gif'])->on('click', new \atk4\ui\jsExpression('document.location="'.$rootdir.'html_public/MAM/dashboard.php";'));`
works, but is there a solution without Javascript?

**Comment by mvorisek** [comment]
Better to use forum for these questions.

If I understand correctly, you want to add a link/anchor to the images - so exactly like in html, wrap the image with `<a>`, so in Atk firstly create a link/anchor and then add the image to it.
