### ISSUE TITLE
Spacer?

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#1169]
Is there a function to add a spacer in the ui?
E.g. 
`Spacer:addTo($app, '40');`
...results in a full width div with a height of 40px...

Otherwise I'd suggesting implementing it.

**Comment by DarkSide666** [comment]
I don't see usefulness of such view.
You can add empty View (div) already with something like `View::addTo($app)->setAttr('height','40px')`.
Do we need special view subclass for this - I doubt.

**Comment by bedengler** [comment]
Thanks,
I'm trying to have some spacers in the left menu ("Admin" layout) between items. 

If I'm using this line
`\atk4\ui\View::addTo($app->layout->menu)->setAttr('height','80px');`
nothing happens.

I've also tried applying that within the body content with something like this:
`\atk4\ui\View::addTo($app)->setAttr('height','80px');
$col = $app->add(new \atk4\ui\Columns());
$v = $col->addColumn(6)
$v->add(['Text','<h2>Blablabla</h2>']);`

The column isn't going down by 80px!
Are you sure this is working? What am I doing wrong here if yes?

**Comment by bedengler** [comment]
I have investigated further. 
Adding juts the line 
```\atk4\ui\View::addTo($app->layout->menu)->setAttr('height','80px');```
does nothing. It even doesn't render the div.

Adding 
```
$testview = \atk4\ui\View::addTo($app)->setAttr('height','380px');
$testview->add(['Text','<h2>Blablabla</h2>']);
```

shows something, but it results in
```<div id="atk_admin_view" class="  " style="" height="380px"><h2>Blablabla</h2></div>```

Even removing the "px" doesn't do the trick (which is reasonable as the attribute in a div doesn't do anything). 
Therefore this is no solution.

**Comment by DarkSide666** [comment]
Some time ago there was method `addDivider` in menu. Not sure if we still have it.

**Comment by mvorisek** [comment]
Closing as solution like `View::addTo($app)->setAttr('height','40px')` or maybe with `setStyle` is fully covering this usecase.

**Comment by bedengler** [comment]
`View::addTo($app)->setAttr('height','40px')` doesn't do the job as mentioned above! Please review my last post and test it yourself.

**Comment by DarkSide666** [comment]
Yes. You should use css (style) instead.
So use `setStyle()` method instead of `setAttr()`
