### ISSUE TITLE
DEMO to use SQLite

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#1175]
ATK's support of sqlite has improved. It is also bundled in PHP.

It would be great to run ATK demo with SQLite by default. SQLite file should also be created by demos/Dockerfile.

This would eliminate need for DSN environment variable and we could run demo just with:

```
docker run -p 8080:80 -t atk4/ui-demo:develop
```

**Comment by mvorisek** [comment]
It should be already possible - set DSN to sqllite , see https://github.com/atk4/ui/blob/160be0e6976ff3480d8eba7eddf6d683a4ff9d67/demos/Dockerfile#L37

Or - and I prefer it - fallback to sqlite by default if DSN env. var is set, help wanted.

**Comment by mvorisek** [comment]
it should be easy by dumping the sql data to sqlite db in Dockerfile
