### ISSUE TITLE
$grid->addColumn('name',['Link', 'url' => 'url.php?tid={id}']) prevents to use 'date' column

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1184]
To reproduce:
grid with two columns, e.g. `name` and `duedate`; where `duedate` is defined as `'type'=>'date'` in model

Then create a grid:
if you `$grid->addColumn('name')` all works, if you `$grid->addColumn('name',['Link', 'url' => 'ticket.php?action=edit&tid={id}'])` it throws this error:
```
"Value should be scalar" field:  duedate
```
in template. 
If remove the `'type'=>'date'` for `duedate` in the model, the grid works again...

**Comment by mkrecek234** [comment]
By the way, also the $grid->addFilterColumn(); does not work anymore if I add a name decorator as above - it throws the error "Error : Call to a member function addPopup() on array" on Grid.php:473

**Comment by DarkSide666** [comment]
@mkrecek234 please create new github issue for this or provide PR.

**Comment by mkrecek234** [comment]
OK, will do.
