### ISSUE TITLE
Implement compatibility branches and patch releases

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#1189]
As agreed on the maintainer meeting, we should be able to create version-specific branches:

 - 2.0
 - 1.7
 - 1.6

The branch would need to be created every time we do a release. 

 - [ ] Need Github workflow allowing us to create new release from a versioned branch.
 - [ ] We need to protect release branches (so that they are not deleted)

**Comment by mvorisek** [comment]
I think the branches should be named like `2.0.x` and presented only until they are supported (but keep all release tags of course).

Managing large amount of branches is time expensive - at least I can not do that - so I propose keeping the branch count to minimum or maybe even version only major versions. So I prefer only `develop` (latest major version) and `1.x` (all previous major versions, ie. `2.x` once we increate the latest major version).

Other minor branches should be created only when needed, ie. we changes needs to be added to an already released versions.

With this, I would also propose, very important change for releases:
Always reset to the head of the source branch and commit the release changes on top of it with single release commit/compiled changes.

Then it is much more clear (than squashing/cherry-picking all previous changes like now) what did the release process added/changed (like css files were compiled and composer.json updated). And, any tag can be checkouted and the dev can continue on the previous commit anyone when needed, no matter if major, minor, ...

**Comment by mvorisek** [comment]
closing as too broad/old topic
