### ISSUE TITLE
Lister does use undefined property "current_row"

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1197]
https://github.com/atk4/ui/blob/3fd37f0bee0d43f01e9eccb41e96b9dc3466d5ca/src/Lister.php#L139

Either define it properly or do not use it at all.

**Comment by mvorisek** [comment]
ping @DarkSide666 @ibelar

**Comment by DarkSide666** [comment]
It can be used in `beforeRow` hook. I think it should stay there.
For example https://github.com/atk4/ui/pull/1196/files#diff-8a7518699f45ce47a7f72cb7eaf73ca0R15

**Comment by mvorisek** [comment]
It should stay there, the issue should stay too and need another answer :)

**Comment by DarkSide666** [comment]
You mean - need to add current_id and current_row definitions in Lister class? If so, then yes of course.

**Comment by mvorisek** [comment]
Yes, I do not know the logic there, so only reporting it...

>  need to add current_id and current_row definitions in Lister class?

`current_id` and `current_row` - the first one is probably a duplicate of the first one, (cloned) row should be enough

**Comment by DarkSide666** [comment]
Let's just add definitions for both in Lister class.
