### ISSUE TITLE
Add some NS to demos

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1199]
Otherwise some absolute type names are without the leading slash.

And then probably mass import ui and data root namespaces. And rerun fixer.

**Comment by mvorisek** [comment]
@DarkSide666 @ibelar Propose NS for demos you want, it will never be used for autoload, at least not now, so it should not matter that much...

**Comment by DarkSide666** [comment]
.../Demo :D

**Comment by mvorisek** [comment]
so like tests?

**Comment by DarkSide666** [comment]
namespace /atk4/whatever/demo;
