### ISSUE TITLE
Demos Table2.php issue

### ISSUE THREAD

**Issue by abbadon1334** [atk4/ui#1209]
Table current_row is now an array : https://github.com/atk4/ui/blob/0652ab852a40a89f8a49a1806b51fba063854842/src/Table.php#L491

in demos/table2.php is used as a model
https://github.com/atk4/ui/blob/0652ab852a40a89f8a49a1806b51fba063854842/demos/collection/table2.php#L28

**Comment by mvorisek** [comment]
@abbadon1334 @DarkSide666 issue introduced by me in 2e95ade56bc55c3c9dfea93d7479ceb8d052b432

but I already opened a bug report for it 4 days ago - https://github.com/atk4/ui/issues/1197

exactly this happen where there is no doc...
