### ISSUE TITLE
refactor App:url() moving '.php' extension outside

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#121]
I generally would prefer that 3rd party frameworks would supply their own implementation for url() which would use their page-to-url mapper. So the existing code wouldn't be used at all and is there just for a raw file usage.

Depending no how we go once we become more popular we might need to clean up by taking .php out.

**Comment by acicovic** [comment]
This is already possible with `App->url(['mypage']);`.

We could probably close this.

**Comment by DarkSide666** [comment]
I would say - close it, but Romans wanted to close issues himself during weekly hangout so adding label.
