### ISSUE TITLE
Expand left menu for demos by default

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1233]
For better UX, at least I find it better and also almost every major UI framework has left menu expanded.

**Comment by ibelar** [comment]
Are you referring to having the left menu visible by default? If so then this is fix by #1217

**Comment by mvorisek** [comment]
No, to expand the left menu items on load, so instead of:
![image](https://user-images.githubusercontent.com/2228672/84159346-44c2dd80-aa6d-11ea-9888-cdc4fda6d489.png)
load it as:
![image](https://user-images.githubusercontent.com/2228672/84159387-4db3af00-aa6d-11ea-91e4-a754c4b9adef.png)

the also `ctrl+f` for demo search can be used

**Comment by ibelar** [comment]
Sorry but I do not fully agree with you on this one. Having all items expanded will make it more difficult to see which categories a site contains. For demo as an example, it will certainly be bigger than screen size. This mean that you will have to scroll down every time for finding or reaching on lower categories.

Would be even worst on a smaller screen.

**Comment by DarkSide666** [comment]
I tend to agree with @ibelar on this.

**Comment by mvorisek** [comment]
> This mean that you will have to scroll down every time for finding or reaching on lower categories.

I like hard data, but for this one I can only point to other frameworks where it is expanded usually by default. My reason is at least because of easy search as I usually od not know where what is.

Let's wait also for @romaninsh and @abbadon1334 opinion. If they like, let's expand it by default, if not, let's close it.

**Comment by ibelar** [comment]
One more thing with this: let say you click on a link at the bottom of the left menu, which you had to scroll down for clicking it. Then when page reload, what do you do? Scrolling the left menu content to the top of the menu to highlight the proper menu item user just clicked? But then you lose what is on top and you have to scroll up again.

The last point, you can always have similar behavior as you ask using the Admin layout instead of Maestro.

**Comment by mvorisek** [comment]
I am aware of these downsides.

Shoul be probably solved by adding "expand/collapse all" button and search (seach in menu item name) next to it. Everyone is happy :)

Example:
![image](https://user-images.githubusercontent.com/2228672/84185198-eb6ba600-aa8e-11ea-8d7a-f97dbb05add3.png)

**Comment by DarkSide666** [comment]
Expand/collapse all and Search would be nice, but of course it's just a nice feature nothing more.
