### ISSUE TITLE
Boolean field in model breaks form save when not checked

### ISSUE THREAD

**Issue by skondakov** [atk4/ui#128]
If you have a form with a model with a boolean field and submit WITHOUT checking the checkbox - when you try to $f->model->save() after submit - you get an error like this:

https://www.screencast.com/t/AYLXTOjf7w

**Comment by DarkSide666** [comment]
How is this field defined in your model? Especially interested in `mandatory` and `required` parameters.

**Comment by romaninsh** [comment]
Zak, are you on crud branch? It's re-implemented for CRUD:

http://ui.agiletoolkit.org/demos/form3.php

However there is still some problem with check-box. If you tick then un-tick it, form still thing that it's ticked. It seems to be Semantic UI issue though. I haven't found related issue yet.

**Comment by romaninsh** [comment]
Please see related #130.

**Comment by mvorisek** [comment]
fixed and tested by https://github.com/atk4/ui/blob/0d31ca39b3562b2bae1a49ecb5eced17383c5a38/tests-behat/checkbox.feature
