### ISSUE TITLE
Demo fails on Array_ persistence creation

### ISSUE THREAD

**Issue by georgehristov** [atk4/ui#1290]
Is this issue due to changes in Array persistence?

![demo](https://user-images.githubusercontent.com/8128250/84694556-ae4d5b00-af49-11ea-9a85-57173dbad6d2.png)

**Comment by mvorisek** [comment]
provide exact steps to reproduce on demos - example report: https://github.com/atk4/ui/issues/1254#issue-634973749

may be related with https://github.com/atk4/data/pull/627 or because the new strict types applied to ui and/or data

**Comment by georgehristov** [comment]
@mvorisek Just follow the demo intro and you will get the errors.
How is it working now for saving the data to the session as Array_ persistence?

**Comment by mvorisek** [comment]
see https://github.com/atk4/ui/pull/1205/commits/ff6866a6f9f91fbaed7ff0e90d2bfaaf1d438e07#diff-d51e445eb72461e0ced686727ad8de29R68

**Comment by georgehristov** [comment]
This new functionality must be reflected in the docs
https://github.com/atk4/data/blob/develop/docs/persistence.rst

**Comment by mvorisek** [comment]
> 
> 
> This new functionality must be reflected in the docs
> https://github.com/atk4/data/blob/develop/docs/persistence.rst

please update it there - all mentions should be complete removed from data - and in ui we support it I think with the Session trait, there is also some Session class in the `demos/_includes/`...
