### ISSUE TITLE
Hard dependency on Agile Data?

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#13]
Arguments 👍 
- more people will try Agile Data
- can shift some code out (e.g. Form field population)
- no need for MVC Controller
- better conception (all data must live somewhere!)

Arguments 👎 
- unnecessary dependency, UI can work without Data.
- can be more appealing for users, bigger exposure
- better backwards compatibility

**Comment by romaninsh** [comment]
Form with dependency on Agile Dada:

- once `Form` has been loaded from POST, data needs to be stored somewhere. What better place could there be than a model?
- you may say - using Array sources are cool, but they don't have types :(
- will prompt us to make more persistences (array, session etc)


- types?

**Comment by DarkSide666** [comment]
Well, hardly coupling UI with AD is definitely good and there are a lot of good things about that solution (as You mentioned above).

But, there should also be solution how to work with at least simple forms / views without models. For example, simple feedback form, which simply sends everything it gets from POST to e-mail. Or some kind of search forms.
Also one thing to note is that UI widgets are not only forms, listers, grids and menus. There can be a bunch of other views which are not related to data models at all. For example, some visual elements - message boxes, popups, dividers, simple div blocks etc.

Also, as you mentioned above, if we make hard dependency on AD, then UI will almost not be usable in other apps. That is a bit of drawback and can take part of possible community away.

So, to wrap up, I'm not sure which way to choose now. Both have pros and cons, but hard-coupling UI with AD probably have more pros than cons. Maybe we can introduce simple and straightforward controller level which works between UI and AD. Then if we need UI to work with Laravel models, for example, then we can develop extension - UI controller for Laravel models without changing anything in UI or AD ...

**Comment by romaninsh** [comment]
When you say sends to email, i assume you mean passes model containing the data produced by a form into a mailer, right ? Now if mailer can take advantage of model it can format things nicely without you having to worry about things like dates.

So that means that even if you didn't intend to create a model, the form will make one for you. Would it be persisting the model into the database, that's another question.

In current toolkit you can look at the "Menu" and it always being populated with addMenuItem, but it actually supports models too. So you can actually configure Menu through JSON, and Model be a good solution here.

AD is not necesserily used with databases, it can be, but there are so many uses outside of that.

**Comment by romaninsh** [comment]
Closing. The benefits of Agile Data are pretty overwhelming especially in "persist into UI" concept.

**Comment by DarkSide666** [comment]
OK
