### ISSUE TITLE
Console is not outputting anything anymore

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1310]
After trying out the new 2.1 releases and patching all the other components (Login, MasterCrud,...) to work again I found out, that Console is not working anymore.

I had a Console in a Wizard and I use the MethodExecutor from MasterCrud.

In both instances the functions will be called from inside the Console as intended, but Console is never outputting anything.
I get a message inside the Javascript-Console about "Firefox can't connect to Server" (sse).
If I call the link in the Browser, the right function inside my application is called but nothing is returned.

When I use the same link on my old application, I get a object back for the sse-Functionality...

I am using atk4/ui:2.1.2

**Comment by DarkSide666** [comment]
It returns HTTP 500 error with text:

```
id: js

!! ATK4 UI ERROR: Unexpected output detected. !!
```

**Comment by mvorisek** [comment]
Provide steps to replicate on demos, closing for now as no reaction.
