### ISSUE TITLE
Is there a guide on how to use AgileUI components with Agile Data?

### ISSUE THREAD

**Issue by humanitiesclinic** [atk4/ui#1322]
Is there a guide on how to AgileUI components with Agile Data?

For example, on https://agile-ui.readthedocs.io/en/latest/table.html

$table = Table::addTo($app);
$table->setModel(new Order($db));

I do not understand how the class "Order" comes about. There's some reference to Agile Data. So I assume it's got to do with that.

When I open Agile Data's documentation, I am quite lost.

Please, can anyone help me?

**Comment by georgehristov** [comment]
Class `Order` in this case extends `\atk4\data\Model`.

You can read on how to implement Model [here](https://agile-data.readthedocs.io/en/develop/model.html#Model::init)
And also check all demos (for instance [here](https://github.com/atk4/ui/blob/develop/demos/_includes/Flyers.php) you have pure model definition and [here](https://github.com/atk4/ui/blob/develop/demos/form/form2.php) at the end of the file you have model which you add to a form)

**Comment by mvorisek** [comment]
see docs & demos/
