### ISSUE TITLE
TableColumn\Template not supporting HTML

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#135]
Previously Template could be used to specify HTML template, now it escapes HTML. 

I think the template must allow HTML, while template arguments (field alues) must still be escaped. We need a test for that.

**Comment by DarkSide666** [comment]
I agree, that Template should allow HTML. That's why Template is there actually :)

What you mean by "field values" which needs escaping? Currently all template is just one solid string and we can't differ template itself from included field values.

**Comment by romaninsh** [comment]
This is implemented in #165.

**Comment by romaninsh** [comment]
how about adding HTMLTemplate column?

**Comment by romaninsh** [comment]
stale..
