### ISSUE TITLE
Improve CRUD Style

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#136]
Current CRUD version has icons for edit / delete. They are quite hard to click and don't look pretty.

<img width="1130" alt="screen shot 2017-04-19 at 11 38 46" src="https://cloud.githubusercontent.com/assets/453929/25176036/c6ecc1f6-24f4-11e7-94c2-79c681d1237f.png">

**Comment by mayack** [comment]
Hi.

According to modern UI standards, row actions need to be moved to a popover that becomes visible after clicking '3 dotted icon' at the end of every row. This approach is more space efficient and also removes hassle over choosing the right icons.

Here are few examples:

<img width="1392" alt="messages image 764756597" src="https://cloud.githubusercontent.com/assets/540261/25176576/3a79d70a-2507-11e7-89d3-dc206aecfad9.png">
![messages image 1503417498](https://cloud.githubusercontent.com/assets/540261/25176584/3e1a165e-2507-11e7-8bb8-cdc81873e747.png)

**Comment by romaninsh** [comment]
Some links:
 - http://codepen.io/Biggrecian/pen/vOdwLd
 - https://datatables.net/examples/styling/semanticui.html

Semantic supports popup menus:
<img width="881" alt="screen shot 2017-04-19 at 12 00 06" src="https://cloud.githubusercontent.com/assets/453929/25176909/c73d2936-24f7-11e7-8183-82d4d1fbcac6.png">

**Comment by romaninsh** [comment]
Slightly cleaned up actions in #156 but need support from menus still.

**Comment by romaninsh** [comment]
closing fro now, looks good enough.
