### ISSUE TITLE
CRUD row actions should be rendered per each row (template rerender/reuse)

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1365]
If one a row/Model does not permit some action or require a different render like different icon, it is not currently not possible.

This is a feature request to not prerender anything.

slightly related with https://github.com/atk4/data/issues/382

**Comment by mkrecek234** [comment]
@mvorisek here are typical use cases for row level action rendering:
- Varying access rights for the user per row - e.g., user is allowed to view all customer records, but edit only his own
- Completed tasks may no longer be edited or deleted, open tasks continue to have activated edit/delete buttons
- etc.

**Comment by mkrecek234** [comment]
Check also https://github.com/atk4/ui/pull/1868 - addAction isDisabled feature already allows for row-level closure, see also extension to addModalAction isDisabled support in that PR.
