### ISSUE TITLE
Date picker popup style issue

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1376]
The date picker is not displayed correctly (see ui.agiletookit.org):
![image](https://user-images.githubusercontent.com/28671486/88304324-679d0e80-cd08-11ea-8c8f-4747ca3738bc.png)

Seen on most recent Safari 14.0 (Beta). Issue also on current official iOS Safari. In Chrome it renders properly.

**Comment by mvorisek** [comment]
Compared to FUI demo, the calendar should have padding equal to 0px:
![image](https://user-images.githubusercontent.com/2228672/88453419-fa53bf80-ce66-11ea-9530-bc85e4ac3461.png)

but for some reasons in atk4 this CSS rule is not there...

@mkrecek234 see https://fomantic-ui.com/modules/calendar.html , if you set the padding to 0px on the owning calendar div manually, is this issue gone?

**Comment by mkrecek234** [comment]
I changed the following to padding: 0 from padding: .833em 1em in .ui.popup of the owning div ui popup calendar and then it works
![image](https://user-images.githubusercontent.com/28671486/88640052-c9b99300-d0bd-11ea-9444-f75f958a322b.png)
