### ISSUE TITLE
Dropdown readonly not working (with isMultiple)

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1382]
If you add a Dropdown control with parameter 'readonly'=> true and isMultiple => true, the control cannot be "edited" in terms of selecting additional entries, BUT: you can still click on the 'X' for each entry and remove it.

Solution. Disable the "'X' delete item" functionality if readonly is set to true.

**Comment by georgehristov** [comment]
Just tried it by modifying the demo and all appears working as intended?

![demo](https://user-images.githubusercontent.com/8128250/88546141-3e3bf580-d01c-11ea-9653-f70f4297cf0f.png)

**Comment by mkrecek234** [comment]
FYI in "disabled" mode everything is working, but in readonly mode you can still delete single items of a multiple item list
