### ISSUE TITLE
Sticky global must apply to self and subtree only

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1385]
issues to fix described in already merged https://github.com/atk4/ui/pull/1377

I find out that https://github.com/atk4/ui/pull/1377#discussion_r463019668 issue depends somehow if the field is required or not.

When field is required - CRUD form does reload (/wo error), when not required, form submits as expected.

**Comment by mkrecek234** [comment]
Similar issue here: I have a grid with a ModalAction. The ModalAction does the following: Loading the record=email, if it's an email in the outbox (message_type_id=3) then it's being changed back to "draft" (message_type_id=2) upon opening the modal. HOWEVER, if you submit then the edited email and send it=submit the form (message_type_id=3) an a JSReload($grid) is returned onSubmit, the modal is re-initialised, and the just submitted message_type_id=3 is reverted back to =2. Here is the code snippet:
`$this->addModalAction(['icon'=>'edit'], 'Edit', function ($v, $id) use ($grid) {
                       
$grid->model->load($id);
            
if ($grid->model->get('message_type_id') == 3) {
    $grid->model->set('message_type_id', 2);
    $grid->model->save();
}
 
$mv = MessageForm::addTo($v, ['message_type_id' => $grid->model->get('message_type_id')]);
$mv->setModel($grid->model);
           
$mv->onSubmit(function($form) use ($grid,$v) {
     $form->model->save();
                             
     return [
                    $v->owner->hide(),
                    new \atk4\ui\JsReload($grid) // THIS RELOAD CAUSES THE MODAL TO RE-INITIATE AND THEN THE MESSAGE_TYPE_ID THAT WAS SUBMITTED TO BE 3 IS CHANGED BACK to 2. BUT HOW TO SOLVE? A $GRID->MODEL->unload after save does not help to destroy the id context.
                ];
            });
        }); `

**Comment by mkrecek234** [comment]
And another stickyArg issue as noted in atk4/login : https://github.com/atk4/login/issues/41

**Comment by mkrecek234** [comment]
Regarding my comment, this is not a bug after further consideration: As the modal is rendered on grid load, the code is executed, not only on modal open. if you implement it with a dynamically loaded VirtualPage with JsModal, the database update above is handled correctly by ATK4.

**Comment by mvorisek** [comment]
So your local issue and I should remove it here, right?
