### ISSUE TITLE
Dropdown/Lookup control not behaving correctly

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1411]
I have a Dropdown control based on this configuration:
```
            $recipient = $gr1->addControl('recipient',
                [\atk4\ui\Form\Control\Dropdown::class, 
                    'isMultiple' => true,
                    'dropdownOptions' => ['allowAdditions' => true]
                ]
                );
            
             $recipient->setModel($model->ref('ticket_id')->ref('customer_id')->ref('CustomerContact'));
```
If you then click the dropdown arrow and select the first email (of 2), then click OUTSIDE of the control, e.g. to the next input field, it then adds a second email from the dropdown erroneously. Very annoying.

**Comment by PhilippGrashoff** [comment]
Hi, could you make a short screencast? Sounds like this is FUI related and not an ATK issue.

**Comment by mkrecek234** [comment]
I could fix the issue by adding the forceSelection => false option to the Fomantic UI dropdown:
`$recipient = $gr1->addControl('recipient',
  [\atk4\ui\Form\Control\Dropdown::class, 'width' => 'twelve',
  'empty'      => 'Email address',
  'isMultiple' => true,
  'dropdownOptions' => ['allowAdditions' => true, 'forceSelection' => false]
  ]
);`
