### ISSUE TITLE
Form error label is not dissapearing

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#142]
If form has an error, sometimes the error does not dissapear even after i change value and submit form again:

<img width="347" alt="screen shot 2017-04-26 at 16 37 03" src="https://cloud.githubusercontent.com/assets/453929/25443052/a1761e86-2a9e-11e7-917f-278b4892583e.png">

**Comment by acicovic** [comment]
This is observed on Calendar controls.

**Comment by ibelar** [comment]
Fomantic-UI calendar module prevent the input field from catching the regular change event we normally use for removing error prompt.
Therefore manually setting  onChange handler to remove error prompt is need here for Calendar field.

```
$date_time = $f->getField('date_time');
$date_time->setOption('onChange', new jsFunction([$f->js()->form('remove prompt', $date_time->short_name)]));
```

**Comment by DarkSide666** [comment]
Can this be implemented in Calendar field decorator class?

**Comment by ibelar** [comment]
> Can this be implemented in Calendar field decorator class?

It could but what if you need you own specific onChange handler?

**Comment by DarkSide666** [comment]
Yeah that's not good then.

**Comment by stokkeland** [comment]
any workarounds ever come around for this issue? 
I am not as savvy in JS at this integrated level - i cannot get the calendar workaround to work for FormField Upload.. to me it would be natural in the Upload case to clear the error with the onDelete event at least.. i  tried in onDelete:
'''
return new \atk4\ui\jsFunction([$form->js()->form('remove prompt', 'file_field_name')]);
'''
but that gives me JS Error Message (Function Statement requires a function name) so I am guessing i am missing a few things..

**Comment by stokkeland** [comment]
@PhilippGrashoff helped me with a solution workaround specifically to Upload - in onDelete:
`return $form->js()->form('remove prompt', 'file_field_name');`

**Comment by DarkSide666** [comment]
Blocked by https://github.com/atk4/ui/pull/869

**Comment by mvorisek** [comment]
@DarkSide666 still valid?

**Comment by DarkSide666** [comment]
@ibelar Can you please check this sometime ?

**Comment by mvorisek** [comment]
no response, please reply if the problem is still present
