### ISSUE TITLE
Form\Control\ScopeBuilder Rule on Date Field

### ISSUE THREAD

**Issue by georgehristov** [atk4/ui#1420]
When adding a rule on date field the current date is set as rule value by default in the UI component but not in the resulting JSON.

**Comment by ibelar** [comment]
@georgehristov - That was the intention to always get the same result from it. I thought that the return value should be format on the server-side. Can you explain what should be done then?

**Comment by mvorisek** [comment]
@ibelar I belive the issue is, that default field value does not trigger field update, you probably listen on keydown even instead of field change

**Comment by georgehristov** [comment]
@ibelar to reproduce it you can use the ScopeBuilder demo and add rule on "Start Date" field for example:

![scopebuilder-bug](https://user-images.githubusercontent.com/8128250/91633918-9172e080-e9ec-11ea-99fc-5c372dfecb71.png)

**Comment by ibelar** [comment]
Thks - now fix in #1430
