### ISSUE TITLE
Feature request: make \atk4\ui\Form optionally able to load model automagically

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#1434]
Currently you always have to define a model first that you connect to a form.
This means double of work. Because you have to define the fields you'd like to load first in the model and then you have to define it again in form, if you want to use for example a group.

Current approach: 
```
class Country extends \atk4\data\Model
{
    public $table = 'country';

    protected function init(): void
    {
        parent::init();
        $this->addField('name', ['actual' => 'nicename', 'required' => true, 'type' => 'string']);
        $this->addField('sys_name', ['actual' => 'name', 'system' => true]);
     }
}

class CountryForm extends \atk4\ui\Form
{
    function addControlsPost() {
        $gr = $this->addGroup('Company');
        $gr->addControl('name', ['actual' => 'nicename', 'required' => true, 'type' => 'string']);
        $gr->addControl('sys_name', ['actual' => 'name', 'system' => true]);
     }
}

// load the model
$country = new Country($db);
$country->load(3);

// load form
$form = CountryForm::addTo($app); 

// assign previously loaded model + data to form
$form->setModel($country, false);

// render controls - if you just define your controls in init of CountryForm, the loaded data will NOT show up as the model renders before the controls
$form->addControlsPost();
```

This is a lot of overhead. Especially if you need to define many fields. A slightly more effective approach would be using the allFields() method in the model. This saves you from having to define all fields in the model first:
```
class Country extends \atk4\data\Model
{
    public $table = 'country';

    protected function init(): void
    {
        parent::init();
        $this->allFields();
     }
}

class CountryForm extends \atk4\ui\Form
{
    function addControlsPost() {
        $gr = $this->addGroup('Company');
        $gr->addControl('name', ['actual' => 'nicename', 'required' => true, 'type' => 'string']);
        $gr->addControl('sys_name', ['actual' => 'name', 'system' => true]);
     }
}

// load the model
$country = new Country($db);
$country->load(3);

// load form
$form = CountryForm::addTo($app); 

// assign previously loaded model + data to form
$form->setModel($country, false);

// render controls - if you just define your controls in init of CountryForm, the loaded data will NOT show up as the model renders before the controls
$form->addControlsPost();
```

My feature request now is, to have an option in the Form that allows us to define a persistence (e.g. db & table) which just does was the "Country" class from above does: it loads up the model with the defined persistence and all fields.
And it adds the defined controls AFTER loading the model.

The following code from above will then have the SAME FUNCTIONALITY as above, but with A LOT LESS EFFORT and way more effective and straight forward:
```
class FormLoad extends \atk4\ui\Form
{
    function render() 
    {
        $gr = $this->addGroup('Company');
        $gr->addControl('name', ['actual' => 'nicename', 'required' => true, 'type' => 'string']);
        $gr->addControl('sys_name', ['actual' => 'name', 'system' => true]);
     }
}

// load form
$form = FormLoad::addTo($app); 

// define model data / persistence - if not defined, form behaves the same as it does currently
$form->db = $app->db;
$form->table = 'tablename';
$form->load = '3';
$form->render();     // renders the form after doing all the configuration stuff
```

**Comment by mvorisek** [comment]
just override setModel(), closing

we can reopen if you provide an example code how to modify this lib

**Comment by bedengler** [comment]
Is this documented anywhere?
How can you override setModel, but use a model in a form (= saving the form data to a certain persistence)?

**Comment by mvorisek** [comment]
we use clean code as a documentation, what to do is obvious when you want to process something right after `Form::setModel`

**Comment by bedengler** [comment]
But you have to process something after setModel if you want to load an entry as there has to be addControls in first place and after that the model has to be loaded.

In addition you have to create a model class, even if you need all fields of a model. 

The approach is just not "automagical". I'm working on some code examples...
