### ISSUE TITLE
https://forum.agiletoolkit.org/ has an old certificate

### ISSUE THREAD

**Issue by rickyosser** [atk4/ui#1437]
Hi!

The forum at https://forum.agiletoolkit.org/ has an old cerficate, this should be fixed.

**Comment by mvorisek** [comment]
It expires on 9th Dec 2020

**Comment by rickyosser** [comment]
Hi,

the certificate is fixed, login is still non-functional. It redirects to https://www4.agiletoolkit.org/dsso which doesn't answer.

Just a heads up!

Best regards
Rickard

**Comment by rickyosser** [comment]
> It expires on 9th Dec 2020

Hi,

the certificate is fixed, login is still non-functional. It redirects to https://www4.agiletoolkit.org/dsso which doesn't answer.

Just a heads up!

Best regards
Rickard
