### ISSUE TITLE
$grid->addQuickSearch generates 2 jqueries in certain cases

### ISSUE THREAD

**Issue by rickyosser** [atk4/ui#1459]
Hi,

I've got this strange problem of $grid->addQuickSearch giving me:
Critical Error
atk4\ui\Exception: Callback requested, but never reached. You may be missing some arguments in request URL.

In both cases where this happens the operation sends 2 jqueries to the server. One __atk_reload which seems to be working correctly and one __atk_callback which shouldn't be sent at all.
The 2 cases are empty field and pressing lookingglass and the other is filled out field and pressing "x".

Using "Escape" works as intended.

I'm running the dev-branch.

Thanks in advance
Rickard

**Comment by PhilippGrashoff** [comment]
Hi Ricky,

could you provide a code example and maybe some screenshots, especially about the 2 requests?

Thanks!

**Comment by rickyosser** [comment]
Hi Philipp,

Here is the code:

```<?php
require_once("init.php");

if (isset($_SESSION["user_id"]) && isset($_SESSION["is_admin"])) {`
    $app = new MyApp($dsn, true);
} else {
    $app = new MyApp($dsn, false);
}

\atk4\ui\Header::addTo($app)->set($app->translator->_("Dashboard"));
\atk4\ui\View::addTo($app, ["ui"=>" divider"], ["Content"]);

$form = \atk4\ui\Form::addTo($app);
$form->buttonSave->destroy();

$registrations = new myrfid_registrations($app->db, ["translator" => $app->translator]);
$registrations->addCondition("user_id", $app->user["id"]);


$grid = \atk4\ui\Grid::addTo($form, [
    "ipp" => 10,
    "pageUpdate" => true,
], ["Content"]);

$grid->setModel($registrations, [
    "sku_description",
    "products_serial_no",
    "comment",
    "conversion_name",
    "format_name",
]);
```

I've attached example pictures as well, both before and after, check the pages loaded in the debug-network part.

![Screenshot from 2020-09-30 01-13-33](https://user-images.githubusercontent.com/22371262/94626528-8c3ed500-02bb-11eb-8b14-5f395d9da1a4.png)
This is a dummy search, allan is not in the DB.

![Screenshot from 2020-09-30 01-13-18](https://user-images.githubusercontent.com/22371262/94626600-b6909280-02bb-11eb-848c-df3c731515bb.png)
Pressing x on the dummy search (any search) renders this result, with 2 queries, 1 reload and one atk_callback. the reload is correct but the atk_callback shouldn't be called in this case.

![Screenshot from 2020-09-30 01-12-41](https://user-images.githubusercontent.com/22371262/94626613-bee8cd80-02bb-11eb-905c-02d4f4809658.png)
This is a standard grid with quicksearch. Nothing special at all.

![Screenshot from 2020-09-30 01-12-26](https://user-images.githubusercontent.com/22371262/94626627-c4461800-02bb-11eb-8ab7-a99f698e74f0.png)
Here we just pressed the looking-glass, it triggers an atk_callback but should really do nothing at all as there is nothing entered in the search-box.

**Comment by ibelar** [comment]
@rickyosser - Probably because your grid is added to the $form view, thus creating url with a form callback. Is there any specific reason why you need to place your grid inside a form?

**Comment by rickyosser** [comment]
Hepp!

No, no reason... 
I'll check the code and see if that fixes it. :)

Thanks,
Rickard

**Comment by rickyosser** [comment]
> @rickyosser - Probably because your grid is added to the $form view, thus creating url with a form callback. Is there any specific reason why you need to place your grid inside a form?

Ok, that was it... Don't know why I did it that way.... I've learned something today.

Thanks!
