### ISSUE TITLE
There is no support for enum(['M'=>'male','F'=>'female'])

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#146]
There is no support for enum(['M'=>'male','F'=>'female']).

In Agile Data we don't support that format and also in Agile UI we ignore that.
Somehow (in Data or UI) this has to be implemented because it's very basic requirement.

For example,
```
$model->addField('gender', ['type'=>'string', 'enum' => ['M'=>'male','F'=>'female']);
```
or as we had in some version quite some time ago
```
$model->addField('gender', [
    'type'=>'string',
    'enum' => ['M', 'F'],
    'ui' => ['listData' =>['M'=>'male','F'=>'female']]);
```
this one looks very cryptic and unnecessary complex for such simple daily requirement.

**Comment by romaninsh** [comment]
Technically that's not an 'enum' and listData makes more sense, but I agree that something must be done here.

**Comment by acicovic** [comment]
@DarkSide666 If I understand the question correctly, this is now possible using the `values` option. For example:
```
$model->addFields(['gender_id', 'values' => ['M' => 'Male', 'F' => 'Female']]);
```
So in that case feel free to close this.

**Comment by DarkSide666** [comment]
Yes you can now use `values` for that.
Thanks for noticing this old issue.
