### ISSUE TITLE
Can't sign in into https://forum.agiletoolkit.org/

### ISSUE THREAD

**Issue by rickyosser** [atk4/ui#1460]
As I mentioned in #1437 the certificate was wrong woth the forum, now when the cert is fixed there seems to be a follow up problem with the sign in/log in.

http://www4.agiletoolkit.org/dsso?sso=<string> gives:
This site can’t be reachedwww4.agiletoolkit.org refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by acicovic** [comment]
I can confirm this. @romaninsh are you in charge of the site or is it someone else?

**Comment by acicovic** [comment]
Closing in favor of #1563
