### ISSUE TITLE
$tabs->addTabUrl not working because of CORS

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1461]
As can be seen on https://ui.agiletoolkit.org/demos/interactive/tabs.php, the $tabs->addTabUrl('Any other page', 'https://example.com/'); does not load a page. Also confirmed in own code. The page just stays blank.
Tested on UI 2.2.

**Comment by DarkSide666** [comment]
You can try this workaround for CORS issue and see if it helps:

Instead of `tabs->addTabURL($name, $url, $settings)` you can try to use
```
$tabs->addTab($name, function () use ($url) {
    return file_get_contents($url); // or use CURL here
}, $settings);
```

**Comment by mvorisek** [comment]
I think this is an issue with the target site, as it does not send required CORS headers.

Is it correct and is there any possible workaround for client/JS?

**Comment by mkrecek234** [comment]
@DarkSide666 Tried your workaround, but the page stays blank - the HTML only contains: 
<div id="_c3781646___virtualpage" class="  " style=""></div>
<script>jQuery(function() {});</script>

**Comment by DarkSide666** [comment]
@mkrecek234 This is how it should look like. It works. Of course it will break all page styling etc. because it's not loaded in isolated DOM (like iframe).

```
$tabs->addTab('Any other page 2', function ($tab) {
    $html = file_get_contents('https://example.com/'); // or use CURL here
    return $tab->js(true)->html($html);
});
```

**Comment by mvorisek** [comment]
what you can do is proxy that page with php and return required headers
