### ISSUE TITLE
DropDown and Lookup in connection with hasOne is not working in CRUD anymore

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1462]
In the newest code in develop (which I need to use...) DropDown and Lookup in a model will not be filled anymore.

I have multiple models with hasOne and in the table everything is fine, but when I try to edit an element, the dropdown or lookup will always return "No results found".

This error is even in the demo visible at https://ui.agiletoolkit.org/demos/collection/actions.php when you try to edit an element, that has a parent-folder set:
![grafik](https://user-images.githubusercontent.com/2448293/94605527-8d5f0a80-0299-11eb-926a-3abbda1bbede.png)

When you set the model explicit to the dropdown everything is working fine.

**Comment by ibelar** [comment]
@karakal - Can you share code on how you defined your model? All seems to be working fine. I think the demo is fine too because hasOne only returns one parent only. @DarkSide666 - can you confirm about file demo data?

**Comment by karakal** [comment]
@ibelar 
All of my hasOne are defined as follows:
`$this->hasOne('Unit', [
            'model' => '<path>\Unit',
            'our_field' => 'unit_id',
            'their_field' => 'id',
            'caption' => 'Unit',
            'required' => true
        ])->withTitle();`

This works out as correctly displayed in the overview:
![grafik](https://user-images.githubusercontent.com/2448293/95204484-73b34b00-07e4-11eb-84f4-90297101cfea.png)

and it will display correctly the selected entry:
![grafik](https://user-images.githubusercontent.com/2448293/95204535-87f74800-07e4-11eb-973c-ab274204161f.png)

But it displays "No result found":
![grafik](https://user-images.githubusercontent.com/2448293/95204596-99d8eb00-07e4-11eb-86a1-f4457e2f4079.png)

although there should be a selection of them:
![grafik](https://user-images.githubusercontent.com/2448293/95204651-ad845180-07e4-11eb-8f5e-139aa0c57aaa.png)

And I don't think the demo is right, because there should be a selection of a lot of root folders...

**Comment by mkrecek234** [comment]
Hi @karakal I had similar strange effects with dropdowns not working - just because the installed PHP version was too old. Upgrade to 7.3 or 7.4 and some mysterious effects might be gone immediately.

**Comment by DarkSide666** [comment]
There surely is some issue (or issues) here with hasOne and dropdowns.
Also model addTitle() added expression field don't load values. Maybe that's because of that.

Will work more on that tomorrow https://github.com/atk4/ui/pull/1477

**Comment by DarkSide666** [comment]
I think it's fixed now.

**Comment by karakal** [comment]
I just installed the freshest version (2.3.1) and it definitely doesn't work:
![grafik](https://user-images.githubusercontent.com/2448293/98932496-b224df80-24df-11eb-9a03-29477d7ddba3.png)

My definition (that worked in former times) was:
`$this->hasOne('LineColour', [
            'model' => 'marbach\connectm\admin\Colour',
            'our_field' => 'colour_id',
            'their_field' => 'id',
            'caption' => 'Farbe',
        ]);`

I tried this definition
`$this->hasOne('colour_id',[new Colour()])->addTitle();`

But it's not working....

**Comment by karakal** [comment]
Okay... It is working in the latest development-Branch from Github :-(
could you do a release anytime soon?

**Comment by DarkSide666** [comment]
@karakal Can you try installing 2.3 like this and tell us if it works then ?
```
    "atk4/ui": "dev-release/2.3 as 2.3.2",
```

**Comment by mvorisek** [comment]
closing as resolved

**Comment by mhuser** [comment]
Hi,
I just stepped on this issue while experimenting the same problem (model with hasOne and "no results")
With the fix, I now see all results...
But filtering the lookup like in
`$form1->getControl('timesheet_project_id')->model->addCondition('user_id', $app->user->getId());`
Doesn't seems to works anymore and adding condition in dependency neither.
Should it?

**Comment by mvorisek** [comment]
please submit a failing test case as PR

**Comment by mhuser** [comment]
@mvorisek thank you for your quick answer. I have forked and branched develop, time to brew coffee and I will give it a try.

**Comment by mhuser** [comment]
I added a segment in demo `lookup-dep` in #1556.
Seems `addCondition` at initialization is working, but not if called on `lookup->model` after.
Not sure how I could turn this code into a true test case. I think I should check in the test if the lookup return a certain array but I cannot see how to manage that.
