### ISSUE TITLE
WIP - DatePicker consistency

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#1467]
### Problem:
- Calendar input uses Fomantic-UI calendar in order to display date selection;
- Vue component like QueryBuilder or Multiline uses v-date-picker for date selection because there are no vue equivalent to Fomantic-ui calendar module;

Although Vue v-date-picker is similar in style to Fomantic-Ui module, they are not the same (see image below).
 - it is possible to use date-time format in Fomantic-Ui module but not in the v-date-picker Vue compnent. 
 - v-date-picker is localizable while Fomantic-Ui is not (unless you provide your own)

### The propose solution:

Drop Fomantic-Ui calendar module and v-date-picker and replace them using Flatpickr : https://flatpickr.js.org/examples/
Flatpickr is highly customizable and has a Vue wrapper equivalent, which would bring consistency within the framework (regular input vs Vue component input) 
Flatpickr also supports more features then Fomantic-Ui calendar module or v-date-picker.

Fomantic-UI calendar module:

<img width="275" alt="Screen Shot 2020-10-02 at 11 15 56 AM" src="https://user-images.githubusercontent.com/2204478/94939939-d7660d00-04a0-11eb-93bd-150996dcf5c0.png">

v-date-picker:
<img width="268" alt="Screen Shot 2020-10-02 at 11 16 12 AM" src="https://user-images.githubusercontent.com/2204478/94939964-dcc35780-04a0-11eb-8ade-81b24949e949.png">

**Comment by mvorisek** [comment]
what is important - to support also date time input and time input only, both with variable precision ranging from hours to microseconds
