### ISSUE TITLE
Error while loading external files on HTTPS

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#147]
Looks like centered layout does not work when installed on HTTPS.

Layout requires file "css" from HTTP site

``` html
    <link rel="stylesheet" type="text/css" href="http://semantic-ui.com/dist/semantic.css">
```

<img width="336" alt="screen shot 2017-04-27 at 10 29 59" src="https://cloud.githubusercontent.com/assets/453929/25477166/802baaca-2b34-11e7-8313-b8e1bddc2909.png">

**Comment by romaninsh** [comment]
Temporary workaround - "use http://" instead of "https://"

**Comment by DarkSide666** [comment]
Can you try setting it this way?
`href="//semantic-ui.com/dist/semantic.css"`

without protocol. It should work and automatically pick correct protocol.

**Comment by romaninsh** [comment]
i thought we switched to CDN.. weird.

**Comment by romaninsh** [comment]
The issue is still there, because jslib is loaded from ui.agiletoolkit.org. We should modify our build so that it uploads complied JS file somewhere.

**Comment by mvorisek** [comment]
Is this issue still valid in 2020?

**Comment by DarkSide666** [comment]
I think no because now we use CDN with https:
```
    public $cdn = [
        'atk'              => 'https://cdn.jsdelivr.net/gh/atk4/ui@2.0.4/public',
        'jquery'           => 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1',
        'serialize-object' => 'https://cdnjs.cloudflare.com/ajax/libs/jquery-serialize-object/2.5.0',
        'semantic-ui'      => 'https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.2/dist',
    ];
```
