### ISSUE TITLE
Localization status

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#1482]
Hello there,

A few localization PRs have been merged in ATK UI, but I'm unsure of its localization status. Is this complete? Are there any guidelines or documentation on how to translate?

Thanks!

**Comment by acicovic** [comment]
@abbadon1334 I am mentioning you here since you are the one who most probably knows best about this.

**Comment by acicovic** [comment]
Hello everyone,

I have created a new repo to start working on this. Feel free to join and help.

https://github.com/acicovic/atk4-localization

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/core/issues/103
