### ISSUE TITLE
[Critical Error][BUG] IPP Bug in https://ui.agiletoolkit.org/demos/collection/grid.php 

### ISSUE THREAD

**Issue by rickyosser** [atk4/ui#1514]
Hi!

Try changing the IPP dropdown on the page...

you get the following error:

Critical Error
TypeError: Argument 1 passed to atk4\data\Model::setLimit() must be of the type int or null, string given, called in src/Grid.php on line 659

**Comment by mvorisek** [comment]
fix will be merged shortly, thanks!
