### ISSUE TITLE
AJAX is sent twice when Lookup control is clicked

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1521]
UPDATE: waiting for release 2.8.8, see https://github.com/fomantic/Fomantic-UI/releases

steps to reproduce:
1. open `/demos/_unit-test/lookup.php`
2. click `Add Product` button
3. open browser network tab
4. click `Product Category Id` dropdown
5. notice, two same AJAX requests are sent for that lookup

is this an issue in Atk, ie. dropdown init?

**Comment by ibelar** [comment]
Looks like a Dropdown module issue from Fomantic: https://github.com/fomantic/Fomantic-UI/issues/1472
Will be fixed in their next release.

**Comment by mvorisek** [comment]
Yes, fixed in FUI 2.8.8
