### ISSUE TITLE
Form with custom IDs fail - inputs are linked to parent element

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#1539]
A PR some time ago caused the immediate closing of a form tag, resulting HTML is something like `<div id="some_view"><form id="some_view_form"></form></div>` All Inputs are linked to the form using its id, e.g. `<input form="some_view_form">`.
This works, so far so good.

But: if the form has a custom ID, it does not work any more. The inputs are no longer linked to the `<form>` element but to its wrapping `<div>`.

Sample PHP:
```
$form = Form::addTo($someView);
$form->id = 'someCustomId';
$form->addControl('someField');
```

The resulting HTML is something like:
```
<div id="someCustomId">
    <form id="id_string_related_to_parents_parent"></form>
</div>

<input form="someCustomId"/>
```

**Comment by mvorisek** [comment]
Please add Behat test

it seems like a bug that can and should be fixed

**Comment by mvorisek** [comment]
maybe fixed by https://github.com/atk4/ui/pull/1769

@PhilippGrashoff is it still present and can you please post a complete repro code?

**Comment by mvorisek** [comment]
@PhilippGrashoff thank you for your reaction, it is already fixed (and you must use `name` instead of `id` property, `id` property no longer exists)

![image](https://user-images.githubusercontent.com/2228672/189521581-468641af-9a35-43cd-b852-5c1bcf0a9d6c.png)
