### ISSUE TITLE
Form not loading boolean value in a checkbox

### ISSUE THREAD

**Issue by skondakov** [atk4/ui#155]
$model = new \atk4\data\Model();
$model->addField('test', ['type' => 'boolean']);
$model['test'] = true;

$f = $page->add(new \atk4\ui\Form(['segment']));
$f->setModel($model);

// When this is done, the checkbox field "test" is not checked

**Comment by romaninsh** [comment]
May be related to #130

**Comment by romaninsh** [comment]
Wasn't this solved?

**Comment by DarkSide666** [comment]
No it wasn't. Issue is in setting field value. I am on it now.

**Comment by DarkSide666** [comment]
Most likely reason for this issue is here: https://github.com/atk4/ui/issues/281

**Comment by PhilippGrashoff** [comment]
Seems fixed by #291, can we close?

**Comment by PhilippGrashoff** [comment]
Tested, works fine now, closing.
