### ISSUE TITLE
WIP - Add lookup to Multiline

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#1560]
Add Lookup to Multiline control.

**Comment by mvorisek** [comment]
related with https://github.com/atk4/ui/issues/1375, ie. we must reuse existing Lookup component

**Comment by ibelar** [comment]
> related with #1375, ie. we must reuse existing Lookup component

Multiline already support 1:n record using hasMany relation. This issues is about adding atk-lookup vue component to it in order to support more control type with existing Line, Enum, Date etc.
