### ISSUE TITLE
ATK4 2.3 Crud ->editFields stopped working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1561]
Just upgraded from 2.2 to 2.3.1 -a Crud now shows all fields again, even though I had
```
 protected function init(): void
    {
        $this->editFields = ['name', 'complete','agent_id', 'due'];
        $this->displayFields = ['name', 'complete','agent_id', 'due'];
        
        parent::init();
    }
```

put in init. It shows all fields, no matter what I put above. Also updated to login.
Used to work in 2.2

**Comment by ibelar** [comment]
@mkrecek234 Unable to reproduce. Do you still have an issue with this?
