### ISSUE TITLE
ATK4 2.3.1 Cannot set onSubmit anymore

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1562]
I have the following addModalAction in a grid that used to properly work in 2.2. The modal works, but the ->onSubmit is not properly overwritten but the standard form onSubmit is executed. What has changed, that I can't overwrite it?
```
$messageviewvp = \atk4\ui\VirtualPage::addTo($grid->app);
$messageviewvp->set(function ($frame) use ($grid){
         
             $mvmodel = clone $grid->model;
             $mvmodel->load($frame->app->stickyGet('mid'));
             ...
             $mv = MessageForm::addTo($frame...]);
             $mv->setModel($mvmodel);
             // THE FOLLOWING ONSUBMIT IS NOT EXECUTED, BUT IGNORED in 2.3.1 !!! 
             $mv->onSubmit(function($form) use ($grid,$mv) {
                 $form->model->save();
                   
                 $modal_chain = new \atk4\ui\jQuery('.atk-modal');
                 $modal_chain->modal('hide');
                 
                 return [$modal_chain, // $form->owner->hide(),
                     new \atk4\ui\JsToast([
                         'title'   => 'Save Message',
                         'message' => 'Message is saved.',
                         'class'   => 'success',
                     ]),
                     new \atk4\ui\JsReload($grid),
                     
                 ];
             });
});
   
$messageviewmodal = new \atk4\ui\JsModal('Edit', $messageviewvp->getUrl('cut'), ['mid' => $grid->table->jsRow()->data('id')]);
```

**Comment by DarkSide666** [comment]
Probably something with URLs that in POST it doesn't reach this place in code anymore.

**Comment by PhilippGrashoff** [comment]
Hi @mkrecek234, do you use the ATK developer extension for google chrome? If not, please do, for cases like this it is extremely helpful as you can see exactly what gets sent to the server and what is returned.
In this particular case, I'd like to see what GET parameter is set when the form is submitted and if they match the HTML id of the <form> tag.

**Comment by ibelar** [comment]
@mkrecek234 - Try setup your virtual page triggerOnReload to false:

`$messageviewvp->cb->triggerOnReload = false;`

I think problem happens because when submitting the form, the virtual page callback trigger and terminate app execution before submit callback is reach. If you prevent virtual page callback from triggering when a reload occur, it should reach form submit callback.
