### ISSUE TITLE
agiletoolkit.org issues

### ISSUE THREAD

**Issue by Jmos** [atk4/ui#1563]
Hi folks! 

any body has a time to correct agiletoolkit.org links work again correctly forum login not working 
atk data namespaces doc also 404 mani links are broken
Has any admin time to correct it 
It is long time problem

**Comment by DarkSide666** [comment]
Currently agiletoolkit.org redirects to our github page because new agiltoolkit.org page (and forum) is in a works. Ping @romaninsh for more info :)

What you mean by agiletoolkit.org links?
What is atk data namespaces doc?
