### ISSUE TITLE
Generating Link in TableColumn using page property doesn't work properly

### ISSUE THREAD

**Issue by miciu10** [atk4/ui#1578]
If you use both page and args property of \Atk4\Ui\Table\Column\Link::class like this:
```
$link = $crud->addDecorator('path', [\Atk4\Ui\Table\Column\Link::class]);
$link->page = "redirect";
$link->args  = ['dok_id' => 'id'];
```
you'll get error: `ErrorException : Illegal string offset 'dok_id'`

My suggestion is to change:
https://github.com/atk4/ui/blob/81803a4a16602e4dfaff8da5347327484e6bda2f/src/Table/Column/Link.php#L151
line to:
```
$p = $this->page ? [$this->page] : [];
```

**Comment by mvorisek** [comment]
The suggestion is not correct, as there is https://github.com/atk4/ui/blob/81803a4a16602e4dfaff8da5347327484e6bda2f/src/Table/Column/Link.php#L110

In your example, the init is called in the 1st line (as long as `$crud` is initialized too), so in the 2nd line of your example you needs to use `$link->page = ["redirect"];`
