### ISSUE TITLE
Bad $cdn value for atkjs-ui bundle in release.

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#1589]
When a release is issued the $cdn value for atk js bundle should point to the release public repo instead of develop.

**Comment by romaninsh** [comment]
Which release is that? can you provide example?

**Comment by romaninsh** [comment]
Possibly related to this: https://github.com/atk4/ui/commit/5204a09456aca3adccbabe21c8ae669a2970edef#diff-5c7c0584c982f3ff6b0ab2e495f70b395328cf9374d88bddcf861a600f5430fbL20

**Comment by PhilippGrashoff** [comment]
Hi, I had this problem with release 2.3.1

**Comment by acicovic** [comment]
Hi guys. Is this resolved?

**Comment by PhilippGrashoff** [comment]
yep it is

**Comment by acicovic** [comment]
Closing this then.
