### ISSUE TITLE
Dropdown in multiline has 2x width

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1590]
demo: `demos/form/html-layout.php`

![image](https://user-images.githubusercontent.com/2228672/104824907-7d723300-5856-11eb-8b30-e1efa5d38fe3.png)

**Comment by ibelar** [comment]
This is correct behaviour from Semantic-ui vue - If you need a specific width you must specify it when defining the Model field.

Example:
```
$this->addField('age', [
    'values' => ['1' => 'From months to 2 years old', '2' => 'From 3 to 17 years old', '3' => '18 years or more'],
    'ui' => ['multiline' => [Multiline::TABLE_CELL => ['width' => 4]]]
]);
```

**Comment by mvorisek** [comment]
Why this is a correct behaviour?

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/135888252-7af6b4ab-d24c-4bf6-b754-7e2e470bf324.png)

**Comment by mvorisek** [comment]
FUI issue: https://github.com/fomantic/Fomantic-UI/issues/2133
