### ISSUE TITLE
Cascade Dropdown return bad results

### ISSUE THREAD

**Issue by ibelar** [atk4/ui#1597]
Look like model condition are not set properly when using cascade dropdown since https://github.com/atk4/ui/pull/1559

In https://ui.agiletoolkit.org/demos/form-control/dropdown-plus.php No product is shown when selecting Category and SubCategory

<img width="688" alt="Screen Shot 2021-01-21 at 10 43 43 AM" src="https://user-images.githubusercontent.com/2204478/105375402-ad169780-5bd6-11eb-9dbe-89f881072d0a.png">

**Comment by mvorisek** [comment]
@ibelar thanks for discovering it, @georgehristov I think this is another issue in dropdown cascade

**Comment by mvorisek** [comment]
@ibelar Are you sure this is really an issue and you did not selected a parent without any child item?

tested https://ui.agiletoolkit.org/demos/form-control/dropdown-plus.php with different input:

![image](https://user-images.githubusercontent.com/2228672/105628759-1567b200-5e3f-11eb-97bf-1c131a85df27.png)

> In https://ui.agiletoolkit.org/demos/_unit-test/lookup.php Sub category shoudl be filter by selected category but retrun all of them

was it ok before? - if so, please trace the issue, or @georgehristov might help, I did not developed this UI control

**Comment by ibelar** [comment]
@mvorisek - definitely a bug - In your picture Mustard should be under Spread sub category and not Gravie.

Look like it is coming from Atk4\Data from recent changes - Seems like the model reference is not set correctly and not related to the proper selection.

**Comment by ibelar** [comment]
Fix in #1599 

Lookup problem previously report was ok. - no fix needed there
