### ISSUE TITLE
Implement pull-down menus

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#161]
Although we do have some menu examples, what we need is ability to have pull-down menus. Preferably by using jsMenu() wrapper so that we can bind it to any button, icon or link:

 - click profile icon to see it drop-down
 - menu click on [...] icon to see more actions
 - ability to render once and attach to table row
 - integration with buttons
 - demo implementing trigger (e.g. unwatch/watch, select trough drop-down with PHP callback)

<img width="241" alt="screen shot 2017-05-11 at 11 35 38" src="https://cloud.githubusercontent.com/assets/453929/25945207/ff698ae6-363d-11e7-94d8-1dfc3ae1917d.png">

<img width="318" alt="screen shot 2017-05-11 at 11 37 28" src="https://cloud.githubusercontent.com/assets/453929/25945285/428a0828-363e-11e7-8975-87997c4c60bc.png">

See also:
 #24, #96 and #136

**Comment by mvorisek** [comment]
@ibelar is this PR still actual?

**Comment by mvorisek** [comment]
closing now, PR welcomed
