### ISSUE TITLE
Redirecting from user_action

### ISSUE THREAD

**Issue by elymatos** [atk4/ui#1627]
Hi!
how to do a redirect from a user_action (e.g. at CardDeck button). I'm trying
```
        $action = $images->addUserAction('report', [
            'callback' => function (ImageModel $image) {
                return $this->jsRedirect('Dashboard/Report/main/'. $image->get('idImage');
            },
        ]);
```
but it is not working...
Thanks!
Ely

**Comment by PhilippGrashoff** [comment]
Hi,

1) there is a nice ATK extension for Google Chrome. Using it you can easily check what is sent back to the browser. That would help debugging the problem.
https://github.com/atk4/atkjs-chrome

2) my first guess is: Only in App the function jsRedirect exists. Try $this->app->jsRedirect().

3) Do you need any processing on the server side or do you just want to forward the user to another URL? If so, the callback to the server is unneccessary and can be done JS only in the browser.

Best regards
Philipp

**Comment by ibelar** [comment]
You will not be able to execute javascript from a Model\UserAction callback. This is a job for Ui\UserAction executor via the `$executor->onHook(HOOK_AFTER_EXECUTE) ` callback.

If your action is set in CardDeck top bar, you can override `CardDeck::initActionExecutor()` to setup `HOOK_AFTER_EXECUTE `or override` CardDeck::jsExecute()` to setup your redirection for this specific action. 

If your action is set in a Card and display in CardDeck, you have to set the Ui\UserAction executor for your Model action using the Model\UserAction $ui['executor'] property in older version; or via ` ExecutorFactory::registerExecutor()` method in latest release.

**Comment by elymatos** [comment]
Thanks!
> If your action is set in a Card and display in CardDeck, you have to set the Ui\UserAction executor for your Model action using the Model\UserAction $ui['executor'] property in older version; or via ` ExecutorFactory::registerExecutor()` method in latest release.

I was able to register the action this way:

```
        $action = $images->addUserAction('report', [
            'callback' => function (ImageModel $image) {
                $this->redirect('/Dashboard/Main/main');
            },
        ]);
        $this->getExecutorFactory()->registerTrigger($this->getExecutorFactory()::CARD_BUTTON, [Button::class, null, 'blue', 'icon' => 'photo video'], $action);
        $deck = CardDeck::addTo($this,  ['noRecordScopeActions' => NULL,'singleScopeActions' => ['report']]);
```

My trouble now is that the redirected page is shown is "modal". It seems to be the default behavior for Card action (button), then the redirect is done, but the page opens in a modal :-(  I didn't find how to change this yet, but this is another issue, I think :-)

Thanks,
Ely

**Comment by elymatos** [comment]
The Chrome extension seems to be very useful! Thanks!

> 1. there is a nice ATK extension for Google Chrome. Using it you can easily check what is sent back to the browser. That would help debugging the problem.
>    https://github.com/atk4/atkjs-chrome

Ely

**Comment by ibelar** [comment]
Should be more like this I believe:

Define your Model action:
```
        $action = $images->addUserAction('report', [
            'callback' => function (ImageModel $image) {
                // Perform db operation for your image.
            },
        ]);
```

Setup Executor:
```
        $executor = new ModalExecutor();
        $executor->onHook(BasicExecutor::HOOK_AFTER_EXECUTE, function($x, $r, $id) {
            return $this->redirect('/Dashboard/Main/main');
        });
```

Then register this executor for the report action:
```
 $app->getExecutorFactory()->registerExecutor($action, $executor);
```

When register globally, Ui components like Card that need to execute the action will do so using the registered $executor.

**Comment by elymatos** [comment]
Thanks, ibelar, for help!
Actually I don't need any action for the model. The idea is very very simple: I want the card to have a button that redirect to another page (something like "/Dashboard/Image/report/<idImage>"). But I don't know how to create such "independent" action and to associate it to the card.
So, about your suggestion I don't know what action must go in "callback".
Thanks,
Ely

**Comment by ibelar** [comment]
Then simply add a button to an extended Card class:

```
class MyCard extends Card
{
    protected function init(): void
    {
        parent::init();

       $b =  $this->addButton(new \Atk4\Ui\Button(['Link']));
       $b->link('/Dashbord/Main/main');
    }
}
```

And use the card in CardDeck:
```
$deck = CardDeck::addTo($app, ['card' => [MyCard::class]]);
```
