### ISSUE TITLE
Dynamic load content in the same page

### ISSUE THREAD

**Issue by elymatos** [atk4/ui#1638]
Hi,
Suppose I have a page with a button and a div below it. When I click the button I want to make a callback and the content might be put inside the div (preserving the button on the page). I read and test VirtualPage, but the callback content is overwriting the whole page. How can I make a callback to fill just the div?
(BTW, I'm putting doubts here as issues but I'm not sure if it is the correct way to get help. If it exists another correct way, please let me know)
Thanks,
Ely

**Comment by PhilippGrashoff** [comment]
Hello elymatos,

do you know our discord channel? Thats the best place to ask for help: https://discord.gg/b6Jvuwhk

See you there :)

**Comment by elymatos** [comment]
Thanks!
