### ISSUE TITLE
File server location with FileUpload demos

### ISSUE THREAD

**Issue by nocelab** [atk4/ui#1639]
I'm runnig `demos/form-control/upload.php` in Docker image (atk4/ui-demo:develop) and I didn't find where uploaded file/image is located.
I've also tried in windows with xampp server with path set in `upload_tmp_dir='./tmp/'` in `php.ini` and I didn't find any files/images.
What i'm missing?

**Comment by mvorisek** [comment]
the developer must handle the upload by its own, to use managed impl., use atk4/filestore addon
