### ISSUE TITLE
Unneccessary line in Grid.php

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#1641]
Hi, in current develop code, there is an unneccessary line:
```
public function setIpp($ipp, $label = 'Items per page:')
    {
        if (is_array($ipp)) {
            $this->addItemsPerPageSelector($ipp, $label);

            $this->ipp = isset($_GET['ipp']) ? (int) $_GET['ipp'] : $ipp[0]; //This line is unneccessary
        } else {
            $this->ipp = $ipp;
        }
    }
```

The line with $_GET can be removed, as the very same code is run by `addItemsPerPageSelector()`.

**Comment by mvorisek** [comment]
send as a PR

**Comment by PhilippGrashoff** [comment]
will do, discovered it when packing for holiday where I am now :) DIdn't want it to get lost so only an issue for the time being.

**Comment by mvorisek** [comment]
Enjoy the stay, where are you and what are the covid restrictions there (bars, quarantine, testing, ...)?

**Comment by PhilippGrashoff** [comment]
Am in Italy, covid restrictions are ok there, feels pretty normal and no one is going crazy in either way. We needed to test at home before entering (but no one checked).

**Comment by mvorisek** [comment]
@PhilippGrashoff ping

**Comment by mvorisek** [comment]
> The line with $_GET can be removed, as the very same code is run by `addItemsPerPageSelector()`.

thanks for the description, fixed in https://github.com/atk4/ui/pull/1665/commits/7c29e8fe9b13c4b55d50cff44b578713420153b1
