### ISSUE TITLE
Workaround for atk4 <2.4 JSON Error null returned

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#1644]
If you are using many fields in a model / form, in older versions of atk4 it could be that you are running in a JSON memory issue.
The error says:
`TypeError: Return value of atk4\ui\App::encodeJson() must be of the type string, null returned`

As a workaround you have to either update to at least atk4 2.4 or replace the preg_replace in \atk4\ui\App.php in line ca. 960.
I have to stick for now on atk4 2.2, so I had to apply this...

You have to replace 2 lines there with the following code:
```
$json = preg_replace_callback('~"(?:[^"\\\\]+|\\\\.)*+"\K|\'(?:[^\'\\\\]+|\\\\.)*+\'\K'
            . '|(?:^|[{\[,:])[ \n\r\t]*\K-?[1-9]\d{15,}(?=[ \n\r\t]*(?:$|[}\],:]))~s', function ($matches) {
```

Thanks to @mkrecek234 and @mvorisek who pointed me to this solution / workaround...

**Comment by mvorisek** [comment]
closing as fixed in v2.4+, lower versions are no longer maintained
