### ISSUE TITLE
DropdownCascade not showing saved value in 3.0

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1685]
I have the following setup:
1. Model CarMake (car manufacturer), which hasMany CarModel
2. A View for another model Ticket which hasOne CarMake and hasOne CarModel with a form including these controls:
```
$makeid = $gr->addControl('make_id');
$modelid = $gr->addControl('model_id', [\Atk4\Ui\Form\Control\DropdownCascade::class, 'cascadeFrom' => 'make_id', 'reference' => 'CarModels'], ['type' => 'integer']); 
```
The DropdownCascade work fine if you want to assign new values, HOWEVER: if you edit an existing ticket record, only the make_id dropdown is rendered correctly showing the saved value. The model_id DropdownCascade does NOT show the saved entry.

This used to work before in 2.2, but broke with migrating to 3.0.

**Comment by mvorisek** [comment]
Closing as not enough info and in demos this is working.

See https://github.com/atk4/ui/pull/1667 , typecasting was not always called in 3.x.

**Comment by mkrecek234** [comment]
Will check - however the demo does not cover the use case here. It just does not save anything to persistence present in a DropdownCascade. I will modify the demo to test. And demo in 3.0 release is not working...

**Comment by mkrecek234** [comment]
@mvorisek This issue is confirmed to be still present in the latest atk4/ui 3.0 release. It only seems to be fixed in the dev-develop branch, but no release yet available without this bug. Check this test setup: 
https://github.com/mkrecek234/atk4-test

In the script Test with records, the DropdownCascade field is empty if you use the 3.0 release of atk4/ui. If you switch to develop branch, it is pre-filled correctly. @mvorisek Please re-open the issue as it is confirmed to be present. Only if it is fixed in a new release, an issue is closed, isn't?
