### ISSUE TITLE
JsExpression - allow to define placeholder for args

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#1688]
Currently, the placeholder for arguments in JsExpressions is `[]` or `[varname]`. When working with more complex javascript, this can lead to problems, for example with for loops:
```
for (var i = 0; i < something; i++) {
    var somevar = somearray[i];
    ....
}
```
In this case, `[i]` is treated as placeholder for an argument by JsExpression - this leads to an exception that no argument is found for that placeholder.

Two solutions I can think of:
1) Change the brackets to something that will not appear in JS code, e.g. `[[varname]]` or `{{varname}}`. The problem here is backwards compatibility.
2) Make the brackets definable per JsExpression instance, e.g. by adding 2 properties like 
```
protected $openingBracket = '[';
protected $closingBracket = ']';
```

Best regards

**Comment by mvorisek** [comment]
thankfully atk4 throws, `openingBracket` seems too hacky to me

`[[varname]]` or `{{varname}}` might be a solution but how often do you need it? is there currently any escaping possible, eg. solution /wo syntax change?

`[]` / `{}` is also what is used in DSQL

**Comment by mvorisek** [comment]
what if we do not replace if the `[` is preceded with alphanum?

a) does it fixes all JS issues/syntax?
b) is there a case, where a replacement makes sense after an alphanum? (`somearray'value'` is an example where it never does, but seems problematic with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#array_literals)

**Comment by PhilippGrashoff** [comment]
> what if we do not replace if the `[` is preceded with alphanum?

this could be a sensible solution, though also not fully BC. I still think that using brackets as placeholders that can not appear in normal JS code would be the way to go, at least make in configurable. @ibelar, you wrote most JS in ATK, WDYT?

To answer your question about escaping: In my current case, I include the js code for the expression from an external file.
The JS code is about a 100 lines long containing several functions. In this case, escaping brackets would mess up syntax check of the IDE etc. So even if escaping was possible, It would be pretty hacky.

**Comment by mvorisek** [comment]
You can always insert the code unescaped:
```
new JsExpression('[]', [file_get_contents('never_escaped.js')])
```

UPDATE: see my post below for correction

**Comment by PhilippGrashoff** [comment]
Hi,

that does not work, as it is then treated as a string and escaped with `"`. Can you please reopen this issue and in general not close them so quickly?

Thanks & regards

**Comment by mvorisek** [comment]
You are right, you need `{}` ;-)

About closing, you can not reopen as the autohor of this issue?

**Comment by PhilippGrashoff** [comment]
Hi,

for some reason I still have limited rights to all the ATK repos and cannt repoen this issue...

**Comment by mvorisek** [comment]
let me know if `{}` is not a solution and I will reopen

**Comment by PhilippGrashoff** [comment]
Hi, `{}` actually works - didn't see the difference when reading the code. Still, this does not solve the situation when you want to use JS code like `someArray[someIndex]` AND also want to replace some placeholders from PHP code.

**Comment by mvorisek** [comment]
then you need to use custom replace function ;-), this is the only 100% safe solution

**Comment by PhilippGrashoff** [comment]
Well, thats what I did already of course, extend JsExpression and change the placeholders to `{{}}`. This way, I can use placeholders and stuff like `somearray[someindex]` in the JS code.

But of course every alteration of the Framework needs to be maintained, and I still think there should be a proper way in JsExpressions to use brackets and placeholders at the same time in JS code. My favorite would still be to customize the placeholders by 2 simple properties.

**Comment by mvorisek** [comment]
I think you have too much edge case.

Either binary/unreplaceable input should be allowed or the standard brackets should apply.

You can however extend the class and replace the `jsRender` for the usecase you need. If you usecase does not change, you do not need to maintain it :)
