### ISSUE TITLE
Change {tag} to {{tag}}? 

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#17]
Our templates are similar to Moustache, but we use single bracket format `{foo}`. At this point we can refactor to use `{{foo}}`, but only for the tags.

**Comment by romaninsh** [comment]
Other template engines use it. I wanted to have a poll anyways, will keep it open to see if there are any other opinions.

**Comment by burisk** [comment]
In my opinion, `{{ .. }}` is better, because that's not valid JSON format. While `{ .. }` can be and what about when someone want to write Json format to output? I think that there must be useless and unnecessary escape characters..

**Comment by romaninsh** [comment]
Good feedback. Technically JSON is a data and it must not be in the body of the template, that alone indicates a big problem with escaping. I am taking what you said onboard, thanks for sharing, see on the other issues.

**Comment by DarkSide666** [comment]
@burisk has a point about JSON, but still I don't see real advantage of `{{...}}` instead of `{...}`.
