### ISSUE TITLE
Sorting by non-persist fields

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#172]
Some fields are 'never_persist' and yet if you click on the header Grid attempts to sort by that column. This generates ugly error.

**Comment by romaninsh** [comment]
Maybe we need to address this on Agile Data level too?

**Comment by DarkSide666** [comment]
I think it's a task for Agile Data.

**Comment by romaninsh** [comment]
Ideally we don't want those headers clickable at all.

**Comment by mvorisek** [comment]
needs demo/repro code, let's close it for now
