### ISSUE TITLE
Card demo is broken

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1723]
steps to reproduce:

1. open `/demos/data-action/factory-view.php`
2. click
  ![image](https://user-images.githubusercontent.com/2228672/147833889-5b81dcc8-2822-4c4c-9740-9698f39e1760.png)
3. the following is shown:
  ![image](https://user-images.githubusercontent.com/2228672/197336081-ab489fd7-cd47-4c90-be39-c8cf0ade4070.png)

**Comment by DarkSide666** [comment]
Also
* `demos/interactive/tabs.php' Dynamic form tab give Atk4\Data\Exception: Expected entity, but instance is a model

**Comment by mvorisek** [comment]
`demos/interactive/tabs.php` is fixed, the original issue is however still present

**Comment by mvorisek** [comment]
the problem is modal window is rendered & opened and then the inner modal content is loaded using AJAX, when it fails, an error modal is shown and then user can recover/return from it

> 5. sometimes (seems some race condition) blank modal is kept open

the race condition is probably fixed already

**Comment by mvorisek** [comment]
there are 3 problematic places - regex `jsShow.*load`:

![image](https://user-images.githubusercontent.com/2228672/197349542-d1ae5cdd-03fe-4b8a-beec-5c65270bcf70.png)
