### ISSUE TITLE
Lookup "plus" feature throws error

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1731]
This line causes an error when you choose to have the Lookup with Lookup::plus = true:

https://github.com/atk4/ui/blob/3cb026a3649efc1841d5d73a7608145da6212971/src/Form/Control/Lookup.php#L257

Error is "Atk4\Data\Exception: Expected model, but instance is an entity".

**Comment by mvorisek** [comment]
https://github.com/atk4/data/blob/e82eebff5b7ab51d2e5d2b0f967d01eb9c045e6e/src/Model.php#L683 onlyFields can be set on model only

but if we set it, it keep the Model state mutates, so we should:
a) clone preferably before
b) OR do not set onlyFields at all
c) impl. virtual wrapping model, eg. wrap the underlaying model by another, on which we can set the custom state safely

**Comment by mkrecek234** [comment]
@mvorisek Can we implement a) quickly to get it working again. I think that is the easy and quick fix

**Comment by mvorisek** [comment]
please test:

`$form->setModel((clone $entity->getModel())->setOnlyFields($this->plus['fields'] ?? []));`

**Comment by mkrecek234** [comment]
Proposal is not working. This works as intended:
```
$form = \Atk4\Ui\Form::addTo($page);
$entity = (clone $this->model)->setOnlyFields($this->plus['fields'] ?? null)->createEntity();
$form->setModel($entity);
```

You have to createEntity on model with setOnlyFields, otherwise $form->setModel() does not pass an entity. Please note also the null instead of [], otherwise empty form is shown.

P.S. Just wonder why setOnlyFields could not also accept to be applied to an entity, and not just a model. Then it would be a bit easier.

**Comment by mvorisek** [comment]
> ```
> $form = \Atk4\Ui\Form::addTo($page);
> $entity = (clone $this->model)->setOnlyFields($this->plus['fields'] ?? null)->createEntity();
> $form->setModel($entity);
> ```

LGTM, please send a PR

> P.S. Just wonder why setOnlyFields could not also accept to be applied to an entity, and not just a model. Then it would be a bit easier.

Entity should represent just a data holder, thus it should not affect the DB query, onlyField is a small exception, but I prefer to stay with one strong & simple design line.
