### ISSUE TITLE
Cruds in multiple-layered modals behave strange

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1732]
- Have a master Crud, and add Modal to open a child model crud. (1)
- You open the Child Model Crud in a Modal -there you add entries
- Works fine.
- Then select another master crud's entry (2) where you open the respective child Crud in the modal
- If you then click add, you see the previous, already filled-in form (1's child entry)
- If you close the modal manually, you see an empty (correct) add form - if you enter new entries there, it won't close the modal, but it still saves its content. If you manually close it you see the correct Crud entry.

Seems a logic error on cascaded cruds/modals.
See video here:

https://user-images.githubusercontent.com/28671486/152869240-ac988f31-39b6-41be-9642-6ab6740828c9.mov

**Comment by mvorisek** [comment]
@mkrecek234 can you please post here a simple code to reproduce, eg. two simple model classes & how you use them to create the Cruds?

You desc is clear, but these simple repro script helps the people that develop the fixes a) to be faster, b) to be sure that when they get onto the issue, it will be reprodudible (or it is already fixed).

**Comment by mvorisek** [comment]
linking here another Modal related issue - https://github.com/atk4/ui/issues/1699

**Comment by mkrecek234** [comment]
@mvorisek Here is the sample code for the above video:
```
$crud = \Atk4\Ui\Crud::addTo($app);
$crud->setModel($model = new Model\Customerpayment($app->db));

$crud->addModalAction(['icon'=>'flag'], ['title' => 'Edit invoice footer texts'], function ($v, $id) use ($crud, $model) {
    $entity = (clone $model)->load($id);
    
    \Atk4\Ui\Crud::addTo($v)->setModel($entity->ref('customerpaymenttext'));
    unset($entity);
    
});
```
where Customerpamenttext is a 1:n (hasMany) model to Customerpayment model:
```
class Customerpayment extends \Atk4\Data\Model {
    public $table = 'customer_payment';
    
    protected function init(): void
    {
        parent::init();
        
        $this->addFields([ 'name']);
        $this->hasMany('customerpaymenttext', ['model' => [CustomerpaymentText::class]]);
    }
}

class CustomerpaymentText extends \Atk4\Data\Model {
    public $table = 'customer_payment_text';
    
    protected function init(): void
    {
        parent::init();
        
        $this->hasOne('customer_payment_id', ['model' => [Customerpayment::class]]);
        $this->hasOne('language_id', ['model' => [Language::class]])->addTitle();
        
        $this->addFields([
            'name',
            'footer' => ['type' => 'text']
            ]);
         }
}
```

**Comment by mkrecek234** [comment]
@ibelar Any idea how to fix this critical and major bug? Really limiting factor to make use of modals unfortunately.

Seems also that loading a Virtual Page as Modal from another Modal shows exactly the same issue as above - so not necessarily linked to Crud only, but loading a Modal from a Modal (and closing it, reopening another dynamically loaded Modal).

**Comment by mvorisek** [comment]
> loading a Virtual Page as Modal from another Modal shows exactly the same issue as above

that should be simpler to debug, please post a minimalistic code and exact steps to reproduce

**Comment by mkrecek234** [comment]
Hard to reproduce, in some instanced I could make it happen that also a modal was empty. In sample code of PR #1764 one of the modals causes a memory leakage.
Anyone an idea? The above video of myself was coded a bit differently: I defined custom Crud classes, and inside CustomCrud->setModel() I typically added then the VirtualPages. This causes the effect in my first video "doubling" the modals after some time, or showing old ones which should have been closed.

Here is the memory leakage video - you can also see I have to close the non-loading modal twice to go back which resembles the error in my first video.  - https://github.com/atk4/ui/pull/1764#issuecomment-1092682713

**Comment by mkrecek234** [comment]
Highly strange - If I add another static modal inside the addModalAction right after $modalvp3 = ... using `$inactivemodal = \Atk4\Ui\Modal::addTo($v);`, the memory leakage disappears.  

And the doubling of the modals, happens after I have opened twice the modals and closed with different records. If I then open the second lay modal a third time, the HTML code shows that two new modals are added when opening it, instead of one:

![image](https://user-images.githubusercontent.com/28671486/162421671-04c9d54a-896d-4c15-9f7a-8222f64b1e90.png)

**Comment by mvorisek** [comment]
I confirm the initial submited issue and simplified the repro code to https://github.com/atk4/ui/blob/3fd832f729ad230dd918958c9fac09181266095f/demos/_unit-test/crud_gh1732.php using already present demo models
