### ISSUE TITLE
Wrong CDN selected in 3.1 release?

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1734]
Please check 
https://github.com/atk4/ui/blob/82a056cf252308b8286f90b86261e8b130fb3b4e/src/App.php#L46

we are using the githack link still in the 3.1 releases.
Shouldn't this be

https://cdn.jsdelivr.net/gh/atk4/ui@3.1/public/atkjs-ui.min.js

then?

**Comment by mvorisek** [comment]
https://raw.githack.com/ is CDN backed, do you have any measureable evidence the backend uptime is problematic?

jsdelivr.net were having issues in the past too, so we switched from it.

cdnjs.cloudflare.com is optimal, can you try to include our repo there?

**Comment by mvorisek** [comment]
related with https://github.com/atk4/ui/issues/1025 , no external/internet dependency is probably the best

**Comment by mvorisek** [comment]
The https://raw.githack.com/ service promises to cache the release resources for a year, I do not belive there is any issue with such resources excl. CloudFlare outages itself which are very rare.

I am in favor of closing this issue.

**Comment by mkrecek234** [comment]
@mvorisek I'm fine either way and don't have nor an opinion nor results. This relates to @PhilippGrashoff message in discord saying we moved to another service. Indeed I also would fancy #1025  - a lot of mission-critical business applications have to run also without internet connection.
