### ISSUE TITLE
develop version of ATK JS/CSS is used in releases

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#1735]
See for example 3.1: https://github.com/atk4/ui/blob/release/3.1/src/App.php#L46

The 3.1 version should be used, not the develop version. 
Using the develop version could make our applications fail at any time when develop versions are changed.

**Comment by mvorisek** [comment]
closing, you posted a link to a release branch, instead of the actual release

https://github.com/atk4/ui/blob/3.1.0/src/App.php#L46 LGTM
