### ISSUE TITLE
Workaround popup blockers

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#174]
Currently if actions (such as form submission) result in error, they will be displayed in a pop-up. We can't really do otherwise because those will typically contain full HTML document. 

Unfortunately popups in response to AJAX request are considered unwanted by browser and will be blocked. ATK js will display alert instead with unusable HTML. It should instead offer user to open a popup with the error and suggest how to disable blocker.

**Comment by acicovic** [comment]
As errors are now shown in modals, I don't think this issue is still relevant so it could probably be closed.

**Comment by DarkSide666** [comment]
I would say - close it, but Romans wanted to close issues himself during weekly hangout so adding label.
