### ISSUE TITLE
Consider native datepickers

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#175]
Perhaps using native date-pickers is a good option, would need to consider.

```
<form>
  <input type="date">
</form>
...
<script>
  var i = document.createElement("input");
  i.setAttribute("type", "date");
  if (i.type == "text") {
    // No native date picker support :(
    // Use Dojo/jQueryUI/YUI/Closure to create one,
    // then dynamically replace that <input> element.
  }
</script>
```

**Comment by DarkSide666** [comment]
Maybe. I have to admit that I have never used them, but hopefully more and more browsers will support that.

**Comment by acicovic** [comment]
I think that the Fomantic DatePickers that we have now are perfect. Native DatePickers may still be a bit of a mess and I think I recall @PhilippGrashoff saying how difficult they were to work with Javascript. Unfortunately, native DatePickers will always be subject to browser implementation which might differ.

Maybe close the issue?

**Comment by PhilippGrashoff** [comment]
actually, they were only difficult regarding onChange...

**Comment by PhilippGrashoff** [comment]
but nevertheless, the calendar Fomantic UI provides is really great!

**Comment by DarkSide666** [comment]
Yeah I also think that there is no need to mess with native datepickers while we use Fomantic :)
Let's just close this one.
Maybe someday there will be a miracle and all browsers will support all features equally well... :D then we can reopen this ticket.
