### ISSUE TITLE
Placement of table column filter dropdowns

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#1751]
Currently looks like this:
![image](https://user-images.githubusercontent.com/1969119/156902148-d0db6d44-ef44-4254-b647-6aed1bb55c88.png)

By disabling/dropping these 2 CSS rules I managed to move dropdown icon to be correctly vertical aligned in center.
```
.atk-table-dropdown {margin-top: -8px}
.atk-table-dropdown i {vertical-align: bottom}
```
![image](https://user-images.githubusercontent.com/1969119/156902245-d0b4c592-3f57-4541-86ea-2d2adedb47f4.png)

But I'm not sure - maybe changing these styles can break style somewhere else.
Any idea why these two CSS rules was added?

**Comment by mvorisek** [comment]
I tested dropping the custom rules also for long header and it works well:

![image](https://user-images.githubusercontent.com/2228672/156902500-31cdf7f8-e25a-47bf-97ba-d46f76fcb676.png)

**Comment by DarkSide666** [comment]
@mvorisek should I make small PR for this?

**Comment by mvorisek** [comment]
yes, make sure you edit both less & css (CI will warn otherwise)
