### ISSUE TITLE
Customizable formatting in UI persistence

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1760]
Idea:
- Not always is the Atk4/Data field content identical to its representation that we want to have.
- Example: you store a float value 8378583.783745 in the database - in tables or other UI elements, like text or messages, you want to define the format. E.g., 8,378,583.78 or 8378584.
- Solution: Approach to be able to add a UI characteristic to a model-specific field that defines the format.

Which fields types?
float, integer, date, datetime, time, boolean.

Challenge:
If you *edit* that field, you sure don't want it to be displayed in the format.

Suggestion:
I would fancy to at least be able to define it in the model init function, as to be passed on to UI. Otherwise it is double-work in your view elements. Such as `$this->addField('amount' => ['type' => 'integer', 'ui' => ['format' => ['decimals' => 1, 'thousand_separator' => ',', 'prefix' => 'Hello', 'suffix' => ' kilograms']]);`

related to https://github.com/atk4/ui/issues/1126 and https://github.com/atk4/data/issues/577

**Comment by mvorisek** [comment]
implemented in #1981
