### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by mhuser** [atk4/ui#1787]
As for yesterday and tried again today, seems the [demo site](https://ui.agiletoolkit.org/) is down.

**Comment by mhuser** [comment]
![image](https://user-images.githubusercontent.com/8080934/167402652-bfdb064c-2065-4f76-9a20-4b9d14d1c9e1.png)

**Comment by DarkSide666** [comment]
I guess it's because of that certificate issue :(
Trying to reach @romaninsh

**Comment by mhuser** [comment]
Great !
