### ISSUE TITLE
Add documentation for 'Table Totals'

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#180]
Document change in #178 

 - also need to add grandTotal strategy, where Table would perform the query.

``` php
$t->addTotals(); // todo - must specify strategy.
```

Also need to create hooks for outputting columns before and after the main body of the table, where we can.

Need the ability to create groups in a table with headers and footers (such as sub-totals).

**Comment by romaninsh** [comment]
see also #286

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/ui/pull/286
