### ISSUE TITLE
UI persistence currency_decimals not working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1802]
The UI decimals by default is 2: If you have a stored field with 4 digits, however, UI does not round to 2 digits but shows 4. How can you show 2, but store 4?

**Comment by mvorisek** [comment]
This is intended design and a trade of between UX and the real data.

`atk4_money` type rounds to 4 decimal digits - https://github.com/atk4/data/blob/e091b675d32a17d839e918557f3e24ab6211b563/bootstrap-types.php#L33

The `currency_decimals` represents a min. digits to be displayed, see https://github.com/atk4/ui/blob/dbfcc4e1cc2fd5656b1efddd8327fd61cfe3c6c0/tests/PersistenceUiTest.php#L70

So if you want your data to be rounded, you need to round them :)

This feature allows you on the other hand to do "precise" calculations with money values, so the intermediate values are "not so much" (4 digits for `atk4_money` type) rounded.

For cheap products/small quantities, rounding to only 2 decimal digits would be not desired.

UI persistence is not responsible to "cripple" any data, it must display the data with full significance. Otheriwse others will post here issues, that the UI persistence rounds data :D and it is also much harder to debug.

So I add a "won't fix" label. If you think there is really something wrong, please provide an usecase/reasoning and propose a solution.

**Comment by mvorisek** [comment]
If you need to round some calculated data like total price, you can add an expressional field to your model:
```
        $this->addExpression($this->fieldName()->calc_price_line_rounded, [
            'expr' => 'ROUND([' . $this->fieldName()->price_unit . '] * [' . $this->fieldName()->amount . '], 2)',
            'type' => 'float', 'ui' => ['visible' => false],
        ]);
```
