### ISSUE TITLE
CardDeck default UserAction not working 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1844]
Steps to reproduce:
- add default CardDeck to any view
- set any model to CardDeck
- Press default UserAction 'Add' and enter entity

Error:
- Expected entity, but instance is a model
https://github.com/atk4/ui/blob/a8a08cfed516c5ffc1e7e0c54db8ab3e8122b0c4/src/CardDeck.php#L262

and here

https://github.com/atk4/ui/blob/a8a08cfed516c5ffc1e7e0c54db8ab3e8122b0c4/src/CardDeck.php#L296

Replacing $action->getModel() by $action->getEntity() also won't fix it...

**Comment by mvorisek** [comment]
Yes, `$action->getModel()->isLoaded()` is definitely wrong.

In the past I put a lot of efford into https://github.com/atk4/data/pull/932 but there are some issues & limitations with phpstan itself although I filed and fixed many bugs there... Before releasing v4.0, it would be great if I can manage to run such static analysis at least one locally.

**Comment by mvorisek** [comment]
Is there any demo in demos/? Or can any existing demo be adjusted with one, two lines to reproduce there?

**Comment by mkrecek234** [comment]
See https://github.com/atk4/ui/tree/bug/card_deck_add_action
However since save is deactivated in demo, error not triggered.
