### ISSUE TITLE
ScopeBuilder with hasOne reference not working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1853]
Steps to reproduce:

1. Define two models with MySQL persistence, e.g. customer and agent, where contract has a hasOne reference to agent.
2. The hasOne reference needs to be set like this: `$this->hasOne('agent_id', ['model' => [Agent::class], 'required' => true])->addTitle()`;
2. Create a view with a form `$form` and add a ScopeBuilder to it.

When rendering, I receive this error:
![image](https://user-images.githubusercontent.com/28671486/188459551-2b892429-1f9d-4d01-93dc-2aad6a73395b.png)

If you set the hasOne reference like this:
`$this->hasOne('agent_id', ['model' => [Agent::class], 'theirField' => 'id', 'required' => true])->addTitle();`
the exception won't be triggered. I think atk4/data should make sure to continue to automatically assume theirField to be `id` if it is not set.

Inside getLookupProps when calling getFieldItems and then `$items[$item->get($field->getReference()->getTheirFieldName())] = ...` , the $this->model is an array and not a model object, so inside `getTheirFieldName` this call runs an exception: `Model::assertInstanceOf($this->model)` .

https://github.com/atk4/ui/blob/32e2742bd6f7787ffc40a2c8c6dd98312360371a/src/Form/Control/ScopeBuilder.php#L478

Here is the content of $this->model:
![image](https://user-images.githubusercontent.com/28671486/188460353-de013e10-e38b-4292-b9b2-4a037187c0c4.png)

**Comment by mvorisek** [comment]
> Inside getLookupProps when calling getFieldItems and then `$items[$item->get($field->getReference()->getTheirFieldName())] = ...` , the $this->model is an array and not a model object, so inside `getTheirFieldName` this call runs an exception: `Model::assertInstanceOf($this->model)` .

This is known/expected atk4/data limitation. We do not have to allow to create model from array here, as it might have negative performance implications if the `getTheirFieldName` getter is called often.

An already created model needs to be passed. I will check if we can do this easily.
