### ISSUE TITLE
Grid/Crud addModalAction and addAction button not working anymore

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1857]
Steps to reproduce:
1. You have an extended Crud class where you add `$this->addActionButton(['icon'=>'star'], function ($v, $id) use ($grid, $model) { return 'Hello world';  });`inside the Crud->setModel function (and after parent::setModel()).
2. You add the Crud to a normal app. When rendered, button is there, but a click won't do anything.

Interesting:
In other scripts where I do not run addActionButton inside the setModel, but like this, it works:
```
$crud = \Atk4\Ui\Crud::addTo($app)
$crud->setModel(...);
$crud->addActionButton(...).
```

Must have been introduced recently.

**Comment by mvorisek** [comment]
@mkrecek234 when you describe code in steps to reproduce, please also add the code to your description. I can then copy it simply, be sure the issue is really present and test/debug/fix it.

**Comment by mkrecek234** [comment]
@mvorisek Here are code snippets for better understanding
```
namespace Atk4\Erp;
class TicketCrud extends \Atk4\Ui\Crud
{
    protected function init(): void
    {
        parent::init();      
    }
    
    public function setModel(Model $model, $fields = null): void
    {   $filteredmodel = (clone $model);
    
        parent::setModel($filteredmodel, []);
                   
        $this->addModalAction(['icon'=>'business time'], ['title' => 'Quick Delegation & Re-scheduling', 'class' => ['tiny']], function ($v, $id) use ($grid, $model) {
            return 'Test';
        });
        
        $this->addActionButton(['icon'=>'star'], function ($v, $id) use ($grid, $model) {
            return 'Test'; 
        });
    }
}
```

The class then is used in this app script:
```
$model = new \Atk4\Erp\Model\Ticket($app->db);
	
$grid = $app->add([\Atk4\Erp\TicketCrud::class]);
$grid->setModel($model);
```

**Comment by mkrecek234** [comment]
Strangely, the addAction buttons do work in this script:
```
$crud = \Atk4\Ui\Crud::addTo($app);
$crud->setModel($model = new Model\CustomerPaymentTerms($app->db));

$crud->addModalAction(['icon'=>'flag'], ['title' => 'Edit invoice footer texts'], function ($v, $id) use ($crud, $model) {
    $entity = (clone $model)->load($id);
    \Atk4\Ui\Crud::addTo($v)->setModel($entity->ref('customer_payment_terms_text'));
});

**Comment by mvorisek** [comment]
@mkrecek234 please see https://github.com/atk4/ui/commit/996fa310de5a5dcf19d6465bbb469f8f49b8e5f5 - please checkout the repro branch and reproduce the problem on `demos/collection/crud.php`.

I copied the code your posted in https://github.com/atk4/ui/issues/1857#issuecomment-1241916619 and the buttons:

![image](https://user-images.githubusercontent.com/2228672/189439228-9cffc003-2dad-4e2d-bbb3-06709c8f0d67.png)

work on my side.

**Comment by mkrecek234** [comment]
Issue identified and detailed in issue #1858 
Thus, closing this issue as it is a bug in the onRowClick implementation, and not a addAction issue per se.

**Comment by mvorisek** [comment]
ok, deleting `repro_1857` branch
