### ISSUE TITLE
Custom modal form executor

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1861]
from chat:

Still my custom modal executor stuff - I am convinced this would make UserActions more valuable to everyone. So far I cannot see that we have what we need. So may be I explain again if I may:
- In a Model::init function you can add a UserAction that will open a Modal (this exists today). BUT: 
a) The form is NOT automatically rendered to collect the "Args" fields defined in the UserAction BUT it simply shows a defined form that you pass to the addUserAction / or a custom executor where then with few lines of code you defined which form to be show.
b) Naturally the form has to return for sure the Args arguments and the fields content, so that the UserAction's callback can then handle the inputs and perform the data modification: 
So, conceptually something like:

```
$country->addUserAction('edit_argument', [
    'caption' => 'Argument',
    'description' => 'Ask for argument "Age" prior to execute the action.',
    'args' => [
        'age' => ['type' => 'integer', 'required' => true],
    ],
    'executor' => [new CustomModalExecutor(['form' => CountryEditAgeForm::class, 'modal' => ['class' => 'tiny']])],
    'callback' => function (Country $model, int $age) {
        if ($age < 18) {
            $text = 'Sorry not old enough to visit ' . $model->getTitle();
        } else {
            $text = $age . ' is old enough to visit ' . $model->getTitle();
        }

        return $text;
    },
]);
```
(copied from https://github.com/atk4/ui/blob/ebbd3b952b44669d7793fa45e8995783ea17134c/demos/_includes/DemoActionsUtil.php#L42-L57, only 'executor' key/seed added)
 
(Please don't take the code literally, just conceptually. I want to achieve to have a very simple way to design complex forms being shown for argument collection in UserActions. That is all. And it would be HIGHLY powerful. - You started on this but did not yet finish the part to pass a free form finally. May be we can finish this off still)

**Comment by mvorisek** [comment]
Before implementing this feature, https://github.com/atk4/ui/issues/1856 should be fixed.

**Comment by mvorisek** [comment]
'executor' key/seed is problematic from OOP design as discussed in https://github.com/atk4/ui/issues/1849#issuecomment-1234837309 - but we can probably use `ui.executor` key instead, this is minor.

@mkrecek234 why do you want executor to be declared directly instead of defined thru `Atk4\Ui\UserAction\ExecutorFactory`?

What base class does `CustomModalExecutor` extend?

`CountryEditAgeForm` the same question for this class too, if this class with extend the regular `Atk4\Ui\Form` /wo any other modification, will it work exactly the same like any current executor?

**Comment by mkrecek234** [comment]
@mvorisek 

> @mkrecek234 why do you want executor to be declared directly instead of defined thru `Atk4\Ui\UserAction\ExecutorFactory`?
> What base class does `CustomModalExecutor` extend?

My key goal is that when adding a UserAction to a model we should be able to very easily pass also the custom-defined form to collect the arguments required. Alternatively even the view (including the form) to collect the arguments. Currently I understand changing the ExecutorFactory is not a one-liner in code which it should be. At least for my code 90% of atk4/data actions involve to simply collect arguments from mostly a modal. So what class to extend you can decide best.
 
> 
> `CountryEditAgeForm` the same question for this class too, if this class with extend the regular `Atk4\Ui\Form` /wo any other modification, will it work exactly the same like any current executor?

I would say so, yes, if it is standard it is like a standard form where all fields are set in setModel, so all controls/fields are automatically populated in the form. Only if we change the Form->setModel, then we can have custom-designed form with  decorations, some JS refinement or any other stuff which make the form more user-friendly than just the standard generated argument collection form.

**Comment by mvorisek** [comment]
Currently when there are no args/fields/preview `ExecutorFactory::STEP_EXECUTOR` is used which implied ModalExecutor. Otherwise JsExecutor is used.

> Currently I understand changing the ExecutorFactory is not a one-liner in code which it should be. 

There is https://github.com/atk4/ui/blob/01d39d24694e4b4f63a576d090e55e0e97aaa9e4/src/UserAction/ExecutorFactory.php#L168 I agree, the method `ExecutorFactory::getModelId` is horribly named, but this method can be used to register a custom executor for a specific UA instance (as unique per model instance).

@mkrecek234 is this what you are looking for?

**Comment by mvorisek** [comment]
(copied from Discord chat)

I would split your CustomModalFormExecutor into 4 points:
- custom form class - solved by `ModalExecutor::$formSeed` seed, custom class (extending Form) can be defined
- custom executor class - `ExecutorFactory::registerExecutor()` and `ExecutorFactory::registerTypeExecutor()` methods can be used to define custom executor seed (for custom Form - 1st point, or even a custom executor class)
- custom executor buttons - in my example, I have shown how to customize them via custom executor class, I agree the code heavily relies on the current impl., if you have any idea how to allow easy seeding of buttons, please comment on https://github.com/atk4/ui/issues/1861
- executor/form seed in atk4/data/Model\UserAction via ui property - given we have executor registry, what usecase will it solve?

---

please see https://github.com/atk4/ui/compare/custom_modal_form_executor

it allows you to define executor via a Model\UserAction::$ui['executor']

during the development, I found several issues:
1. `Model::addUserAction` does accepts "defaults" ("seed" /wo class), thus UA class cannot be defined, this should be probably fixed in atk4/data (fixed in https://github.com/atk4/data/pull/1070)
2. having `Model::addUserAction::$ui` property with possibility to define executor class/seed is problematic from design perspective, as ui ExecutorFactory can override the executor as well, for example if custom ModalExecutor class is set, but globally PanelExecutor is configured, ModalExecutor will be still used, which might be unwated
3. (related to previous point) we should probably not allow to override the type/executor class from UA::$ui prop, but instead of allow to override the Form class/seed only, such Form can be used then in any executor as configured

**Comment by mvorisek** [comment]
@mkrecek234 I do not want to spend more time on this topic and proactive communication.

HEAD was https://github.com/atk4/ui/commit/cd544dfb3231a88596436cea76660595ebff1f08
