### ISSUE TITLE
form addField() argument refactor

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#187]
This ticket is to refactor $form->addField() to address:

 - https://github.com/atk4/core/issues/50 - refactor of seeds
 - need to improve usecase of form to be used without Model
 - need consistency in the arguments
 - rename namespace FormField/Generic into FieldDecorator, to avoid confusion between model fields and form fields.

The proposal is to clarify meaning of the arguments for addField:

 - First argument is name of the field.
 - Second argument describes field decorator.
 - Third argument describes the model field.

addField will follow this process:

 1. if no model is associated, create a blank one.
 2. find field object in a model.
 3. if field with specified name does not exist in a model, create new field in model based on 3rd argument of addField
 4. create field decorator using field type or as specified in 2nd argument.
 5. return field decorator.

### First Argument

Only accepts string values. If null, then Field decorator will be created without field. Can be good for "capcha", but all other field decorators will require field.

### Second argument

Possible value types:

 - Object (e.g. FieldDecorator\Money) will be associated with field and added into form.
 - Seed (e.g. ['Money', 'class'=>'big']) 
 - String (e.g. 'Your Field') - will be used as a label/caption.
 - null - deduct field decorator from field type

### Third argument

Possible value types:

 - Object (e.g. new Image()) can specify Model Field object
 - Seed (e.g. ['type'=>'integer']) will be used to create field object.
 - String (e.g. 'integer') will be used as a type
 - null, add generic field or use existing

### Examples

Here is a full test-case looking at all the possible use cases:

``` php
// initialize blank form, no model association
$cc = $layout->add('Columns');
$f = $cc->addColumn()->add(new \atk4\ui\Form());

// adding field without model creates a regular line
$f->addField('one');

// Second argument string is used as a caption
$f->addField('two', 'Caption');

// Array second is a default seed for default line field
$f->addField('three', ['caption'=>'Caption2']);

// Use zeroth argument of the seed to specify standard class
$f->addField('four', ['Checkbox', 'caption'=>'Caption2']);

// Use explicit object for user-defined or 3rd party field
$f->addField('five', new \atk4\ui\FieldDecorator\Checkbox('Caption 2'));

$a = [];
$m = new \atk4\data\Model(new \atk4\data\Persistence_Array($a));

// model field uses regular line form field by default
$m->addField('one');

// caption is a top-level property of a field
$m->addField('two', ['caption'=>'Caption']);

// ui can also specify caption which is a form-specific
$m->addField('three', ['ui'=>['form'=>['caption'=>'Caption']]]);

// type is converted into Checkbox form field with caption as a seed
$m->addField('four', ['type'=>'boolean', 'ui'=>['form'=>['caption'=>'Caption2']]]);

// Can specify class for a checkbox explicitly
$m->addField('five', ['ui'=>['form'=>['Checkbox', 'caption'=>'Caption3']]]);

// Form-specific caption overrides general caption of a field. Also you can specify object instead of seed
$m->addField('six', ['caption'=>'badcaption', 'ui'=>['form'=>new \atk4\ui\FieldDecorator\Checkbox(['caption'=>'Caption4'])]]);

$f = $cc->addColumn()->add(new \atk4\ui\Form());
$f->setModel($m);

// Next form uses setSource
$f = $cc->addColumn()->add(new \atk4\ui\Form());

// this is optional BTW:
$data = ['one'=>'value1', 'two'=>'value2'];
$f->setSource($data);

// Field is not defined, we can define here
$f->addField('one', null, ['type'=>'password']);

// adding that same field but with custom form field seed
$f->addField('two', 'Caption2');

// We can override type, but seed from model will still be respected. Set source does not have to have data for the field
$f->addField('three', ['Checkbox']);

// We override type and caption here
$f->addField('four', ['Line', 'caption'=>'CaptionX']);

// We can specify form field object. It's still seeded with caption from model.
$f->addField('five', new \atk4\ui\FieldDecorator\Checkbox());

// can add field that does not exist in a model
$f->addField('nine', new \atk4\ui\FieldDecorator\Checkbox(['caption'=>'Caption3']));
```

**Comment by DarkSide666** [comment]
Looks OK

**Comment by romaninsh** [comment]
I have updated description, please re-read once again for any inconsistencies.

**Comment by DarkSide666** [comment]
_4. create field decorator using field type or as specified in 2nd argument._
What will be precedence if we, for example, define field decorator (2nd argument) as checkbox, but model field (3rd argument) as text?

**Comment by romaninsh** [comment]
- 2 - if we use field decorator, then there is no disambiguity.
- 3 - as per my text you can't specify 3rd argument for existing field. 
- 4 - currently 'foo' would be undocumented, we can create exception if that is passed, but may be used in the future. For now it is all passed as 2nd argument to 'addField'.

**Comment by DarkSide666** [comment]
What field will be if we call:
`addField('test', new FieldDecorator\Money(), ['type'=>'date'])` ?
That's what I mean when asking about precedence. Will it be money field or date field in this case?

**Comment by romaninsh** [comment]
money.

**Comment by DarkSide666** [comment]
ok
