### ISSUE TITLE
Modal JS onComplete error in latest develop 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1883]
- I have a JsModal which is opened from a page. 
- Inside this JsModal, there is a Crud which opens another Modal on row click.
- Having updated to the very latest develop branch, I now get this JS error if I click on the first Js Modal's Crud row - and the next JsModal is not opening but stuck at a small window with the "Loading..." message.

![image](https://user-images.githubusercontent.com/28671486/194003801-dc5a7641-e41d-4843-8cf5-3a7c34d80a0f.png)

**Comment by mvorisek** [comment]
please post a minimalistic repro code with a steps to reproduce

**Comment by mvorisek** [comment]
the browser console screenshot indicates a 500 server error

maybe you use some of the removed methods by https://github.com/atk4/ui/pull/1881?

not displaying the AJAX problem to user is related with https://github.com/atk4/ui/issues/1720 - for now, open the network browser developer tools tab and copy the server response here

**Comment by mkrecek234** [comment]
Just analysed it further: The reason was an exception in the view that was assigned to the Modal. The exception was not visible, but resulted in the above JS code. For repro, just create a View that causes an Exception, and load it into a Modal, then the above JS code will fire. Not very developer-friendly.

**Comment by mvorisek** [comment]
yes, see my last post - so you figured the problem and the only atk4/ui issue is not showing the error which is known as https://github.com/atk4/ui/issues/1720, right?

**Comment by mkrecek234** [comment]
Yes, correct, thus, I will close this issue
