### ISSUE TITLE
Modal executor should (re)load whole modal incl. buttons

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1928]
currently only modal inner content/view is r(e)loaded causing uncessary html/js generated like:

![image](https://user-images.githubusercontent.com/2228672/199005298-fde8875c-e54c-4643-8685-243d7382c047.png)

![image](https://user-images.githubusercontent.com/2228672/199004391-73ca20ad-b0a2-4155-bd7d-3a40ad488065.png)

no modal content should be generated before displayed (when inner content/view is loaded via API) and once AJAX for (re)load is fired, whole content should be rendered/downloaded

this will improve performance when main page has a lot of modal executors and also allow greater executor buttons customizations per (re)loaded content/records

filter popup generates a lot code as well, maybe move it to AJAX completely as well

**Comment by mvorisek** [comment]
This is complicated, as Fomantic-UI requires the modal title/buttons to be not wrapped in any div.

**Comment by lubber-de** [comment]
> This is complicated, as Fomantic-UI requires the modal title/buttons to be not wrapped in any div.

Could you explain? The modal header is actually expected to be wrapped in a "header" and the buttons are expected to be wrapped in an "actions" div... So where does FUI _not_ expect them to be wrapped?

**Comment by mvorisek** [comment]
(AFAIR, not on desktop ATM to provide source code references) FUI modal expects header/button wrapper divs to be present immediatelly after the main modal div. This limitation is not compatible with our atk4/ui reload impl, as we cannot reload inner html without the wrapping div (outer html) reload.
