### ISSUE TITLE
Active column filters in Grid not visible

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1950]
Steps to reproduce:
- Filter a column in a sample grid, e.g., https://ui.agiletoolkit.org/demos/collection/tablefilter.php
- All "down arrows" are displayed in blue, no matter if the respective column filter is active or not.

Expected behavior:
- E.g., only mark active filtered column's down arrow icon blue, all others gray.

In previous version I think it displayed like that, now all columns' arrows are blue by default.

**Comment by mvorisek** [comment]
Yes, important for UX, definitely not intentionally dropped.

**Comment by mvorisek** [comment]
I identified the problem, return of `recallData()` is an array and should be empty if there are no data, previously there was a fallback to empty array wrongly.
