### ISSUE TITLE
Label details='0' is invisible

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#198]
The following code:

```
$layout->add(['Label', 'Books available to rent: ', 'detail'=>'0']);
```

Thinks that detail is not specified at all:

<img width="154" alt="screen shot 2017-07-12 at 11 02 42" src="https://user-images.githubusercontent.com/453929/28112632-ac8857aa-66f1-11e7-9b7f-9b701f09daa0.png">

Unless 'detail' is null, it should be displayed.

**Comment by DarkSide666** [comment]
will be fixed in https://github.com/atk4/ui/pull/199
