### ISSUE TITLE
`data-id` values must not be typecasted using UI persistence

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1985]
The newly added decimalSupport in #1981 will not correctly interprete dots and commas.

Steps to reproduce:
- You have a uiPersisdence with `decimalSeparator` set to comma, and `thousandSeparator` set to dot (as standard e.g., in Europe).
- You have a form with a model field with type `float`.
- You enter a value `1.2` into the field (which is incorrect, as dot can only be a thousand separator, so 1.200)

Expected behaviour:
- The entered number is incorrect: If the user wants a decimal value of `1,2` he needs to enter it accordingly. If he wants to enter 1200, he may have entered 1.200
- This should throw a ValidationException as this is an incorrect entry.

Current behaviour:
- The number will be stored as if the user had inputted `1,2` - so the dot - even though as it is a thousandSeparator in that language - will be interpreted as a decimalSeparator...

**Comment by mvorisek** [comment]
this issue needs a Behat test

the current problem is undetected because of #1985 as the (UI formatted) value is parsed by PHP (on AJAX, what you describe as `1.2` -> `1` issue) but it is silently accepted
