### ISSUE TITLE
Default typecasting should be applied for any View on set 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1990]
Enforcing HTMLTemplate in #1989 to accept string only, makes coding unnecessarily cumbersome.

Why is PHP-standard typecasting not allowed here where model field is an integer?

`\Atk4\Ui\Header::addTo($app, [$model->get('stock')]); `

Simple code, simple PHP typecasting. Do we really want to enforce everyone to code like this?
\Atk4\Ui\Header::addTo($app, [(string) $model->get('stock')]); 

Either, any view which is set a value to should continue to use PHP-default typecasting or it should behind the scenes use uiPersistence typecasting.

**Comment by mvorisek** [comment]
with hintable, such problem is detected by phpstan, and was before #1989

in 95% of atk4/ui code we do accept `string` (strongly typed) strictly, so even if we fix this for Header/View constructor content/label, the issue will remain for other 95% cases

Also, opinionated, I wonder how purely numeric header is common/helpful to be supported - `'Stock #' . $model->get('stock')` will cast the integer implicitly...

**Comment by mvorisek** [comment]
It may be implemented in the future, but we need reliable idea how to address this. So far requiring everything typecasted to string is the best and the safest.
