### ISSUE TITLE
Crud Modal not behaving correctly 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2002]
In the most recent FUI releases, I encounter the following issue:
- You have a crud on a model with many fields
- The first field say is name, and for a given record it is empty
- You go to "Edit" for that record in the Crud, and the edit modal opens
- You enter something in the first field
- You scroll down, and click "Save"
- It won't save but jump back the focus to that first field. Scrolling down again and clicking save will then save correctly.

See screen recording:

https://user-images.githubusercontent.com/28671486/220370891-ad9cd326-1621-4098-ad09-75047942cd15.mov

**Comment by mvorisek** [comment]
Yes, this is caused probably by Fomantic-UI autofocus, I have already reported like 5 issues with it. In the next FUI release, I hope they will be fixed.

Please try - click somewhere in the modal before clicking Save. Then click Save. Will the form save?

Also can this be reproduced on some atk4/ui UI demo?

**Comment by mkrecek234** [comment]
Correct, any click anywhere in the modal before clicking save will make it save immediately. Atk4/Ui demo: I could not find one yet, as most modal forms are too small I believe

**Comment by mvorisek** [comment]
Too small - you can resize your browser viewport ;-)

Let's wait a few days until FUI is updated, I am fine with merging the latest FUI Beta into atk4/ui then.

**Comment by mkrecek234** [comment]
Can be reproduced on /demos/collection/crud.php by reducing browser size - edit iso2 code, scroll down to reach save button and you will encounter the issue described above.
