### ISSUE TITLE
Grid IPP change is broken

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2016]
Check https://dev.agiletoolkit.org/demos/collection/grid.php and try to change the Items per Page to 25.

Error:
`Atk4\Ui\Exception: Not sure what to do with argument`

**Comment by mvorisek** [comment]
in v4.0 it is working - https://ui.atk4.org/demos/collection/grid.php

needs a Behat test

**Comment by mkrecek234** [comment]
@mvorisek Even if you raised now the bar to enforce behat tests, I cannot provide this, as it drives efforts to fix newly introduced bugs significantly, even though the fix is simply like in this case. This bug is really annoying, as it destroys the IPP functionality simply. So I would welcome either a merge by you, or any contribution by you to make it ready-to-merge also based on your lifted requirements.
