### ISSUE TITLE
Implement multi-step Virtual Page

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#204]
It's possible to nicely extend VirtualPage so that it allows developer to specify multiple steps. Here is example syntax:

``` php
$mp = $layout->add('MultiStep');
$popup = $layout->add(['Modal', 'vp'=>$mp]);
$layout->add('Button')->js('click', $popup->jsShow());

$popup->set(function($p) {
    // define modal contents dynamically, oh and btw, $p is MultiStep page.

   if(!$p->step) {
     $this->add('Text')->set('Welcome to this popup. Click next to go to page 1');
     $this->add(['Button', 'Next step'])->js('click', $p->jsStep(1));
   } elseif ($p->step == 1) {
      $this->add('Text')->set('OK, you arrived at the first page. Well done');
   }
});
```

**Comment by ibelar** [comment]
May be a Wizard class that extends Modal with proper VirtualPage setup, next and previous action button. Then on each step of the page you could set your buttons state function depending on each step.
 if ($p==1) {
    $p->next->set(['show', 'enable']); // could be hide, enable, show....
    $p->previous->set('disable');
}

**Comment by romaninsh** [comment]
Well it won't be necesserily in a Modal, but I think the goal here is to make it work like paginator - it can either refresh itself or use a link and reload all page. If you use forms, then you will probably use JS to reload.

**Comment by romaninsh** [comment]
Wizard is implemented.
