### ISSUE TITLE
Call to a member function cloneRegion() on a non-object

### ISSUE THREAD

**Issue by nandlal-tjm** [atk4/ui#208]
I run the demos and get this error Call to a member function cloneRegion() on a non-object
\vendor\atk4\ui\src\Lister.php on line 14

**Comment by DarkSide666** [comment]
Can you please give us more details and some sample code which you try to run?

Lister line 14 doesn't look like it could throw exception:
https://github.com/atk4/ui/blob/develop/src/Lister.php#L14

**Comment by romaninsh** [comment]
not enough info, closing.
