### ISSUE TITLE
Symfony 6.3 dependency

### ISSUE THREAD

**Issue by abbadon1334** [atk4/ui#2088]
In `atk4/core` we have the following dependency in composer.json:
`
        "symfony/yaml": "^3.4 || ^4.4 || ^5.1 || ^6.0"
`
In `atk4/ui`, we have:
`
        "symfony/filesystem": "^4.4 || ^5.3",
        "symfony/http-foundation": "^4.4 || ^5.3"
`
And the following managed "conflicts":
`
        "symfony/console": "<4.4.30 || >=5 <5.3.7",
        "symfony/css-selector": "<4.4.24 || >=5 <5.2.9",
        "symfony/filesystem": "<4.4.30 || >=5 <5.3.7",
        "symfony/http-foundation": "<4.4.30 || >=5 <5.3.7"
`
Currently, 5.3 is unmaintained and it's not possible to use `atk4/ui` within the framework.
What issues have been encountered and how can we I help the dependencies to raise at least for Symfony 6.3 like in atk4/core?

**Comment by mvorisek** [comment]
Submit a PR with ` ... || ^6.0` for all symfony deps and let's see the CI result. The conflicts are unreleated, they refer to v before 5.3.7.

**Comment by abbadon1334** [comment]
Seems ok, 8.2 install 6.3 and gives no error in unit tests.
what do you think? #2089

**Comment by mvorisek** [comment]
LGTM, merged.
