### ISSUE TITLE
$element->set(123) fails (not sure what to do)

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#209]
``` php
$x = 1;

// This works correctly
$app->add(['Button', $x*2]);


// But this does not:
$app->add('Button')->set($x*2);
```

**Comment by DarkSide666** [comment]
That's impossible. How do it fail? Is there some Exception or it doesn't calculate `$x*2` correctly?

**Comment by romaninsh** [comment]
it shows button without a label.

**Comment by acicovic** [comment]
Can anybody re-test this? Maybe we should close the issue if everything is OK.

**Comment by DarkSide666** [comment]
As expected it works nicely both ways.
