### ISSUE TITLE
$app->jsRedirect() and $app->redirect()

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#210]
Those two methods are needed, because redirecting is essential when developing apps, and the only way to do them is by using header('Location') and new jsExpression() and require knowledge of HTTP headers and JavaScript. By creating wrappers, we can educate new users to build apps without relying on those technologies:

``` php
$button->on('click', function($b) {
    return $m->app->jsRedirect(['page2', 'a'=>'b']);
});
```

``` php
if (!$app->logged_user->loaded()) {
    $app->redirect(['error', 'message'=>'Must be logged in']);
}
```

**Comment by DarkSide666** [comment]
Also it's very important to explain in docs how these two methods differ.

**Comment by romaninsh** [comment]
true.

**Comment by PhilippGrashoff** [comment]
AFAIK thats implemented, can we close this?
