### ISSUE TITLE
CRUD Paginator uses peristence action() which Persistence_Array doesn't have

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#211]
CRUD Paginator uses peristence action() which Persistence_Array doesn't have.

Description here: https://forum.agiletoolkit.org/t/error-when-using-crud/319/2

**Comment by mvorisek** [comment]
CRUD is working with array persistence and tested in https://github.com/atk4/ui/blob/91c497f86958fd09a5267d493f06c6a4c4a50c8c/tests-behat/crud.feature#L60
