### ISSUE TITLE
Multiple dropdown with special characters not working anymore

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2141]
Please check https://github.com/fomantic/Fomantic-UI/issues/2979 affecting also Atk4/Ui

**Comment by mvorisek** [comment]
Please provide self-contained minimal atk4/ui repro code.

**Comment by mvorisek** [comment]
should be solved (and tested) as part of https://github.com/atk4/ui/issues/1020

**Comment by mkrecek234** [comment]
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/2993

**Comment by mvorisek** [comment]
please submit a PR with FUI update
