### ISSUE TITLE
Draggable inclusion is hardcoded - make it part of $app->cdn

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#2169]
When adding a drag handler via 
`$grid->addDraghandler();`
 \Atk4\Ui\JsSortable is loaded. 

In this file we can find the line
`$this->getApp()->requireJs('https://cdn.jsdelivr.net/npm/@shopify/draggable@1.0.0-beta.5/lib/draggable.bundle.js');` hardcoded.

I am often programming in the plane, so I'm offline. 
Therefore I use the variable $app->cdn to load all assets offline in this case. Works pretty well so far.
But there's no chance of loading draggable.js without (heavy) tweaking.

The problem is, that if I go offline and reload the page, it throws a JS error (in console) and messes up the app. The only "solution" / workaround for now is to remove the draghandler from the grid when going offline. Therefore the functionality can't be tested offline.

Steps to reproduce: 
- Load needed assets via $app->cdn offline (usually these are (I copied them into my publicly availabe folder "offline-assets-v3": $this->cdn = [
            'atk'              => 'offline-assets-v3',
            'jquery'           => 'offline-assets-v3',
            'serialize-object' => 'offline-assets-v3',
            'semantic-ui'      => 'offline-assets-v3/semanticui',
            'flatpickr'      => 'offline-assets-v3',
        ];)
- Load a grid
- Add $grid->addDraghandler(); into init()
- Load the page when online and open JS console
- Go offline
- Reload page and check console

Therefore I suggest making draggable part of $app->cdn.

Thoughts?

**Comment by mvorisek** [comment]
done in https://github.com/atk4/ui/pull/1874#discussion_r985152987 / https://github.com/atk4/ui/pull/1874/commits/3e786a095d5d9425c047aa5730784395d392cdae already, released since v4.0

**Comment by bedengler** [comment]
You are awesome @mvorisek - I must look at newer versions before posting, sorry for the inconvenience...
