### ISSUE TITLE
Crud wrongly rendered on model's with soft delete 

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2174]
Situation:

- You have a model where you added the soft delete logic as described in https://atk4-data.readthedocs.io/en/develop/advanced.html#soft-delete
- You have a simple crud which is linked to that model.
- You delete a row

Expected behavior:
- The row will be faded out after delete

Current behavior:
- The record will be deleted (and JsToast confirms it), BUT the row will not fade out
- Thus, the crud is not correctly updated and still shows the deleted row

**Comment by mvorisek** [comment]
post here minimal repro (like in https://github.com/atk4/ui/issues/2156 for example)

**Comment by mvorisek** [comment]
feel free to reopen once the needed info is provided
