### ISSUE TITLE
For on Tab, warning when destructing unsaved form

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#219]
Old ATK used to alert user every time un-saved changes were about to be destroyed. For example when you have form on a tab, switching to a different tab brought a warning.

Currently no warning is displayed, which may be pretty important for some clients.

**Comment by romaninsh** [comment]
i think that currently switching tab does not destroy their content. I suppose hitting browser's reload should warn about unsaved changes.

**Comment by acicovic** [comment]
Going to other tabs does not destroy the content, only leaving the page does. Pointers on how to implement this can be found here:

https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by ibelar** [comment]
Form leave without save was implement using https://github.com/atk4/ui/pull/705

**Comment by acicovic** [comment]
@ibelar good catch, closing this.
