### ISSUE TITLE
Tutorial intro.php is broken

### ISSUE THREAD

**Issue by woodholly** [atk4/ui#2201]
Please fix documentation and tutorials. None of examples work with current version of software.

**Comment by woodholly** [comment]
Half of the demos doesn't  work too

**Comment by mvorisek** [comment]
Feel free to submit a PR.

Also see demos/ which we test using CI and should be 100% working. They are hosted at https://dev.atk4.org/demos/.

**Comment by woodholly** [comment]
https://dev.atk4.org/demos/tutorial/intro.php?atk_layout_maestro_wizard=2

**Comment by mvorisek** [comment]
Thank you. Contribution welcome, it seems such issue was introduced recently as such demo/tutorial was working.

**Comment by woodholly** [comment]
I can't fix it without docs..

**Comment by mvorisek** [comment]
The demos is broken because of some recent change. You should be able to debug it. We are keen on clean code and the code itself acts as very good and up-to-date documentation.
