### ISSUE TITLE
Demo broken on UserAction

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2215]
1. Go to https://dev.agiletoolkit.org/demos/collection/crud.php (develop branch)
2. In configured crud, click on gear wheels

Error:
Critical Error
Error: Object of class Atk4\Ui\Demos\WrappedId could not be converted to string

**Comment by mvorisek** [comment]
Thank you for spotting this and providing good report.

I missed this in #2168 and I guess it is a demo issue only. Will fix.
