### ISSUE TITLE
Lookup multiple feature broken

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2218]
- Setup a lookup control connected to a model with `multiple=> true`
- Then renderView function is broken as it attempts to load a single entity in line https://github.com/atk4/ui/blob/5cef498fb307f4d1b93abe04fb294271662c57f9/src/Form/Control/Lookup.php#L399

**Comment by mvorisek** [comment]
Please post here a minimal repro using some model(s) in the demos.

Also, do you know the fix?

**Comment by mvorisek** [comment]
No input provided.
