### ISSUE TITLE
Wrong decimal number in `atk4_money` type typecast

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#2234]
Following the ATK4 Discord Help conversation, here is the summary:

- Store a value, e.g., -172158.01 in an atk4_money field.
- It is wrongly typecasted as € -172.158,01000000001

Reason is that https://github.com/atk4/ui/blob/a441238bfa34d57a42f63b8d5c119c7744b5e995/src/Persistence/Ui.php#L132 calculates the wrong number of decimals of any given number.

Here is an alternative calculation of $valueDecimals for that given line which is working:
`$valueDecimals = ($decimalPos = strrchr((string) $value, '.')) ? strlen($decimalPos) -1 : 0;`

**Comment by mvorisek** [comment]
fixed in https://github.com/atk4/ui/pull/2233
