### ISSUE TITLE
Demo fails to open modal

### ISSUE THREAD

**Issue by slava-vishnyakov** [atk4/ui#228]
When I go to this URL https://atk-warehouse.herokuapp.com/docs.php?type=purchase
and click "Add new purchase", this happens:

![image](https://user-images.githubusercontent.com/817931/31560664-deea099a-b05d-11e7-8324-78dcfec5c814.png)

Google Chrome 61.0.3163 (WebKit 537.36)

Actually, this happens almost on every page, where "Add new" is..

**Comment by slava-vishnyakov** [comment]
Pretty printing the source gives this:

![image](https://user-images.githubusercontent.com/817931/31560755-3420d48e-b05e-11e7-95fa-a87b206a341f.png)

**Comment by slava-vishnyakov** [comment]
Breakpoint shows: 

![image](https://user-images.githubusercontent.com/817931/31560794-590d340e-b05e-11e7-81dc-5442c1d23e1c.png)

**Comment by romaninsh** [comment]
Hi. 

This simply runs older version of ATK, it should be fine with the 1.2.1.

**Comment by slava-vishnyakov** [comment]
Is there a chance the demo gets fixed? I was thinking this project was a cool idea, but I even have no idea what this project does :) there are no screenshots of the functionality and demo seems to be broken? :)

**Comment by slava-vishnyakov** [comment]
Thanks for the response, btw :)

**Comment by romaninsh** [comment]
I have updated the version, and javascript works OK now, however another problem emerged. I have created a different ticket #229. Will close this one and focus on the new ticket to avoid confusion.

**Comment by slava-vishnyakov** [comment]
@romaninsh Thanks!

**Comment by romaninsh** [comment]
It's now resolved on the demo-site, i switched it to use feature branch: https://github.com/atk4/warehouse/commit/97cf33ac05090060a5986e2d5a6326ff960bda14#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R7
