### ISSUE TITLE
Testing ORM

### ISSUE THREAD

**Issue by francescobianco** [atk4/ui#236]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by romaninsh** [comment]
Hi. Looks pretty interesting. We have used http://github.com/atk4/schema but it is very basic. I'll review and post.

Overall your library could fill the gap, but moldable would need to be cleaned up a little.

**Comment by romaninsh** [comment]
https://stackoverflow.com/questions/9774046/can-agile-toolkit-generate-its-model-from-existing-sql-db

**Comment by romaninsh** [comment]
https://github.com/atk4/atk4-addons/tree/master/dynamic_model (old)

**Comment by romaninsh** [comment]
@DarkSide666 what are your thoughts here? We might need auto-creator..

**Comment by francescobianco** [comment]
@romaninsh Moldable AUTOMATICALLY generate, update, sync the database schema triggered by Class Model schema change! Think about when a customer asks for a schema change and you have to create a new migration or fixer for the main schema! with Moldable you simply add a new attribute to the model class

**Comment by romaninsh** [comment]
@francescobianco, i have reviewed documentation available for your project as well as the code. Agile UI relies on Agile Data to interact with a database. It's a very powerful database abstraction library capable of all the necessary operations except for schema alteration.

Surely we can use some help with creating a better migrator, but it needs to fit well into the architecture. I tried to outline requirements here: https://github.com/atk4/data/issues/251 and it should be a pretty straightforward migration of an older code to the newer.

If you would like to contribute, you can give it a try and create an add-on. As for relying on your code - there is too much overlap as well as schema handling is outside of main scope for Agile UI or Agile Data, so I'm closing this ticket.

I appreciate your suggestions. Try writing few projects Agile Data to better understand it and if you like it - you would know what's needed.

**Comment by francescobianco** [comment]
@romaninsh Please, could you install the library and give me a feedback if there is something wrong?
Sorry !! Please!! please!! please!! I still can not find anyone who installs and try the library

**Comment by DarkSide666** [comment]
Well, this repo basically is like our own old dynamic_model just a lot more sparse (and better  abstracted) code. Anyway we will not be able to use this directly because our Agile/data models are different and as @romaninsh said above - we definitely will need add-on like this for Agile Data, but it should be build exclusively for Agile Data models, not some other ORM models.

What I am wondering is - can your library do the opposite? Detect changes in DB structure and reverse engineer them in ORM model? Like our old ModelGenerator (https://stackoverflow.com/questions/9774046/can-agile-toolkit-generate-its-model-from-existing-sql-db).
