### ISSUE TITLE
[epic] Making Agile UI conceal errors (for production use)

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#237]
We don't want errors to pop up on production sites. This issue is for tracking various techniques and issues about hiding error messages from user. We recognize that depending on choice/taste there may be 3 settings:

1. Display all errors, even with sensitive info, no logging.
2. Display only error messages, log full errors.
3. Display "we are having technical difficulties", log full errors.

Please read: http://agile-core.readthedocs.io/en/develop/debug.html#introduction

**Comment by PhilippGrashoff** [comment]
I think some of the huge commits @abbadon1334 did to App, this is not available? Will assign him.

**Comment by mvorisek** [comment]
`App::caughtException()` method can be overriden to output less info

closing for now, but feel free to comment
