### ISSUE TITLE
Provide Bootstrap extension for Agile UI

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#241]
The plan is to create a separate extension, e.g. "atk4/bs" which would extend all the basic components re-defining their templates in favour of Bootstrap CSS.

This would also provide an extension to App class (see https://github.com/atk4/ui/blob/develop/src/App.php#L286)

**Comment by acicovic** [comment]
Is this still relevant?

**Comment by DarkSide666** [comment]
I don't think so because we're to deep into Fomantic and `atk4/ui` is using only Fomantic.
If somebody someday will want to create atk4/ui port to Bootstrap then it's fine, but I don't see reason why keep such _feature request_ open here.
