### ISSUE TITLE
DropDown to respect $value inject

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#251]
$field = $model->hasOne('country_id', new Country());

$field->ui = ['Form'=>['Dropdown', 'values'=>...]];

A list of values specified to a form field decorator like this should take precedence over the model results. 

P.S. if you're working on this issue, please also make Closure valid value for 'values'.

function($key){ return $value; }

-----------

also final fix would be to allow:

$field->ui = ['values'=>...];

which would be injected into both DropDown of enum (or model) and take precedence and table column.

(table column may be tricky since the "id" value is normally hidden)

**Comment by DarkSide666** [comment]
`$field->ui = ['Form'=>['DropDown', 'values'=>...]];`
form key should be lowercase.

**Comment by DarkSide666** [comment]
Currently:

```
//$f->addField('test', null, ['ui'=>['values'=>['a'=>'aaa','b'=>'bbb']]]); // dont work
//$f->addField('test', new \atk4\ui\FormField\DropDown(['values'=>['c'=>'ccc','d'=>'ddd']])); // works
//$f->addField('test', null, ['enum'=>['aaa','bbb'], 'ui'=>['values'=>['a'=>'aaa','b'=>'bbb']]]); // don't work
//$f->addField('test', null, ['ui'=>['form'=>[new \atk4\ui\FormField\DropDown(),'values'=>['a'=>'aaa','b'=>'bbb']]]]); // dont work
```

**Comment by romaninsh** [comment]
why would Form be lowercase btw? Should it be consistent with a class?

**Comment by DarkSide666** [comment]
I believe it was implemented lowercase at some point and also for historical reason - it was lowercase in old toolkit. Actually this key doesn't have anything to do with class names. It's just a property name/key.

**Comment by romaninsh** [comment]
This is superseeded by #268
