### ISSUE TITLE
Refactor Form::setModel to use $field->ui['Form'] by default.

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#252]
Update to use ui['Form'] for form field decorator and ui['Table'] for table column decorator. Include backward compatibility for ['form']. In the future will keep key consistent with name of the component.

``` php
$agile_data_field->ui['Form'] = new \atk4\ui\FormField\Password();
```

For clarification: https://github.com/atk4/ui/issues/251#issuecomment-340463791

**Comment by PhilippGrashoff** [comment]
IMO this works now, can this be closed?

**Comment by PhilippGrashoff** [comment]
@Romans: Is this still of any interest? For the 2 years since this issue was opened everyone uses $field->ui['form'] with a small f.
