### ISSUE TITLE
Consistency with js-action emitting methods.

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#253]
Currently some methods which return JavaScript action are prefixed with "js":

 - Table::jsRow
 - TableColumn\Checkbox::jsChecked
 - Form::jsField()
 - Loader::jsLoad()

While other methods don't use prefix:

 - Form::error() and Form::success()
 - Modal::show() and hide()

 Which approach should we use and why?

**Comment by skondakov** [comment]
I like the second one more, as the first examples could do without "js" prefix, but the second examles would look strange with "js" prefix

**Comment by romaninsh** [comment]
but we would still leave js* for the classes, such as `new jsReload()`

**Comment by ibelar** [comment]
Simple suggestion, why not add another prefix when js action are intended to change ui state for end users.

Form::uiError() or uiSuccess()
Modal::uiShow() or uiHide()

This should also cover method that require more than one js action to be returned to update a ui state.
ex: $crud->uiNotify()

**Comment by ozgurgesli** [comment]
As someone who is new to ATK, I would be happier with better consistency, so having everything with js prefix. Are there any downsides to this other than typing two more chars?

Actions are bridge to js domain, they don't function like the rest of the code. When i'm debugging or reading documentation or sample codes, when i see js prefix somewhere, that is a big help for me. I would have never expected Form:error() or Modal::show() being an action. Obviously if i think about it i could figure out, but i find the prefix doing a good enough job there.

**Comment by mvorisek** [comment]
implemented in https://github.com/atk4/ui/pull/2001
