### ISSUE TITLE
how to work!  copy 

### ISSUE THREAD

**Issue by 1040304181** [atk4/ui#265]
I don't know how to install it.

**Comment by DarkSide666** [comment]
Please give us more information so we can help you with that.

As it is written in readme:

> Install by downloading from from www.agiletoolkit.org or through composer composer require atk4/ui.

**Comment by 1040304181** [comment]
i'm in china ,ican't get some js css, please upload them, 
ex https://cdn.rawgit.com/mdehoog/Semantic-UI-Calendar/0.0.8/dist/calendar.min.js
https://cdn.rawgit.com/atk4/ui/1.3.0/public/atk4JS.min.js
https://cdn.rawgit.com/atk4/ui/1.3.0/public/agileui.css

**Comment by romaninsh** [comment]
Hm.. Try moving folder "vendor/atk4/ui/public" to the root of your project.

If this does not work either, then set $app->cdn = false;

If it still not finding CSS , paste the error here.

**Comment by 1040304181** [comment]
all of js、css  can`t get！

**Comment by DarkSide666** [comment]
As I said previously - give us more info.
What have you tried, some screenshots, can you open URL https://cdn.rawgit.com/atk4/ui/1.3.0/public/atk4JS.min.js in your browser. If you can't, then check your internet settings, firewall, proxy.
