### ISSUE TITLE
Dropdown Value decoration

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#268]
Here is my current proposal:

## 1. Add "values" property for Model Field.

This will be change in Agile Data, which would allow to specify list of allowed properties (derived from keys of $value array) as well as set default presentation for UI.

``` php
$model->addField('gender', ['values'=>['F'=>'Female', 'M'=>'Male']]);
```

Effect would be similar to:

``` php
$model->addField('gender', [
    'enum'=>['F', 'M'],
    'ui'=>['values'=>['F'=>'Female', 'M'=>'Male']]
]);
```

## 2. Add formatter

When defining Model Field, through 'ui' array you should be able to define a format of how the field is presented. 

```
$model->hasOne('country_id',[
    new Country(),
    'ui'=>['format'=>'<i class="{$country_code} flag"></i>{$country}']
])->addFields(['country_code', 'country']);
```

This will result in Dropdown, Autocomplete and Table column values to display values with icons:

<img width="149" alt="screen shot 2017-11-15 at 17 17 12" src="https://user-images.githubusercontent.com/453929/32850473-2fa960c0-ca2a-11e7-96e9-1d94906c6bec.png">

(This must not conflict with https://github.com/atk4/data/issues/252)
(Will use https://github.com/atk4/ui/blob/develop/src/TableColumn/Template.php and https://github.com/atk4/ui/blob/develop/src/Lister.php)

## 3. Allow formatter callback

With a sensible callback, you should be able to use different ways to decorate. Output of a callback may be a string or a Template object, in which case it will still be populated with the values.

``` php
$model->hasOne('country_id',[
    new Country(),
    'ui'=>['format'=>function($m){
        if($m['is_eu']) { 
            return '<i class="eu flag"></i>'.htmlspecialchars($m['country']);
        } else {
            return new Template('<i class="{$country_code} flag"></i>{$country}');
        }
    }]
])->addFields(['country_code', 'country']);
```

## 4. May be combined with manual mapping:

This technically can be packed up into a new field class, so you don't have to re-type every time:

``` php
$model->addField('country_id',[
    'values'=>['uk'=>['country_code'=>'gb', 'country'=>'United Kingdom']],
    'ui'=>['format'=>'<i class="{$country_code} flag"></i>{$country}']
]);
```

## 5. Track fields properly

As you import fields you may use different aliases. Code must work consistently in Table (where it works with $row model) and Dropdown (where it works with referenced model)

```
$model->hasOne('country_id',[
    new Country(),
    'ui'=>['format'=>'<i class="{$code} flag"></i>{$title}']
])->withTitle()->addFields(['code'=>'country_code']);
```

## 6. Can store data for other uses

A {$_} could be a tag which is set automatically to a the title field. Similarly {$_id} could refer to $model->id_field.

``` php
$model->hasOne('country_id',[
    new Country(),
    'ui'=>['format'=>'<div data-currency="{$currency}"></div>{$_}']
])->withTitle()->addField('currency');
```

NOT INCLUDED (yet):

 - handling for recursive data types (tree)
 - handling for contained data (e.g. json)

---------------
OLD DESCRIPTION

We need a way to decorate drop-down and auto-complete values correctly. Unlike "Persistence/UI.php" which we use to convert "date" object into presentable string and back, values for drop-downs and auto-completes does not have to be read back. Also for the table value interpretation is important.

On other hand, sometimes values may include multiple fields and may be formatted differently. So lets say auto-complete field could contain a template like this:

"Invoice {$invoice_no} dated {$date}"

This could be rendered as string and perhaps even contain HTML. This can theoretically even be a callback. Works for Tables also.

But drop-downs may use some icons etc. 

``` html
  <div class="item" data-value="dk"><i class="dk flag"></i>Denmark</div>
  <div class="item" data-value="dj"><i class="dj flag"></i>Djibouti</div>
  <div class="item" data-value="dm"><i class="dm flag"></i>Dominica</div>
``` 
I suppose we could use `'<i class="{$country_code} flag"></i>{$country}'` value here, right?

**Comment by acicovic** [comment]
In my opinion those are great ideas. Point 1 seems to work already. Point 2 doesn't seem to work. For starters, having point 2 would be awesome.

**Comment by mvorisek** [comment]
Mostly implemented, issue is too broad and stale.
