### ISSUE TITLE
CRUD should focus first input field when add/edit dialog is open

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#270]
makes entry easier. Dialog pops up, enter data, press enter, dialog closes. 

if this is implemented as enhancement to form/modal, then the approach should be documented for other uses.

**Comment by gartner** [comment]
In addition to focus on first element when opened, I think that the 'Save'-button should be included in the tab-order.
I like to use <tab>-key to walk through the form, but here, when I tab out of the last input-field in the dialog, focus is sent to the browsers url-bar. (Using Chrome).

I would like it to be placed on the 'Save'button, where I can then press <space> to save the record.

**Comment by acicovic** [comment]
This is already implemented so I think the issue should be closed.

**Comment by DarkSide666** [comment]
agreed, works
