### ISSUE TITLE
[Epic] - progress bar

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#274]
A stand-alone component which will execute several actions when loaded. Based around SSE. By default will be "teal" but when reaching 100 will become green. Setting progress to `null` will set 100 progress, but yellow color. When process exits successfully, progress goes to 100 and becomes green.

Second argument to `$process->set` can specify message to display on the progress bar.

``` php
$bar = $app->add('ProgressBar');
$bar->set(function($process) {
    $process->set(10);
    sleep(1);
    $process->set(40);
    sleep(2);
    $process->set(null, 'Just few more seconds...');
    sleep(4);
});
```

Because $process extends SSE you may also send other JavaScript events.

**Comment by romaninsh** [comment]
Crazy idea, but what if progress-bar and Console ( #275 ) is implemented as a same object and you can switch between just seeing progress bar or opening it up to see details?

**Comment by DarkSide666** [comment]
I think they should be separate features. Progress bar can extend console class, but it's definitely not the same as console.
