### ISSUE TITLE
refactor Template.php to work without each()

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#278]
construct `each()` has been depreciated in PHP 7.2. It still works, but requires a @.

The current implementation relies on multiple calls to `each()` to advance internal array pointer while walking through reference-infused array built from the templates. We use it similarly to tokenizer, where we advance forward to the next item in the template based around logic.

Refactoring out `each()` is not a trivial task but must be done (I'm not sure of a simple workaround)

**Comment by romaninsh** [comment]
actually we can use cur() and next().. !

**Comment by PhilippGrashoff** [comment]
This can be closed as current Template code does not use each() any more

**Comment by DarkSide666** [comment]
checked - no more each() there. Closing.
