### ISSUE TITLE
AutoComplete ignores model conditions until input is done

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#282]
Excluding records in autoComplete Field via Model does only work when something is typed into autoComplete field.

```
	$autocomplete_model = new Group($app->db);
        $autocomplete_model->addCondition('id', 'not in', $group_ids_related);
	$add_to_existing_group = $group_form->addField('add_to_group', [
		'AutoComplete',
		'model'			=> $autocomplete_model,
		'placeholder'	=> 'Search for existing group',
		'plus'			=> true,
		'search'		=> ['name'],
	]);
```

In my case, the record "12.07.2018 Priminus Stratius" is excluded, its id is in $group_ids_related. (which is an array with the excluded id's)

The autoComplete with no input done: it loads the first 3 records of the table:
![bugautocomplete1](https://user-images.githubusercontent.com/33204878/33634036-1352ae74-da13-11e7-8301-776700fe9d31.png)

"12.07.2018 Priminus Stratius" appears, though its excluded in the model.

When typing something, the Conditions are used correctly:
![bugautocomplete2](https://user-images.githubusercontent.com/33204878/33634087-49ed24b4-da13-11e7-9969-e626bb6d0754.png)

See how "12.07.2018 Priminus Stratius" is now gone.

**Comment by PhilippGrashoff** [comment]
This problem seems session related:
After closing and reopening the browser, the results are fine. As soon as I change data (adding new records, deleting records, altering records) the problem occurs. 
After reopening the browser again, the problem is gone.

**Comment by ibelar** [comment]
Autocomplete use Semantic dropdown module for fetching field content and the dropdown module use the semantic api to call the server. By default, semantic api cache setting is On, so the initial values of the autocomplete field will be cache and display to user to avoid a server round trip.

You can try the following in AutoComplete.php.  Set the apiSettings in the dropdown call to add the cache property and set it to false, like below.

```
        $chain->dropdown([
            'fields'      => ['name' => 'name', 'value' => 'id'/*, 'text' => 'description'*/],
            'apiSettings' => [
                'url' => $this->getCallbackURL().'&q={query}',
                'cache' => false,
            ],
        ]);
```

You will find the call to dropdown function inside the AutoComplete::init() method.

**Comment by PhilippGrashoff** [comment]
Thats it! Thanks for the hint.

The question is: is this a bug? That cache is set to true as standard. After all, it makes the field not do the right thing if conditions are set in the related model. Trying to figure if there could be other cases this causes trouble. If not, maybe set cache false if a model with conditions is passed, and set it to false if a model without conditions is passed is the right thing.

Best regards
Philipp

**Comment by romaninsh** [comment]
i think we should switch cache off, because for us correct implementation and appropriate values is more important.

**Comment by ibelar** [comment]
On a side note, cache has nothing to do with model condition. It will simply cache the initial dropdown value. So when going back to the field, it will use cache value instead of going back to server. Believe this is still a good thing to have when using a long list of dropdown values that does not changes too often. 
I'll submit PR with cache OFF by default and the possibility to switch it on when needed.

**Comment by romaninsh** [comment]
yes if the dropdown is reloaded with different dropdown values then it will mess things up.

**Comment by romaninsh** [comment]
Thanks @ibelar
