### ISSUE TITLE
Pass "Add new" text as parameter to autoComplete

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#284]
![autocomplete1](https://user-images.githubusercontent.com/33204878/33676723-ce5079f6-dab6-11e7-8ad8-e0e1b892f4a3.png)

At the moment, when passing `plus = true` parameter, the text of the "Add new" button is hard coded:

```
if ($this->plus) {
    $this->action = $this->factory(['Button', 'Add new']);
}
```

IMO this text should be passed as parameter as well so it can be changed without touching the class code.

Best Regards
Philipp

**Comment by PhilippGrashoff** [comment]
Simple, working solution:
In class AutoComplete:
```
    // set this to create right-aligned button for adding a new record
    public $plus = false; 
	
	//Text for adding new record button
	public $plus_text = 'Add new';

    ....

        if ($this->plus) {
            $this->action = $this->factory(['Button', $this->plus_text]);
        }
```

Creating Autocomplete with aditional parameter:

	```
$add_to_existing_group = $guest_form->addField('add_to_guest', [
		'AutoComplete',
		'model'			=> $autocomplete_model,
		'placeholder'	=> 'Search for existing guest',
		'plus'			=> true,
		'plus_text'		=> '+ new Guest',
		'search'		=> ['name'],
	]);
```

**Comment by romaninsh** [comment]
better yet - a seed for the entire button should be injected: 

```
$this->action = $this->factory(
    ['Button', $this->plus_text],
    $this->plus
); 
```

**Comment by PhilippGrashoff** [comment]
Lookup FormField which is the sucessor of AutoComplete implements this, closing.
