### ISSUE TITLE
CRUD values from model don't propagate to boolean and dropdown values

### ISSUE THREAD

**Issue by dpavliuchkov** [atk4/ui#288]
Hi there. I have recently started with this framework so I might not know things. Anyway, I need some help to figure out how to do what I want.

I have a model called `HeroItem` that is populated from my database. I have built a simple CRUD admin interface to edit items that belong to heroes, for example.

### Question 1 - replace integer key with label

There is a field called `type` which is integer – type of item such as weapon, armor, potion etc. First of all, I didn't found how to supply values native so I have used a hack described here https://github.com/atk4/ui/issues/251#issuecomment-340202939

I used this snippet to alter the form value
```
function init()
    {
        parent::init();

        $values = [
            1 => 'Junk',
            2 => 'Recipe',
            3 => 'Quest',
            4 => 'Weapon',
            5 => 'Armor',
// etc...
        ];

        $this->getElement('type')->ui['form'] = new \atk4\ui\FormField\DropDown(['values' => $values]);
    }
```
This works great for the dropdown in the form, I see the label and not the key. However it is still displayed as a numeric value in the grid. How an I solve that?

![joxi_screenshot_1513183932404](https://user-images.githubusercontent.com/1267719/33951147-45694eae-e03f-11e7-9684-769b0224aadc.png)

### Question 2 - checkbox is not checked for boolean=true columns
On the previos screenshot item with `type=4` is `equipped`. This is correct. But when I click on edit and see the form – it is not checked and if I save it I will lose my value. If I manually tick it it will work fine. But I often forget to do that. See screenshot below.

![joxi_screenshot_1513183944647](https://user-images.githubusercontent.com/1267719/33951252-8bed7256-e03f-11e7-8f5a-bdf17ec52ddf.png)

Thank you! Hope we can resolve it without hacking the engine. I can provide the code of my models if that is needed.

**Comment by romaninsh** [comment]
Hi, @dpavliuchkov, could I ask you to re-post your question on the support forum (https://forum.agiletoolkit.org) and I'll answer there.

**Comment by dpavliuchkov** [comment]
@romaninsh done, thanks!
https://forum.agiletoolkit.org/t/fatal-error-while-using-field-with-type-boolean-and-enum/198

Although the case with checkbox might be a bug :)

**Comment by romaninsh** [comment]
Reading it now. If it is, I'll open a separate ticket with more specific information.

**Comment by DarkSide666** [comment]
it is this bug https://github.com/atk4/ui/issues/155

**Comment by romaninsh** [comment]
Wasn't that solved?

**Comment by dpavliuchkov** [comment]
fiy, I am using composer with `"atk4/ui": "^1.3"`

**Comment by romaninsh** [comment]
#291 should address this.
