### ISSUE TITLE
array as second argument in View->add()

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#289]
Hi,

I read the code of \atk4\ui\View->add() function and something does not seem right:

The comment says the second argument can be an array:
`@param string|array $region (or array for full set of defaults)`

But a few lines later, an Exception is thrown if this argument is an array:
```
        if (is_array($defaults)) {
            throw new Exception('Second argument to add must be region or null!');
        }

```
Is this wrong or am I just not understanding the code completely? ;)

Best regards
Philipp

**Comment by romaninsh** [comment]
The problem is with PHP 7.0 which otherwise throws an error about incompatible arguments. I'd suggest that the method be refactored to use `null` as default value.

**Comment by PhilippGrashoff** [comment]
As we dropped 7.0 support, lets see if we can get rid of this issue.

**Comment by PhilippGrashoff** [comment]
The code block I mentioned in the issue does not exist any more, I close this
