### ISSUE TITLE
Template->render('Region') causes PHP notice

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#301]
In its current implementation, the render() function of \atk4\ui\Template class causes a PHP notice if a Region is set. Sample call:
`$template->render('Content');`

Notice:
`Notice:  Only variables should be passed by reference in /var/www/html/TourManagement/vendor/atk4/ui/src/Template.php on line 715`

My simple solution was to create a variable first and then pass it so PHP does not complain:
```
    public function render($region = null)
    {
        if ($region) {
	    $t = $this->get($region);
            return $this->recursiveRender($t);
        }

        return $this->recursiveRender($this->template);
    }
```

Best regards
Philipp

**Comment by DarkSide666** [comment]
I think in line https://github.com/atk4/ui/blob/develop/src/Template.php#L729 we don't need to get parameter as reference `&$template` because it's not changed there anyway.

**Comment by romaninsh** [comment]
Although that's normally intended for outside use, why not properly document this and let others use it?

http://agile-ui.readthedocs.io/en/latest/template.html#rendering-template

**Comment by DarkSide666** [comment]
We have to get rid of that PHP notice and I think that removing that reference is a way to go. 
Not sure how changing of documentation could help here.

**Comment by romaninsh** [comment]
Dark, I'm saying we need both :).. Where is that PR where you removed reference?

**Comment by DarkSide666** [comment]
There is no PR for this :)

**Comment by PhilippGrashoff** [comment]
Closing as Template was refactored and does not pass by reference any more to recursiveRender()
