### ISSUE TITLE
Implement Upload Field for form

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#304]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=53301193)](https://www.bountysource.com/issues/53301193-implement-upload-field-for-form?utm_source=53301193&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Requirements:
 - [x] must not use flash
 - [x] support all major browsers
 - [x] should display progress bar while uploading
 - [x] field needs to execute PHP callback with ($original_filename, $path)
 - [x] after file is uploaded, should have icon to remove uploaded file
 - [x] removing uploaded file should execute PHP callback

Optional ideas (separate bounties, or can be implemented later):
 - multiple files on the same field
 - show "processing" when file is fully sent, but response not received
 - allow to cancel upload while it is in progress
 - use upload field without the form (example)

**Comment by romaninsh** [comment]
@DarkSide666 please review requirements, in case i missed something to make sure it's usable.

**Comment by DarkSide666** [comment]
* add ability to validate uploaded file, for example, to restrict (black-list or while-list) particular file extensions or mime-types. Can be defined as callback.
* add ability to configure progress bar to show uploaded percent or uploaded file size in bytes, Kb or Mb.

**Comment by romaninsh** [comment]
Implemented in #306 and #346
