### ISSUE TITLE
[Addon] - Implement User Login, Authentication, Passwords

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#308]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=53377341)](https://www.bountysource.com/issues/53377341-addon-implement-user-login-authentication-passwords?utm_source=53377341&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Agile UI is perfect for creating admin systems of any kind and shape, however it could really use some "Login" add-on.

In the legacy version of ATK4 we had:

``` php
$app->add('Auth')->setModel('User');
```

This would enable login check for the rest of the script. We need to offer a similar functionality through a high quality add-on.

**Current implementation: https://github.com/atk4/login**

**Current status: partially implemented**

**Comment by PhilippGrashoff** [comment]
As there has been a lot of change in Login add-on, can this be closed?

**Comment by DarkSide666** [comment]
Yeah. No use of such issue here.
Of course it would be nice that some day atk4/login will be super cool and high-quality, but that's not question of atk4/ui anyway.
