### ISSUE TITLE
[Addon] - Implement "Outbox", email sending functionality

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#309]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=53377806)](https://www.bountysource.com/issues/53377806-addon-implement-outbox-email-sending-functionality?utm_source=53377806&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Outbox add-on offers a modern implementation of sending user messages (email, SMS, push notification, etc) through "Gateways".

The main idea is to have add-on which could handle two-way communications with mail delivery provider:
 - [ ] Provide 'Outbox' model, containing copies of sent email, status
 - [ ] Support Gateway-templates and prefer APIs, store "tags"
 - [ ] Provide API interface for Gateway callbacks (delivered/bounced/opened/clicked, etc)
 - [ ] Ability to re-send message by admin
 - [ ] Provide UI to send a basic message

Optional features:
 - Integrate with Filestore addon for attachments.
 - Integrate with #308 login add-on for email confirmation.

To provide cross-gateway transparency we also need to use a good 3rd party framework. Here are some candidates:
 - https://github.com/gabrielbull/omnimail
 - https://github.com/juriansluiman/SlmMail
 - https://github.com/Stampie/Stampie

Example Admin UI:
<img width="1208" alt="screen shot 2018-01-04 at 11 54 05" src="https://user-images.githubusercontent.com/453929/34562456-6c02223a-f146-11e7-89f7-0a0cc8726421.png">

Send a message UI:
![5f757471f9599cacb84199aad4119668da414a21_1_690x412](https://user-images.githubusercontent.com/453929/34562605-0af3975c-f147-11e7-9fc0-7f697962e4fc.png)

Email field:

![6b4a7c32f4b335a45d412625d5e9fb5870690df2](https://user-images.githubusercontent.com/453929/34562630-260dce18-f147-11e7-87ed-711b6316c3fc.png)

**Current status: not started**

**Comment by romaninsh** [comment]
Outbox Model: (WARNING - USES LEGACY SYNTAX)

``` php
class Outbox extends Model {
    public $table = 'outbox';
    function init()
    {
        parent::init();
        $this->hasOne('User')->editable(false);

        $this->addField('slug'); // short text describing message
        $this->addField('message')->type('text');
        $this->addField('email');
        $this->addField('name');
        $this->addField('tags')->type('text');
        $this->addField('is_sent')->type('boolean');
        $this->addField('is_urgent')->type('boolean');

        $this->addField('error')->type('text');
        $this->addField('is_bounced')->type('boolean');

        // Instantiate Mandrill here, used in two function now
        $this->mandrill = new Mandrill($this->app->getConfig('mandril/key'));
        $this->tags_array = [
            'FromServer' => $this->app->pm->base_url,
            'Site' => get_class($this->app) == 'App_CLI' ? 'Command Line' : $this->app->getFrontendURL()
        ];
    }

    function new($slug, $template, $tags = []) {
    }

    function send() {
    }
}
```

The way to integrate would be by adding this into your User class:
``` php
$this->hasMany('Messages', new Outbox());
```

To use:

``` php
$user->ref('Messages')
    ->new('password reminder', 'reminder', ['link'=>$link])
    ->send();
```

**Comment by mvorisek** [comment]
this is not akt4/ui problem, should be solved in https://github.com/atk4/outbox
