### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by giandi** [atk4/ui#315]
Dear,
I'm just started a project by using your framework and I've noticed that lot of strings are hardcoded and cannot be translated (_ie boolean values as yes/no into tables, months name in the calendar, "Add new" button into the CRUD and so on_).

Have you planned a way to make your framework localizable?

Thanks so much

**Comment by romaninsh** [comment]
Yes, the localization is planned for 1.5. The way how it will be implemented is by wrapping all hard-coded english texts into $app->_() function and you can redefine this function with any localization implementation. I'll keep this ticket open but just wanted to let you know it's coming.

In a meantime - check our progress on version 1.4, perhaps you can help us get there faster :)

**Comment by acicovic** [comment]
This is in the works. Anyone interested can consult https://github.com/atk4/core/pull/93 and https://github.com/atk4/core/pull/110.

**Comment by acicovic** [comment]
Closing this, issue will be tracked on #1482
