### ISSUE TITLE
Form does not handle integer fields set to 0 correctly

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#317]
Several of my models have integer fields, e.g.
`['amount_guests_payreduced',  'type'=>'integer']`

When this model is assigned to a form and 0 is entered as value for this field, NULL gets stored into database instead.
Have a look at this short screencast:
http://www.spame.de/atkinteger0.mkv

Even if I set the value manually to 0 in the database, it is not displayed in the form.

Interestingly, it does not happen in Demo Form, here it works for the fields Project Hours Est and Reported:
http://ui.agiletoolkit.org/demos/form3.php

Can someone reproduce this error? It happens in all integer fields in my application. I am using the newest Agile UI that was published.

Best regards
Philipp

**Comment by DarkSide666** [comment]
I can reproduce.

It stores `0` in database, but in form it shows empty string in form field.
In model it's defined as `['type'=>'integer']`.

**Comment by DarkSide666** [comment]
fixed in https://github.com/atk4/ui/pull/319
