### ISSUE TITLE
Form error reloads in new popup window

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#318]
See video: https://www.useloom.com/share/d2d10646e443491895448f9b306f3f5c

**Comment by romaninsh** [comment]
I've seen this in the past. Issue is with modal dialog zIndex..

**Comment by DarkSide666** [comment]
But shouldn't it lreload in existing window where we have form?
Now it reloads in new window.

**Comment by romaninsh** [comment]
re-opening because this issue is still worked on.
