### ISSUE TITLE
QuickSearch should have cancel [X] icon

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#322]
Quicksearch should have Cancel [X] icon in case filter is enabled.
See old toolkit for example. Or some autocomplete solutions.

**Comment by DarkSide666** [comment]
![screenshot](https://user-images.githubusercontent.com/1969119/35886065-7eecea62-0b98-11e8-9355-968a09555339.png)

for example something like this or probably nicer is needed. That "delete" icon only should show up in case filter is enabled.

**Comment by romaninsh** [comment]
thing is, i'm not sure if semantic ui allows 2 buttons after a field, but worth trying.

**Comment by DarkSide666** [comment]
that would be very good for usability of this field.

**Comment by acicovic** [comment]
@DarkSide666 currently Grid/CRUD search shows an X button when there's text in it. Should we mark this issue as closed or is there something missing?

Thanks!

**Comment by DarkSide666** [comment]
Yeah it's implemented quite some time ago.
