### ISSUE TITLE
Can not move Modal window by dragging of its title bar

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#323]
Normally Modal opens up in the middle of screen and that's fine. But in some cases Modal contents are dynamic (for example have Console in Modal) and can grow outside of visible screen.

In that case, or any other case, when user tries to move Modal window by dragging by modal window title that doesn't work. Modal is not movable.

**Comment by romaninsh** [comment]
yes, semantic ui modals are not movable. If you find otherwise - please link example.
