### ISSUE TITLE
Modal should be refreshed after adding dynamic content

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#324]
If we have dynamic content in modal (for example Console), then modal should be refreshed to correctly position it.

Please read https://forums.meteor.com/t/position-of-modal-semantic-ui-popup/28429/2 and maybe that can help you somehow to get idea what's needed.

**Comment by ibelar** [comment]
Imants;

Have you tried refreshing the modal from inside console after updating content.
something like:
```
$console->send($modal->js()->modal('refresh'));
```

Also can you provide a code sample on how to reproduce.

thanks;

**Comment by DarkSide666** [comment]
Page:
```
// Set up Modal
$mod = $app->add(['Modal', 'title' => 'Generate']);
$mod->addScrolling(); // I wonder if this works at all
$mod->notClosable(); // Don't allow to close Modal by clicking outside of it
$mod->set(function ($modal) use ($m){
    $modal->add('Console')->setModel($m, 'gen');
});

// Add button
$app->add(['Button','Generate'])->on('click', $mod->show());
```

Model:
```
    public function gen() {
        $this->log('info', 'Starting long process');

        for($i=0;$i<25;$i++) {
            $this->debug('test = '.$i);
            sleep(1);
        }

        return 'Success';
    }
```

Video:
https://www.useloom.com/share/668785beb4e34fc5ae735dd950c68ab5

See Console is growing infinitely and there are no vertical scrollbars not in browser, not Modal, not Console. But when I resize browser window and set it back to full, then vertical scrollbar appears.

**Comment by ibelar** [comment]
Add this option to your modal and it should be working:

```
$mod->setOptions(['observeChanges' => true]);
```

**Comment by DarkSide666** [comment]
Yeah !!! That helped.
https://www.useloom.com/share/b5951efe581f44829f69063d95096c6b

Can you add this info in documentation? Or maybe even set this as default option?
Or maybe we need method $modal->observeChanges() which will enable this switch and document it?

**Comment by romaninsh** [comment]
btw console can be limited with max-height in theory.
