### ISSUE TITLE
Upload field: When $hasFocusEnable = true and "cancel" button is clicked in file dialog, file dialog reopens

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#349]
Check this screencast, explains everything:

www.spame.de/bug_upload_reopen.mkv

Best regards
Philipp

**Comment by ibelar** [comment]
Philipp;
I am not able to reproduce this. Can you describe your environment please?
Os, Browser etc. 
Look like the input field in video is not readonly. Have you change the template file for the upload field in upload.html? if so, please make sure it is readonly: <input type="text" placeholder="{$PlaceHolder}" readonly/>

**Comment by PhilippGrashoff** [comment]
Hi ibelar,

I am running the latest Firefox (58.0) on Ubuntu 16.04.
I did not touch the HTML template.
The HTML output shown in Firefox for the field is:
```
<div class="field">
      
<div id="_93ec6e48__layout_file_upload">
<div class="ui readonly action input" style="">

<input placeholder="Datei hochladen" readonly="" type="text">
<input name="file_upload" placeholder="Datei hochladen" id="_93ec6e48__layout_file_upload_input" value="" type="hidden">
<input accept="" style="display:none" type="file">
<div id="_93ec6e48__layout_file_upload_button" class="ui icon button" style=""><i id="_93ec6e48__layout_file_upload_button_icon" class="  upload icon" style=""></i></div>
</div>
<div class="ui tiny indicating progress active" data-value="1" data-total="100" data-percent="1" style="display: none;">
<div class="bar" style="transition-duration: 300ms; width: 1%;"></div>
<div class="label">1%</div>
</div>
</div>
</div>
```
I also tried to set readonly="readonly" which does not change the behaviour.

The code that creates this field is:
```
$uploader = $f->addField('file_upload', [new \atk4\ui\FormField\Upload(), 'caption' => 'Datei hochladen', 'placeholder' => 'Datei hochladen']);
	//after upload finish
	$uploader->onUpload(function($f) use ($app, $group) {
		...
                ...
	});
		$uploader->onDelete(function($f) use ($app, $group) {
	});
```

Best regards
Philipp

**Comment by ibelar** [comment]
Thanks Philipp for your quick reply.

I have tried to reproduce the error using Firefox on a Mac but no success. May be this issue is related to an Ubuntu/Firefox combination. The fileUpload plugin attach a focus eventHandler, when option is set, to simulate a click event on the file input type field, which open the file dialog. 

From your video, it look like the 'focus' event is fire after you cancel file upload dialog, thus firing the open dialog again.

**Comment by PhilippGrashoff** [comment]
Upload field was changed to use a onClick event, not onFocus, so closing this
