### ISSUE TITLE
'ops'=>['u'=>false]] disables r as well

### ISSUE THREAD

**Issue by roelleor** [atk4/ui#352]
```php
$crud = $app->add(['CRUD', 'ops'=>['u'=>false]]);
```
The above code disables r as well. The fatal error is thrown:
atk4\ui\Exception: You cannot disable "r" operation

**Comment by romaninsh** [comment]
I think that 'ops' should be refactored before it gets any wide-spread use. Also it's not documented properly.

**Comment by DarkSide666** [comment]
```
$crud = $app->layout->add(['CRUD', "ipp" => 15]);
$crud->ops=['c'=>false, 'r'=>true, 'u'=>false, 'd'=>false];
```
still shows Create New

**Comment by DarkSide666** [comment]
`$app->add(['CRUD', 'ipp' => 10, 'ops'=>['c'=>false]]);`
throws Exception - You cannot disable "r" operation because we always need to pass full `ops` array.
I think it should use array_merge in this case and merge with default options.

**Comment by romaninsh** [comment]
What about properties like this:

``` php
  public $can_edit = true;
  public $can_delete = true;
  public $can_add = true;
```

The reason why the OPS code is not working is because we disabled array merging on injections, having a separate properties is probably better.

**Comment by roelleor** [comment]
that sounds like a good solution to me. 
However, this probably mean that these properties cannot be altered when using MasterCrud, right?

**Comment by romaninsh** [comment]
why not, they can be injected as any other property.

**Comment by roelleor** [comment]
Nice, I’m not intimite with the source code yet

**Comment by DarkSide666** [comment]
maybe better:
* can_create (C)
* can_read (R)
* can_update (U)
* can_delete (D)
so we are consistent with abbreviation CRUD ?

**Comment by DarkSide666** [comment]
I can implement that if you agree :)

**Comment by romaninsh** [comment]
i'm working on MultiCRUD, there may be some other things i'll need to fix. we should also probably use canRead, canUpdate, and slowly refactor arguments that way. So no worries, i'll refactor this too.

**Comment by DarkSide666** [comment]
ok
