### ISSUE TITLE
Use constants for CRUD operations

### ISSUE THREAD

**Issue by gartner** [atk4/ui#357]
CRUD operations can be defined using letters 'c', 'r', 'u', 'd' as array keys. 

Why not define some class constants that can be used in addition:

const CRUD_CREATE = 'c';
...

Internally, the code should then use these constants, but code made by users of UI, that is still using just the letters, their code will keep working.

Having constants would make it more obvious what the code does.

**Comment by romaninsh** [comment]
Was just discussed in #352
