### ISSUE TITLE
CRUD - add if model is loaded..

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#362]
CRUD's add form will do editing action if model is loaded:

``` php
$model->loadAny();
$crud->setModel($model);
```

Solution would be to add unload() into setModel(), it would only mess things up anyway.

**Comment by FabulousGee** [comment]
Can you clarify what's the issue here, please?

I load a model with LoadAny (so I get a real model or a new empty model as return, right?). I hand this over to the CRUD and the CRUD wants to edit the new empty model as well instead of creating it?
Or did I get this wrong?

**Comment by DarkSide666** [comment]
CRUD should no care about is record loaded in model or not.
Maybe CRUD setModel() should even clone model and unload. Or just unload model.

**Comment by romaninsh** [comment]
just unload is fine.

**Comment by DarkSide666** [comment]
Already implemented here: https://github.com/atk4/ui/blob/develop/src/CRUD.php#L107
So this issue can be closed.
