### ISSUE TITLE
Field hints 

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#377]
We should be able to define hint which would appear on the form under a field:

<img width="318" alt="21c06878-b047-11e4-8804-aa1e3813b6ea" src="https://user-images.githubusercontent.com/453929/36469515-5afa9616-16df-11e8-8575-aaafb289a2d9.png">

``` php
$model->addField('name', ['ui'=>['hint'=>'Full name and surname']]);
```

**Comment by DarkSide666** [comment]
implementation here: https://github.com/atk4/ui/pull/378
