### ISSUE TITLE
Set custom Label to CheckBox

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#385]
This code should produce a checkbox with a custom label, but it does not:
```
$chbox = new \atk4\ui\FormField\CheckBox();
$chbox->label = 'custom_label';
$f->addField('notification'.$notification->get('id'), $chbox);
```
Instead, the input name is shown.

Changing line 58 of FormField/CheckBox.php from
      `$this->template['label'] = $this->label ?: $this->caption;`
to
     `$this->template['Content'] = $this->label ?: $this->caption;`
did it for me, but if thats a nice fix I do not know :)

**Comment by romaninsh** [comment]
the idea is that Content can be used for adding some other elements, e.g.

```
$checkbox->add(['template'=>new Template('<a href=...>blah</a>')]);
```

then it will override the label and the label is used as default if Content is not set. Possibly this is broken, I am not sure. Content shouldn't be set if it's null and if element has no children.

Probably a bug, but needs a different solution to the one you propose.

**Comment by romaninsh** [comment]
See also checkboxes here: https://github.com/atk4/ui/blob/develop/demos/form5.php#L75

**Comment by romaninsh** [comment]
Also, can you do this:

 [ ] Agree to [terms and conditions](url).

**Comment by acicovic** [comment]
@PhilippGrashoff do you think this issue should be left open?
