### ISSUE TITLE
Grid/Table can not handle $g->addColumn(null, ..., null)

### ISSUE THREAD

**Issue by FabulousGee** [atk4/ui#388]
Right from the demo ( https://github.com/atk4/ui/blob/develop/demos/grid.php ) , I wanted to use the code like this:
```
require 'init.php';
require 'database.php';
$g = $app->add(['Grid']);
$g->setModel(new Country($db), FALSE);
$g->addQuickSearch();
$g->menu->addItem(['Add Country', 'icon' => 'add square'], new \atk4\ui\jsExpression('alert(123)'));
$g->menu->addItem(['Re-Import', 'icon' => 'power'], new \atk4\ui\jsReload($g));
$g->menu->addItem(['Delete All', 'icon' => 'trash', 'red active']);
$g->addColumn('name');
$g->addColumn(null, ['Template', 'hello<b>world</b>']);
//$g->addColumn('name', ['TableColumn/Link', 'page2']);
$g->addColumn(null, 'Delete');
$g->addAction('Say HI', function ($j, $id) use ($g) {
    return 'Loaded "'.$g->model->load($id)['name'].'" from ID='.$id;
});
$g->addModalAction(['icon'=>'external'], 'Modal Test', function ($p, $id) {
    $p->add(['Message', 'Clicked on ID='.$id]);
});
$sel = $g->addSelection();
$g->menu->addItem('show selection')->on('click', new \atk4\ui\jsExpression(
    'alert("Selected: "+[])', [$sel->jsChecked()]
));
$g->ipp = 10;
```

I only changed lines 7 and 12 (added a FALSE to have the columns added myself and added one column).
Returns an "calling function on NULL" exception in line 234 of Grid.php...

It seems like Grid can not handle it like this. It works with the normal table and forms though.

**Comment by DarkSide666** [comment]
It's not because `setModel()`, it's because you have `null` as column name and it calls `Table->addColumn(null, 'whatever', null)` and here https://github.com/atk4/ui/blob/develop/src/Table.php#L151 it try to create model field with name `null` :)
```
    $field = $this->model->addField($name); // $name = null here
```

Solution / workaround - use meaningful column name (which is not model field name).

**Comment by DarkSide666** [comment]
Well actually it was because of setModel :)
Here is real issue why this happened: https://github.com/atk4/ui/issues/390 and solution: https://github.com/atk4/ui/pull/391

**Comment by romaninsh** [comment]
Table should support null as a column name.
