### ISSUE TITLE
'width' causes AutoComplete to glitch

### ISSUE THREAD

**Issue by FabulousGee** [atk4/ui#400]
When you add the following option to any AutoComplete-FormField, it causes the field to glitch (you don't see the text you entered). It seems to work fine in the background but it's an ugly optical bug

```
'width'=>'four'
```

Demo: https://github.com/atk4/ui/blob/develop/demos/autocomplete.php
Replace Line 31f.
```
    'search'      => ['name', 'iso', 'iso3'],
]);
```
with
```
    'search'      => ['name', 'iso', 'iso3'],
    'width'      => 'four',
]);
```

This of course also happens with a correct "width"-environment, when I have a group sixteen wide and four fields all equal four wide - just wanted to keep the example short.
If you need more information or another demonstration, please let me know.

**Comment by acicovic** [comment]
@FabulousGee could you check if this is still an issue?

**Comment by DarkSide666** [comment]
@FabulousGee I can not reproduce this issue now. It's probably fixed at some point. If that's not the case, then please let us know. Otherwise we will close this issue shortly.

**Comment by FabulousGee** [comment]
Sorry for not giving feedback on the issue right away but I am pretty busy currently...

I can check this again in early 2020, so we can either leave this open or close it (and I will file a new report if the issue persists).
But I believe since you can not reproduce with the given code, chances are high that this has benn fixed in the ongoing development.
