### ISSUE TITLE
AutoComplete doesn't save new added instance

### ISSUE THREAD

**Issue by FabulousGee** [atk4/ui#404]
When I add a regular AutoComplete field to a form and use "plus" to create a new instance of the model, it adds the new values to the database and selects them in the AutoComplete correctly. But when I hit "Save", the value doesn't get saved in the field.
However, if I add a value manually by selecting it in the dropdown (pre-existing value), then it's saved correctly.

Maybe also related to PR https://github.com/atk4/ui/pull/403

**Comment by ibelar** [comment]
Was not able to reproduce... can you check if this still a bug. 
Perhaps this is resolve with PR#403

Steps: 
- demos/autocomplete.php;
- fill up form using add new country in Country2 field;
- submit form 
then newly create country is set in $f->model['country2']

Am i missing something?

**Comment by romaninsh** [comment]
@ibelar, I think problem is in one of the following steps:

 - newly added entry is auto-filled in a outer form
 - newly added entry specifies ID of a newly added country in an auto-complete
 - when the outer form is submitted, the ID is passed to the submit handler.

**Comment by ibelar** [comment]
@FabulousGee - Do you still have this issue? If so, can you provide sample code?

**Comment by FabulousGee** [comment]
I will check on it and report back in - give me a few weeks, currently a bit in a hurry.

**Comment by mvorisek** [comment]
closing as no response, @FabulousGee can you reproduce on the latest develop and/or 3.1 rel?
