### ISSUE TITLE
Implement conditional field display for form

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#410]
Currently form will display fields as you specify it with setModel(). I'm proposing to introduce a mechanism to hide/show certain field with JS based on the values of other fields:

![form-logic](https://user-images.githubusercontent.com/453929/37764160-cfd5db9a-2db8-11e8-91d2-279cfeb5487f.gif)

For implementation, we should look for some existing library, where field logic could be provided through json, but even if that does not exist, we can pick the one we had for ATK4:

https://github.com/atk4/atk4/blob/4.4/public/atk4/js/atk4_univ_basic.js#L419

Regarding the definition, the logic would be the following:

``` php
new jsConditionalForm($form, [
   'include_time_field'=>[true=>['time_format']]
]);
```

Any field that is explicitly shown during certain value condition (true) should be hidden by default.  This should work for onChange but also during initial form load respecting default value.

## Nested logic

Fields that are controlled by the element which becomes hidden, must also be hidden:

``` php
new jsConditionalForm($form, [
   'phone1'=>[  ['phone2'] ],
   'phone2'=>[ ['phone3'] ],
]);
```

in this scenario if you  enter both phone1 and phone2 then field for phone3 appears. If you remove value for phone1 it should hide phone2 and phone3.

## alternatives

It should be possible to define various conditions for showing a certain field:

``` php
new jsConditionalForm($form, [
   'is_delivery'=>[  ['tip_amount'] ],
   'is_vip'=>[ ['tip_amount'] ],
]);
```

selecting delivery and VIP then removing VIP shouldn't hide tip_amount because as long as one of the above is selected it should be visible.

## values

It should be possible to specify custom value too:

``` php
new jsConditionalForm($form, [
   'delivery_type'=>[  'time_slot' => ['delivery_date', 'delivery_time'] ],
]);
```

You can also use some reverse logic:

``` php
new jsConditionalForm($form, [
   'breakfast'=>[
     [ 'breakfast_time' ],  
     'traditional'=>[ 'breakfast_time', 'is_tost_included' ],
     'no_thanks' => []
   ],
]);
```

## Further ideas

I'm open to additional ideas on this control. The goal of this integration is to have a simple form integration:

``` 
$form->setConditionalLogic([ field=>rules, ...]);
```

one idea we could do is to use '>30' for numerical comparison, but that can probably be implemented later.

**Comment by ibelar** [comment]
We could add to the show condition a field validation to be true, as an option, from semantic-ui form validation module. They already have a full set of validation rules already define. This would take care of '>30' numerical comparison.

**Comment by romaninsh** [comment]
i am not a big fan of browser validation. It's extra work if we validate on the server anyway in my opinion. Can semantic rules be used for visibility? 

Perhaps we can build something on our own initially without the deep logic and then integrate/improve later.

**Comment by romaninsh** [comment]
Potential implementation in #422

**Comment by PhilippGrashoff** [comment]
Can this be closed as Conditional Form is implemented?
