### ISSUE TITLE
Table header - example showing how to add clickable button

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#412]
It would be nice if we had an example for Table which would explain how to add icons into table headers:

<img width="340" alt="screen shot 2018-03-22 at 11 06 59" src="https://user-images.githubusercontent.com/453929/37767202-2cf79f2c-2dc1-11e8-9e35-b60fada3707e.png">

Once icons are there, we can target them, use click handlers or hover.

**Comment by mvorisek** [comment]
Closing as stale.
