### ISSUE TITLE
Popovers

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#413]
Normally Modal opens full-screen, but sometimes we want to associate it with a certain element:

<img width="406" alt="screen shot 2018-03-22 at 11 08 46" src="https://user-images.githubusercontent.com/453929/37767282-82fb51ac-2dc1-11e8-9425-3fb585fac192.png">

Semantic UI supports this, sort-of, with "HTML" for popups:

<img width="554" alt="screen shot 2018-03-22 at 11 11 19" src="https://user-images.githubusercontent.com/453929/37767356-c45e72e6-2dc1-11e8-9808-9cbd0d3d510d.png">

We should enhance our Modal / jsModal implementations so that they are capable to anchor those pop-ups and include interactive elements such as form inside them.

**Comment by ibelar** [comment]
Implemented popup  in #427 
Implemented filter/popup in grid in #448 
Can probably be closed

**Comment by DarkSide666** [comment]
Implemented.
