### ISSUE TITLE
type='money' is no longer using 'Money' column decorarot

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#414]
Previously when you specify `'type'=>'money'` for your model field, then Table/Grid/Crud would display it right-aligned and highlight negative values:

<img width="144" alt="screen shot 2018-03-22 at 13 25 58" src="https://user-images.githubusercontent.com/453929/37773106-93a93948-2dd4-11e8-856f-1afc350339e1.png">

However the current stable version does not do that:

http://ui.agiletoolkit.org/demos/crud2.php

Scroll to the right and money still has the euro symbol but lost alignment and coloring.

**Comment by DarkSide666** [comment]
Tested. Now it works.
