### ISSUE TITLE
Column alignment should be simpler

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#415]
We should make a $alignment property in TableColumn\Generic.

Currently alignment is done like this:

https://github.com/atk4/ui/blob/develop/src/TableColumn/Money.php#L14

This is quite hard to override.

**Comment by skiliton** [comment]
Hi, should this new property align the whole column or just body excluding header? 

A column can be aligned left\center\right via Html class so I think it would be logical to make $alignment property to accept these values.
