### ISSUE TITLE
Form Dropdowns do not show ... (empty selection) once something is selected

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#418]
If a Form is associated with a model, it displays hasOne References as Dropdown.

When no value for this dropdown is set, it shows an empty selection (... placeholder).
As soon as a value is selected, this option disappears. So its no possible to un-select this hasOne Reference any more.
The ... option should only disappear when the field is set to` required = true`

Empty selection available
![empty_selection_there](https://user-images.githubusercontent.com/33204878/38039530-b7fdf2ce-32ad-11e8-8dd3-196057c8cf9a.png)

And gone after something was selected
![empty_selection_gone](https://user-images.githubusercontent.com/33204878/38039553-c6afe9b2-32ad-11e8-9f16-b1333223f72e.png)

**Comment by DarkSide666** [comment]
Here is fix for that which I use in one project:

/**
 * Dropdown form field for single select by Imants.
 * Uses Semantic-UI dropdown.
 *
 * @TODO Semantic UI don't allow to unselect value :(
 *       https://github.com/Semantic-Org/Semantic-UI/issues/2072
 * Workaround #1: https://jsfiddle.net/xu4fv5n0/2/ - see slightly improved version below
 * Workaround #2: https://jsfiddle.net/hghkwkgv/6/
 */
class Form_Field_Semantic_DropdownSingle extends Form_Field_Dropdown
{
    public function getInput($attr=[])
    {
        $this->setProperty('class','ui search selection dropdown');
        $this->setProperty('name', $this->name);
        $this->js(true)->_v3()->dropdown([
            'placeholder' => 'auto',
            'forceSelection' => false, // if you find tab annoying, then put false here
            //'allowTab' => false,
            'match' => 'text',
            'fullTextSearch' => 'exact',

            // workaround for semantic ui issue mentioned above
            'onChange' => $this->js(null,'function(value) {
                var target = jQuery(this).dropdown();
                if (value!="") {
                    target.find(".dropdown.icon").removeClass("dropdown").addClass("delete").on("click", function() {
                        target.dropdown("clear");
                        jQuery(this).removeClass("delete").addClass("dropdown");
                        return false;
                    });
                }
            }'),
        ]);

        // workaround to force onChange event on initialization
        $this->js(true)->_v3()
            // set active selection
            ->closest('.ui.selection')->find('.item.active')->addClass('qwerty')->end()
            ->dropdown('clear')
            ->find('.qwerty')->removeClass('qwerty')
            ->trigger('click')
            // remove focus from field, fixes https://github.com/atk4/smbo/issues/4372
            ->closest('.ui.selection')->find('input.search')->blur()
            ;

        return parent::getInput($attr);
    }

    public function getOption($value)
    {
        return $this->getTag('option', [
            'value'     => $value,
            'selected'  => $this->value && $value == $this->value,
        ]);
    }
}

**Comment by romaninsh** [comment]
Shouldn't it be \atk4\ui\FormField\Dropdown instead of Form_Field_Dropdown ?

**Comment by DarkSide666** [comment]
It's for smbo project and extends older toolkit (amodules3) Form_Field_Dropdown, but with some modifications this trick should work on new ui field too.

**Comment by DarkSide666** [comment]
And this is for multiple value select dropdown.
```
/**
 * Dropdown form field for multi select by Imants.
 * Uses Semantic-UI dropdown.
 */
class Form_Field_Semantic_DropdownMulti extends Form_Field_Dropdown
{
    public function getInput($attr=[])
    {
        $this->setProperty('multiple',true);
        $this->setProperty('class','ui search selection dropdown'); // add small?
        $this->setProperty('name', $this->name.'[]');
        $this->js(true)->_v3()->dropdown([
            'placeholder' => 'auto',
            'forceSelection' => false, // if you find tab annoying, then put false here
            //'allowTab' => false,
            'match' => 'text',
            'fullTextSearch' => 'exact',
        ]);

        return parent::getInput($attr);
    }

    public function getOption($value)
    {
        return $this->getTag('option', [
            'value'     => $value,
            'selected'  => $this->value && in_array($value, $this->value),
        ]);
    }
```

**Comment by PhilippGrashoff** [comment]
Had a quick look into it, in the HTML code the empty selection is always there, so its definitely on the JS side. forceSelection option seems to be the one. will continue later.

**Comment by PhilippGrashoff** [comment]
Has nothing to do with forceSelection :) Here is the according sematic UI issue:
https://github.com/Semantic-Org/Semantic-UI/issues/2072

There seems to be a proper solution, lets hope it gets into the next release.
Until then, some more or less ugly workarounds seem to be the only option.
@DarkSide666 couldn't make your workaround working in newest ATK release.

**Comment by DarkSide666** [comment]
Hmmm...
https://github.com/Semantic-Org/Semantic-UI/issues/2072#issuecomment-323809270

**Comment by ibelar** [comment]
@PhilippGrashoff 

Try this to see if this work for you. 
 - Create a new Dropdown field class like below. 
 - This one add the placeholder option in dropdown module.

Then you can use this like:

```
$m->hasOne('country1', [new Country(), 'ui' => ['form' => [new MyDropDown()]]]);
```
```
class MyDropDown extends atk4\ui\FormField\Input
{
    public $rows = 2;

    public $values = [];

    public $empty = '...';

    public function init()
    {
        parent::init();
        $this->jsInput(true)->dropdown(['placeholder' => 'value']);
    }

    /**
     * returns <input .../> tag.
     */
    public function getInput()
    {
        $value = isset($this->field) ? $this->app->ui_persistence->typecastSaveField($this->field, $this->field->get()) : $this->content ?: '';

        $options = [];
        if ($this->empty) {
            $item = ['option', 'value' => '', $this->empty];
            $options[] = $item;
        }

        if (isset($this->model)) {
            foreach ($this->model as $key => $row) {
                $title = $row->getTitle();

                $item = ['option', 'value' => (string) $key, $title];
                if ($value == $key) {
                    $item['selected'] = true;
                }
                $options[] = $item;
            }
        } else {
            foreach ($this->values as $key => $val) {
                $item = ['option', 'value' => (string) $key, $val];
                if ($value == $key) {
                    $item['selected'] = true;
                }
                $options[] = $item;
            }
        }

        return $this->app->getTag('select', [
            'class'       => 'fluid search selection',
            'name'        => $this->short_name,
            'type'        => $this->inputType,
            'rows'        => $this->rows,
            'placeholder' => $this->placeholder,
            'id'          => $this->id.'_input',
        ], [[$options]]
        //
        );
        //return '<input name="'.$this->short_name.'" type="'.$this->inputType.'" placeholder="'.$this->placeholder.'" id="'.$this->id.'_input"/>';
    }
}
```

If this work then we can add a way to pass options to regular Dropdown input. 


When I use this, then the empty option become available after selecting a value.

![dropdown-with-placholder-value](https://user-images.githubusercontent.com/2204478/38571351-48d3a1c6-3cbe-11e8-9eec-05685f6c9edc.png)

**Comment by PhilippGrashoff** [comment]
@ibelar you definitely are the JS god in here, though your fix has nothing to do with magically altering some JS or so - it just works :) :) :) Just adding ANY placeholder works.
I just commited a simple solution which works flawlessly here: https://github.com/atk4/ui/pull/431
