### ISSUE TITLE
Form with related record editing

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#419]
Sometimes in the Form you want to also be able to edit related records.

Suppose you have "Inovice" model which "hasMany('Lines')". Each line contains "item_no", "item_name" as well as "price" and some other columns.

<img width="808" alt="screen shot 2018-03-28 at 20 32 58" src="https://user-images.githubusercontent.com/453929/38051866-7446133a-32c7-11e8-848e-6af8334deebd.png">

However, before you save the form, you cannot add items. This results in a difficult-to-implement UI.

My proposal is to implement this as extension to the form.

1. Implement a MultiLineForm component, which looks like a regular form, but will duplicate itself to add more and more fields.
2. Form will not submit, instead it will serialize it's fields (array of hashes)
3. On initialization form can use same JSON to pre-fill the values.

So here is what can be done:

1. Add a regular form for model for 'Invoice'
2. Add a hidden field.
3. Add MultiLineForm for $invoice->refModel('Lines');

This can be wrapped nicely into a Component that interract with form.

``` php
$form->add(['MultiLine', 'Lines']);
```

Additionally this can extend $form->save mechanics like this:

1. first $form->model is saved.
2. next $form->model->ref('Lines') is populated with supplied data. 
3. if already exists, lines will be removed/amended.

Alltogether this would be a powerful mechanism how to edit record along with it's related records. I think that multiple MultiLineForm components can be used to work on various related records.

This also makes possible to use many-to-many relations.

``` php
$form->setModel(['Invoice']);
$form->add(['MultiLine', 'PaymentAllocation', ['payment_id']);
```

See also: #351

**Comment by funyx** [comment]
I've spend some time working on scenario like this:

```
// test model a
$model_a = new \ddfsbo\Data\Model($app->db,[
    'table' => 'test_a'
]);
$model_a->addFields([
    ['name_a'],
    ['flag_a' => 'boolean']
]);
// test model b
$model_b = new \ddfsbo\Data\Model($app->db,[
    'table' => 'test_b'
]);
$model_b->addFields([
    ['name_b'],
    ['flag_b' => 'boolean']
]);
// test model c
$model_c = new \ddfsbo\Data\Model($app->db,[
    'table' => 'test_c'
]);
$model_c->addFields([
    ['name_c'],
    ['flag_c' => 'boolean']
]);

$model_c->hasOne('test_b_id',[$model_b]);
$model_b->hasOne('test_a_id',[$model_a]);
$model_a->hasOne('ModelB',[$model_b]);
$model_b->hasMany('ModelC',[$model_c]);


// include a, b, c in form fields for add/edit

$a = $app->add(['\ddfsbo\Form']);
$a->setModel($model_a,false);
$a->addField('name_a');
//$b = $a->addRef('ModelB');
//$b->addField('name_b')
$a->addField('ModelB.name_b');
//$c = $b->addRef('ModelC');
//$c->addField('name_c')
$a->addField('ModelB.ModelC.name_c');
```

that involved adding functionality to store atk4\data\Model References and their section layout within the \atk4\ui\View and also creating two new instances to interpret them 
- \atk4\ui\FormLayout\Section\Reference_One
- \atk4\ui\FormLayout\Section\Reference_Many

Goals:
- they should be traversable using the Form::model as root
- they should have ::model set with conditions (Form::model->ref($refLink))
- they should use hoooks `beforeSubmit` and `afterSave` for propagating all the data in the reference `Tree` 

What do you think of an implementation like this @romaninsh  ?
+ Model::Reference->ui['form'] might hold specific seed (which extends ..\Section\Reference_**)
+ if we implement Section\Reference_** as interfaces the seeds might inherit already existing sections like Accordion and Tabs
+ functionality like this (managing view->refs) would allow us implementation for the functionality in most of the ui components..

**Comment by skondakov** [comment]
@funyx As far as I understand @romaninsh has asked here what we need and proposes a solution to have 2 forms, but you propose to have 1 section of the standard form for fields and below another section for Reference fields. 

I like @funyx idea here. I just think for something in between i.e. extending the Form class by providing this ref editing functionality that @funyx is talking about. Maybe naming the new form something like `AdvancedForm` or `MultilineForm` .

WDYT think guys?

**Comment by DarkSide666** [comment]
Form can have multiple layout segments and if I am not mistaken then each segment can have separate model attached and all of them will be saved when form submits. Maybe that can help somehow here too?

**Comment by funyx** [comment]
yup, that's the idea..
atm the we have a layout which has a form instance within it, that form instance uses the layout's ability to addField..
the segments are attached to the form and can manipulate the model and the layout.. but thats it.. 
what i mean is that nowhere in the FormLayout i can find something with model relations (references)..
you are able to attach fields from different models via the FormFieldDecorator but the layout is trying to insert them in the layout::model, which shouldn't be the default behaviour of the component i think..
that's why my idea was to introduce atk4\data\reference to atk4\ui\view mirroring the atk4\data\model's functionality..

```
$form->addField('parent_name'); // result -> <input name="parent_name" />

// parent->hasOne('child')
$form->addField('parent.child_name'); // result -> <input name="[parent]child_name" />

// parent->hasMany('children')
$form->addField('parent.child_name'); // result -> <input name="[parent][0]child_name" />
$form->addField('parent.child_name'); // result -> <input name="[parent][1]child_name" />
```
on form submit
```
$parent_model_instance->import($submitted_data);
```

**Comment by romaninsh** [comment]
Implemented by #700

**Comment by PhilippGrashoff** [comment]
I think this can be closed as the MultiLine FormField now exists.

**Comment by abbadon1334** [comment]
referenced in #784
