### ISSUE TITLE
Grid should have "filter" support

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#420]
Filter is similar to quicksearch , but allow to specify precise fields for each value.

**Comment by ibelar** [comment]
How do you like this idea?

Let say we have dynamic popup using a form where we can generate dynamic input then we could have a filter similar to this image below.  

![popup-filter](https://user-images.githubusercontent.com/2204478/38440007-d641c646-39ad-11e8-9c16-202507c984a8.png)

Clicking 'add filter' would add another form line inside the filter dynamic popup and would query the server on input change. Users would be able to set up their filter as they want.

**Comment by romaninsh** [comment]
hm... #413 would do that quite well :) 👍

**Comment by skondakov** [comment]
I like ibelar’s idea. Looks powerfull, and easy to understand. Also they do it like this in Zoho and a lot of other places. Much better than horizontal form with all the values ...

**Comment by skondakov** [comment]
Also we should be able to add custom fields not available in the model ... can we do that?

**Comment by romaninsh** [comment]
they should be in a model, but does not necessarily be in a grid.

**Comment by romaninsh** [comment]
see also #434
