### ISSUE TITLE
AutoComplete does not work within Wizard

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#429]
When adding an AutoComplete to a Wizard step, the AutoComplete does not load any records. 
I would guess this is due to double parameter in URL, the first one indicating the Wizard step, the next one the AC itself?

This is how an URL inside the wizard looks like:`
create_tourlist.php?atk_eooadminlayout_view_wizard=0\x26_479c5d0d___tour_callbacklater_2=ajax\x26__atk_callback=1\x26q={query}`

And "normal", without a wizard: `groups.php?_5cfd31cf___to_tour_callbacklater_2=ajax\x26__atk_callback=1\x26q={query}`

**Comment by romaninsh** [comment]
possibly having same problem as https://github.com/atk4/ui/pull/425

**Comment by PhilippGrashoff** [comment]
I do not have any idea what happened, but now it works. Without me changing anything around the AutoComplete.
