### ISSUE TITLE
Grid's container to stretch 100% while remaining responsive

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#433]
Currently Grid puts table into a scrollable div. This is because sometimes grids would have too many columns and this can harm the surrounding UI by stretching it off screen. 

However if the screen is wide enough, grid should consume all the possible space:

![2018-04-12_0822](https://user-images.githubusercontent.com/453929/38688373-d26e405e-3e70-11e8-86af-461aee564044.png)

**Comment by romaninsh** [comment]
I remember now. Actually grid is 100% already, but the issue is with Admin Layout. 

https://github.com/atk4/ui/blob/develop/template/semantic-ui/layout/admin.pug#L5

https://github.com/atk4/ui/blob/develop/public/agileui.less#L98

**Comment by mvorisek** [comment]
in demos the CRUD is stretched
