### ISSUE TITLE
Use nice Modal instead of standard browser dialog for View->on() confirm option

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#437]
Currently, when setting a confirm to View->on(), e.g. `View->on('click', function() {}, ['confirm' => 'Are you Sure?'])`, a standard browser dialog is shown.

Apart from this dialog not being stylable, it has a drawback, at least in Firefox: When opening such a dialog more than once on the same page, it offers the option to surpress any further dialogs from that page, thus destroying UI functionality if a user (accidently) selects this.

A Modal would be stylable, something like the "Basic" example on https://semantic-ui.com/modules/modal.html seems nice to me.

**Comment by romaninsh** [comment]
Ideally lets think about this once nested modals are sorted #436.

**Comment by PhilippGrashoff** [comment]
Implemented in  #770
