### ISSUE TITLE
Paginator should have ability to choose items per page

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#441]
It would be very good it Paginator would have ability to choose items per page count.
Probably as dropdown - 10, 20, 50 or 100 items per page for example.

**Comment by romaninsh** [comment]
not the default one surely. We want to keep things simple if possible. Also it seems like a control for "limit" per page, not really pagination job.

**Comment by romaninsh** [comment]
something like this could work
```
$grid->add(['FormField\DropDown', 'enum'=>[10,20,50,100])->onChange($grid->jsReload(), ['ipp'=>new \atk4\ui\jQuery().value()]);
if ($_GET['ipp']) {
   $grid->ipp = $_GET['ipp'];
}
```

This can be in a separate view.

**Comment by romaninsh** [comment]
i think this was done while ago.
