### ISSUE TITLE
calling terminate() will bypass CallbackLater execution

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#443]
callbackLater promises to execute callback at a later stage, but if terminate() is invoked it won't. The reason is that callbackLater relies on app->hook for beforeOutput / beforeRender, but neither is called during terminate().

See impact: #438

**Comment by PhilippGrashoff** [comment]
See if thats still the case after #790

**Comment by romaninsh** [comment]
This has been fixed some time ago.
