### ISSUE TITLE
When entering long text in Form field, it blocks browser

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#449]
Is there any javascript event on keypress in form field (simple line input field) ?

The fact is that if you enter long text, like 5000 or more characters, then it becomes very slow after each keypress (wait like 5 seconds after keypress to see new char in input field). After about 10000 characters my browser became totally un-responsive.

**Comment by PhilippGrashoff** [comment]
Hi,

had a quick look and test to our demo page, there is no event listener attached to the inputs there. Entering 100 000 sings is no problem. 
**But**: these fields are directly added to App and do not belong to any form, maybe the form attaches an event handler.

**Comment by PhilippGrashoff** [comment]
Yes, its the form:
On http://ui.agiletoolkit.org/demos/form.php the input is within a form and has the following event listeners:

semantic.min.js:
```
function(t) {
  var n = e(this),
    i = n.closest(g),
    o = P.get.validation(n);
  o && ("change" == v.on || i.hasClass(C.error) && v.revalidate) && (clearTimeout(P.timer), P.timer = setTimeout(function() {
    P.debug("Revalidating field", n, P.get.validation(n)), P.validate.field(o)
  }, v.delay))
}
```

jquery.min.js

```
function(t) {
  return "undefined" != typeof w && w.event.triggered !== t.type ? w.event.dispatch.apply(e, arguments) : void 0
}
```



But on my PC which is pretty slow I start to feel a bit of lag after 100 000 signs input

**Comment by DarkSide666** [comment]
1. What browser did you use? I used Chrome.
2. One more thing is that i copied about 4000 chars long text multiple times in that field with Ctrl+V and then tried to add some more chars and it was slow. Maybe it revalidated each char separately of all that copied text?

**Comment by PhilippGrashoff** [comment]
1) Firefox
2) I also used CRTL+V ok course :)

**Comment by ibelar** [comment]
It should not validate unless you add a validation rule for the input field and, if so, should only validate on blur since this is what we are using in form.

```
        $this->js(true)
            ->api(['url' => $cb->getJSURL(),  'method' => 'POST', 'serializeForm' => true])
            ->form(['inline' => true, 'on' => 'blur']);
```
I am doing some test pasting char length at 5k lenght value each time and do not experience any delay. 

![demo-input](https://user-images.githubusercontent.com/2204478/38995051-fec5ebb2-43b5-11e8-963a-3c524f8137ce.png)

**Comment by mvorisek** [comment]
Closing. @DarkSide666 please retest - and note here if solved, if not, provide tests and enviroment to replicate
