### ISSUE TITLE
Grid action button should not allow double-click

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#452]
## Issue description

If you have grid with action button column like this:
![image](https://user-images.githubusercontent.com/1969119/39188883-8da3c008-47d9-11e8-9db4-df7328ab2e72.png)

And then quickly click on action button, for example, "delete", then it tries to execute that action multiple times and of course fails to delete record 2nd time.
![image2](https://user-images.githubusercontent.com/1969119/39189063-0359ead4-47da-11e8-9c76-4c52eb5637bf.png)

## Possible solution

Disable action button while particular action is executed and re-enable it again when action is finished (server response is received).

**Comment by ibelar** [comment]
@DarkSide666 -  This problem seem to occur when confirmation dialog is not use. If this is intentional, I can have a look at it.

**Comment by DarkSide666** [comment]
I personally think that any action button needs to be disabled after click until it receives response from server. Imagine, for example, action "Pay This Invoice" if it's without any confirmation dialog. If you fast click twice, then you can pay same invoice twice etc. :)

**Comment by ibelar** [comment]
fix in #453
