### ISSUE TITLE
unable to jsReload view with custom "id"

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#456]
In this case, I want to manually place the HTML ID of the HTML element:
```
$box_group = new \atk4\ui\View();
$box_group->id = 'GuestToGroup';
$content_box_container->add($box_group, 'Right');
$box_group->addClass('pmgreloadgroupchange')->on('pmgreloadgroupchange', new \atk4\ui\jsReload($box_group));
```

Now this reload fails, the Browsers JS console outputs:
```
Unable to replace element with id: atk_eooadminlayout_view_columnlayout_view_2_view_2_view_2
atkjs-ui.min.js:1:3254
```
And the long ID of course is the one this element would have if I hadnt changed the ID manually.

The corresponding JS code produced b Agile UI is:
```
  $("#GuestToGroup").on("pmgreloadgroupchange",function(event) {
    event.preventDefault();
    event.stopPropagation();
    $("#GuestToGroup").atkReloadView({"uri":"guests.php?__atk_reload=atk_eooadminlayout_view_columnlayout_view_2_view_2_view_2","uri_options":[],"afterSuccess":null});
  });
```

JsReload uses the View->name, not View->id to determine the URL. Reading through the code a bit, View->init() should actually set View->name = View->id if no name is set (which it is not until init() is called through `$content_box_container->add($box_group, 'Right');`). But its not the same...

**Comment by romaninsh** [comment]
there is method getJSID(), it should respect "id" property. Also need to review docs.

**Comment by mvorisek** [comment]
@PhilippGrashoff is it still present and can you please post a complete repro code?

**Comment by mvorisek** [comment]
no response, closing
