### ISSUE TITLE
TableColumn/Link doesn't evaluate as template

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#462]
`$table->addColumn('name', new \atk4\ui\TableColumn\Link(['details', 'id' => 'id']));`

generates link `details.php?id=id` not `details.php?id=123`

**Comment by romaninsh** [comment]
Explained here https://agile-ui.readthedocs.io/en/latest/tablecolumn.html?highlight=link#atk4\ui\TableColumn\TableColumnLink - just the place where you would express to have it.
