### ISSUE TITLE
allow to use icon in DropDown

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#473]
we only provide id/name combinations now, but why not also be able to specify icon?

![image 1](https://user-images.githubusercontent.com/453929/40131423-ddbf3c02-5931-11e8-8bfb-2f0976e70f90.png)

**Comment by ibelar** [comment]
#474 

Add to create a new Dropdown input completely (DropDownPlus) as current Dropdown implementation using select input type does not allow for displaying icon.

**Comment by romaninsh** [comment]
merged.
