### ISSUE TITLE
jsNotify->setDuration(0) message is not sown forever

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#478]
One of our clients reports that in case he set jsNotify->setDuration(0), then message still disappears. It should stay visible forever unless user explicitly close it.

I didn't try to reproduce that error, also I am not sure which version of agile ui he is using at this moment.

**Comment by ibelar** [comment]
ok I see the error. Not sure why setDuration() method changes at some point. 

Here is a quick work around: $notifier->setMissingProperty('duration', 0)

I will issue a PR fix.

**Comment by DarkSide666** [comment]
so this is fixed now?

**Comment by romaninsh** [comment]
Note - we might have a new growl messages soon to replace jsNotify :)

**Comment by ibelar** [comment]
Yes - it was fix in PR#479

**Comment by DarkSide666** [comment]
Fixed in #479 (for linking)
Then who will close fixed issues? Romans?

**Comment by romaninsh** [comment]
closing.
