### ISSUE TITLE
Demo buttons2.php reloading broken.

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#48]
A button that executes call-back to update value is broken.

**Comment by DarkSide666** [comment]
Because 
`.../demos/button2.php?atk_admin_button_3_click=callback`

returns
```
{"success":true,"message":"Hello World","eval":"$(this).text(19)"}<!DOCTYPE html>
<html lang="en">
  <head>
  ...
```

**Comment by DarkSide666** [comment]
it's because Callback is not working correctly - will try to fix that a bit later.

**Comment by romaninsh** [comment]
ok, leaving it to you. looks like exit is missing.

**Comment by DarkSide666** [comment]
need to implement $app->execute() which will unregister apps shutdown function and just echoes clean JS response.

**Comment by DarkSide666** [comment]
This is how we can "unregister" shutdown function in case we don't need to render all views when exiting.

**Comment by romaninsh** [comment]
It's possible to disable this function through a property in the $app. I don't want to accidentally unregister something else. I feel that i can implement $app->execute() easily.

**Comment by DarkSide666** [comment]
But you can disable it only on __construct(), but at that moment we probably don't know will we have normal app->run() or JS response.
