### ISSUE TITLE
Class 'atk4\ui\FormLayout\Exception' not found (in _Abstract.php)

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#480]
Hi there,
this error message is produced after I updated to newest Agile UI Version:

Error: Class 'atk4\ui\FormLayout\Exception' not found (in /var/www/html/TourManagement/vendor/atk4/ui/src/FormLayout/_Abstract.php:77)

**Comment by ibelar** [comment]
Looks like it is trying to threw an error but could not find the Exception class. 

Until we issue a fix : Try to add this line in _Abstract.php class in ui/FormLayout nest to namespace line.

use atk4\ui\Exception;

Then you should be able to see the error it is trying to throw.
This is the error that it try to tell from line 77: 'Unable to add form field', 'name' => $name, 'decorator' => $decorator, 'field' => $field

**Comment by romaninsh** [comment]
fixed.
