### ISSUE TITLE
Upload FormField: Setting placeholder via placeholder does not work

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#483]
Hi there,

setting the placeholder the "normal" way using placeholder property does not work:
`$add_attachment = $upload_form->addField('add_attachment', ['Upload', 'placeholder' => 'Anhang hinzufügen']);`

This works:
`$add_attachment = $upload_form->addField('add_attachment', ['Upload', 'caption' => 'Anhang hinzufügen']);`

**Comment by DarkSide666** [comment]
tested - works fine
