### ISSUE TITLE
Avoid multi-modals

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#487]
when you open modal from inside another modal, you have a mess on your screen. Rather than waiting for Semantic to do a miracle, I proposed this:

1. When modal is being opened, it should check if there is another modal open.
2. If yes - it will hide the old modal.
3. after modal closes - if it had previously hidden another modal, it will show it.

This should be a pretty simple fix. Do make sure it work with jsModal and Modal View.

**Comment by romaninsh** [comment]
@PhilippGrashoff / @skondakov - can you please test if this issue is fixed in "Develop" branch? I know your projects may be using nested modals, so this should help.

**Comment by romaninsh** [comment]
Also in 1.5.3 release.

**Comment by acicovic** [comment]
@romaninsh, @ibelar this works for me.

However there's a usability issue when the first modal is taller than the viewport. In that case, when the second modal closes and the first re-appears, the page is no longer scrollable. Because of this the modal gets cut and is unscrollable.

If this gets fixed I think that this issue could be closed.

**Comment by acicovic** [comment]
This is an important problem for smaller devices as it can make certain modals unusable on them. For me this would be a priority fix.

**Comment by PhilippGrashoff** [comment]
AFAIK there was an ATK solution to Multi-Modals as at that time there was no development in Semantic-UI. However, nowadays Fomantic-UI is available with looots of fixes and rapid development.
My idea would be:
@ibelar, could you have a look in this and see if the ATK solution can be replaced by native Fomantic-UI? That would probably be the preferable way to deal with this.

**Comment by ibelar** [comment]
Will be fixe in atkjs-ui v1.11.0 in pr #820 

see https://github.com/atk4/ui/pull/820/commits/9a1d85e759e0e0bea8dc300bf7ae6c306c2ec7c4

**Comment by DarkSide666** [comment]
#820 is merged now. Is this issue fixed now?

**Comment by acicovic** [comment]
I have changed my design approach so I cannot test this easily. Is there anyone who can?

If not I'll see if I can test.

**Comment by DarkSide666** [comment]
It looks that it works now.
