### ISSUE TITLE
jQuery and jUniv are not implemented

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#49]
* Can't find in code where we actually use jQuery->_include and load jquery.min.js. In demos we have hard-coded `<script src="https://code.jquery.com/jquery-3.1.1.js"></script>`
* Same story with jUniv - that's why `$view->js()->univ()->reaload()` doesn't work

**Comment by romaninsh** [comment]
This is currently hard-coded: https://github.com/atk4/ui/blob/develop/template/semantic-ui/html.jade#L7

Technically i think it's responsibility of the App class to add additional includes, because this is framework-dependent action.

**Comment by DarkSide666** [comment]
see also https://github.com/atk4/ui/issues/50

**Comment by romaninsh** [comment]
#50 and #51 overlap with this ticket, so I'll close this down.
