### ISSUE TITLE
If i set $lister->class i get nasty error. It should be handled better

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#498]
A more appropriate error should be displayed. Current error is unclear.

<img width="1116" alt="screen shot 2018-06-19 at 10 33 14" src="https://user-images.githubusercontent.com/453929/41589344-3443cb26-73ac-11e8-8b38-efb48e211e95.png">

**Comment by mvorisek** [comment]
fixed by https://github.com/atk4/core/pull/329 if the property is not present, if not present in template, error is correct
