### ISSUE TITLE
jsReload / Reload View Custom URL

### ISSUE THREAD

**Issue by jm-comentum** [atk4/ui#504]
Is it possible to pass in the URL to call the reload from? Right now I have a form going to a different URL for example:

```php
        $form->setApiConfig(
            [
                'headers' => [
                    'X-CSRF-TOKEN' => csrf_token(),
                ],
                'url'     => route('admin.user.register'),
            ]
        );
```

The form is reloaded but the URL the api is called from assumes its the URL that it was submitted too. This is not where the component should reload, so instead I am having to manually write the reloadView request for example:

```php
        $form->onSubmit(
            function (\atk4\ui\Form $form) use ($ui, $col) {

                //...

                $route = route('admin.user.list', ['__atk_reload' => $col->name], false);

                return $col->js()->atkReloadView(
                    [
                        'uri'          => $route,
                        'uri_options'  => [],
                        'afterSuccess' => null,
                    ]
                );
            }
        );
```

I have some other pain points as I am integrating with Laravel, things like auto-appending .php extensions was an issue, but I just extended the App class and removed that logic.

**Comment by romaninsh** [comment]
Each view has an url() method which provides URL to itself. 

https://github.com/atk4/ui/blob/develop/src/View.php#L1060

This relies on the App's url(). If that's working correctly then reloading should also work consistently everywhere.

I saw you progressing further pass this issue, lets close this ticket if it's not actionable.

**Comment by mvorisek** [comment]
> I saw you progressing further pass this issue, lets close this ticket if it's not actionable.

closing, feel free to test with latest version and if needed, fork demos and provide a link to a minimalistic code to what you want and is currently not possible
