### ISSUE TITLE
Link or Template Component Accept Callback For URLs?

### ISSUE THREAD

**Issue by jm-comentum** [atk4/ui#505]
Another issue that was a pain to work around is that in Laravel routes cannot have expressions in parameters of routes. For example:

```php
        $grid->addColumn(
            'name',
            ['Link', 'url' => route('admin.user.edit', ['id' => '{$id}'])]
        );
```
That route function generates `/admin/users/edit/{$id}`, but Laravel will throw an exception before the URL is generated because I cannot pass expression strings as parameters as it will try to evaluate `{$id}`. So for now I am converted `{$id}` into `[$id]`, to let Laravel resolve the URL. Once I get a string, I convert it back to `{$id}` so that ATK Template can parse it. To avoid this, it would be easier to just have a callback with the Link's item passed, so that it can return a URL string. For example:

```php
        $grid->addColumn(
            'name',
            ['Link', 'url' => function ($user) {
                route('admin.user.edit', ['id' => $user->id])]
            }]
        );
```

That way instead of passing a URL string upfront with a template string, I can get the item back and generate the URL using the traditional Laravel named routes helper function.

**Comment by joseph-montanez** [comment]
The link parameters do not work when using the TableColumn\Link class. I need the row's data to generate a URL path and not the query parameters i.e `/admin/users/22` and not `/admin/users/edit?user_id=22`:

So I can use this code to generate `/admin/users/edit?user_id=22` but there is no way to generate a URL like `/admin/users/22` unless its a template string. 
```php
new Link(['/admin/users/edit'], ['user_id'=>'id'])
``
I've gone ahead and extended the Link class to allow a callback and just pass in the row to return a string. This way I can use the Laravel route generator.

Here is an example of the callback method:

https://gist.github.com/joseph-montanez/a05961fbbd0d745277535709f11313e7
```php
        /**
         * The User Grid
         *
         * @var \atk4\ui\Grid $grid
         */
        $grid = $userListColumn->add('Grid');
        $grid->setModel(new UiUser($atkDb), ['name', 'email', 'phone', 'created_at']);
        $grid->addDecorator(
            'name',
            new Link(null, [], function ($row) {
                return route('admin.user.edit', ['id' => $row['id']]);
            })
        );
        $grid->addColumn('Actions', new Delete());
```

**Comment by romaninsh** [comment]
using template string as a work-around here is bad. Instead you should simply encode URLs in the api to strip out "user_id" and only place the numeric value of ID.

I'd be using some global route /admin/users/:user_id which replaces :user_id with the passed argument.

Other option is to grab array_values and join them through '/'.

**Comment by mvorisek** [comment]
Closing as stale, if anyone want to pursue this, feel free to sent a PR.
