### ISSUE TITLE
UI reloading feature.

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#51]
We require ability to create JS action from inside PHP that will re-load a component.

**Comment by DarkSide666** [comment]
Isn't it `$view->js()->reload()`?

**Comment by romaninsh** [comment]
exactly.

**Comment by romaninsh** [comment]
In a past version of ATK we used this: https://github.com/atk4/atk4/blob/develop/public/atk4/js/ui.atk4_loader.js

but the code is very dirty and 7 year old. We need a modern solution. Requirements would be:

 - replace indicated element with a new
 - display loader (https://semantic-ui.com/elements/loader.html) while request is in progress
 - get new content from server
 - content will include element with same ID as we are reloading
 - content may want to execute JS code on load to initialize some other components present in the loaded code (e.g. drop-down or time picker)
 - content may want to set some events (e.g. if you click OK button)
 - events associated with the OLD content or OLD main element should be dropped.

**Comment by romaninsh** [comment]
Follow up is #75
