### ISSUE TITLE
DropDown: purpose of isValueRequired=true ?

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#513]
```
$f = new \atk4\ui\Form(); // no model set

$f->addField('some_field', ....); // see https://github.com/atk4/ui/issues/512

$f->addField('format', ['DropDown', [
	'isValueRequired' => true,
	'values' => [
		'csv' => ['CSV', 'icon' => 'tag icon'],
		'txt' => ['TXT', 'icon' => 'file icon'],
	],
]]);

$f->onSubmit(function ($f) {
	var_dump($f->model->get());
});
```
related https://github.com/atk4/ui/issues/512

If I open form and don't choose value in dropdown field, then it submits empty string as value. So the question is - what's the purpose of isValueRequired property. Shouldn't it also be detected as validation rule and give error that you can't submit empty value if field is required? Anyway I see some consistency problem here.

**Comment by romaninsh** [comment]
Dark, did you look for the answer in the docs?

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/193467173-7353ac0c-28fb-471e-bfe8-273ed4f9b302.png)

fixed in https://github.com/atk4/ui/pull/826, one doc leftover to be removed...
