### ISSUE TITLE
Field error message should disappear on(change)

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#515]
If you submit and get error message of some form field, then it shows up in form (as red hint, below field) and field is marked with 'error' CSS class.

Now if I change value in that field, then error message don't disappear. It disappears only on next trying to submit form. I think 'error' CSS class and error message should disappear as soon as I change value of that field because at that moment error is no more relevant to field current value.

**Comment by romaninsh** [comment]
yes, agreed.

**Comment by ibelar** [comment]
In Form, error are clear on 'change' event, see below, so in order for the event to get fired, field need to either lose focus or be commit by user, i.e. enter for error to be clear. In our case, however, committing the field with enter also submit the form. 

```
        $this->on('change', 'input', $this->js()->form('remove prompt', new jsExpression('$(this).attr("name")')));
```

**Comment by DarkSide666** [comment]
Ok, that sounds good.
But in case of Upload field it should also clear error onUpload and onDelete events. Theoretically it should fire change event, but somehow it didn't work for me. Can you please check that too?

**Comment by romaninsh** [comment]
some solution in-between is needed. for text fields it makes sense to keep error even after focus, but remove it once you start typing.

the problem is with single-field forms which hide error once you hit enter just to show it once again. The same error is pretty much everywhere else on the internet.

**Comment by PhilippGrashoff** [comment]
Hi there,

as Fomantic-UI has a very capable form validation itself, maybe we could map our data validation into their form validation?
https://fomantic-ui.com/behaviors/form.html#/usage

Best regards

**Comment by romaninsh** [comment]
@PhilippGrashoff any JS validation can be disabled and therefore is unreliable. We still would have to check on the server, so something like that is not worth the effort.

**Comment by DarkSide666** [comment]
Is this still the issue?

**Comment by romaninsh** [comment]
probably can close. Open a more specific issue if certain fields don't drop errors after change.
