### ISSUE TITLE
Switch from Semantic-UI to Fomantic-UI

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#523]
Fomantic is a community fork of Semantic UI. Currently they have delivered 2.4 release with various improvements and are more likely to progress forward.

I propose that we use Fomantic instead of Semantic.

**Comment by DarkSide666** [comment]
If Fomantic is active project nd it doesn't break compatibility with Semantic then I agree.

**Comment by vegax87** [comment]
I agree

**Comment by hammy2899** [comment]
If you make the decision to switch to FUI please feel free to contact the fomantic team if you need anything or want to know any information.

Great to see you considering fomantic 😃

**Comment by romaninsh** [comment]
@hammy2899 we could be interested to collaborate on some themes / style packs but that would be end of 2018.. Will see how our side-project will go :)

**Comment by ibelar** [comment]
Although Fomantic seem promising, I do not see the advantage of switching now. My understanding is that there lists of features is practically the same then Semantic except for a few more feature in there 2.4 version.
I think we should wait and see what Fomantic will bring in term of new features vs Semantic and base our decision then. 
I do not see any substantial benefit of making the switch now.

**Comment by DarkSide666** [comment]
More or less I agree with @ibelar . Let's allow some time to pass and see how active and promising Fomantic will be.

**Comment by PhilippGrashoff** [comment]
I vote for Fomantic for 2 reasons:
1) they have constant development and releases. This offers us the chance to get bugs that interfere with ATK to get fixed quickly.
2) More important, each person using Fomantic UI and giving feedack will motivate the developers to keep going. Just ask yourselves what keeps you going developing ATK without directly getting any money for it. Aint a part of your motivation the people that use ATK, like it, give new input, share ideas? 

Best regards

**Comment by DarkSide666** [comment]
Good point @PhilippGrashoff

**Comment by prudho** [comment]
In case you want another reason to move to Fomantic, 2.5 was released this morning with new core components: https://fomantic-ui.com/introduction/new.html

**Comment by romaninsh** [comment]
Thanks everyone for the feedback. Glad to see 2.5 out there. Calendar is finally a significant argument in favour of fomantic.

**Comment by romaninsh** [comment]
NOTE: semantic released 2.4 (https://semantic-ui.com/introduction/new.html#/twoFour). But it seems romantic 2.5 is more important for our purposes (calendars), so does not affect our desire to change.

**Comment by hammy2899** [comment]
I just want to add we have plans to merge the SUI 2.4 release into FUI in the next few days and do another release.

**Comment by romaninsh** [comment]
Thanks @hammy2899 . For I've pushed through minor release, but I'll release 1.6. as soon as that happens 👍

**Comment by romaninsh** [comment]
@ibelar I'll need your help to prepare PR for the switch.

**Comment by DarkSide666** [comment]
Moved to Fomantic in todays release https://github.com/atk4/ui/releases/tag/1.6.0
