### ISSUE TITLE
CRUD edit form reload don't use stickyGet parameters

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#524]
Example in demo/crud.php first CRUD.

1. open demo/crud.php page.
2. sort first CRUD by phone number by clicking on column header.
3. open edit form (in this URL there still is atk4_admin_crud_sort=phonecode sticky parameter).
4. when you click Save in edit form, then it simply triggers js reload with `trigger('reload')`, which was added in CRUD view on init() phase and don't contain stickyGet arguments in it's URL. So CRUD reloads without taking current stickyGet arguments in account.

CRUD on init generates this js code and at that moment there was no stickyGet sort argument:
```
$("#atk_admin_crud").on("reload",function(event) {
  event.preventDefault();
  event.stopPropagation();
  $("#atk_admin_crud").atkReloadView({"uri":"crud.php?__atk_reload=atk_admin_crud","uri_options":[],"afterSuccess":null});
  });
```

Later on when you call `trigger('reload')` it simply runs this js reload method and reloads view without sort argument and that  way _forgets_ it.

Possible solutions:
1. add ability to call `trigger('reload', $this->stickyArgs)` and that would inject arguments in original reload URL
2. or move on('reload' , ...) somewhere else so it also reloads on each view/crud reload.

**Comment by romaninsh** [comment]
@DarkSide666 so in short - "grid reload looses current sort order" right?

**Comment by DarkSide666** [comment]
yeah :)

now fixed - sort order, paginator page and quicksearch are memorized on grid reload
