### ISSUE TITLE
CRUD->initDelete probably should also reload CRUD view

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#525]
Currently CRUD->initDelete simply hides deleted row from table view. Visually it works fine, but it is possible that when you delete some row from table, it also have some more impact on other view rows.

That's especially visible on Totals row. Totals should be recalculated when you delete row from table. And that's probably will work just fine if we also reload CRUD view on delete the same as we do that on create/update events.

@romaninsh do you agree with that?

**Comment by romaninsh** [comment]
This would mean visual element for deleting will be gone. It's always possible to create your own delete if one is not satisfied with default behaviour. Suggestion would involve a complex solution, would benefit only a small number of users.

Overall I'd like to keep current behaviour.

**Comment by DarkSide666** [comment]
ok
