### ISSUE TITLE
jsSSE can be clicked multiple times before finish

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#535]
Curent behaviour:
Currently jsSSE component can be clicked multiple times before finish.
test case: http://ui.agiletoolkit.org/demos/sse.php

Expected behaviour:
The submit button should be disabled during the processing and user should not be able to trigger the submit action twice.

**Comment by acicovic** [comment]
This is fixed by https://github.com/atk4/ui/commit/5b9563ef0b5030e0c309c15e3dd97fff451150b5 so it should be up in the next release demo. Closing this.
