### ISSUE TITLE
Grid paginator works only with Persistence_SQL

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#542]
Because `Grid->setModelLimitFromPaginator()` method uses `Model->action()` grid paginator currently is supported only for Persistence_SQL. If you use other persistence which don't support `action()` method, then you get ugly exception.

**Possible solution:**
* Generic Persistence class should have method `getRowCount()` (or something like that)
* Persistence_SQL->getRowCount() = action('count')->getOne()
* Persistence_CSV->getRowCount() = count($this->data) etc.
* Model->getRowCount() = simply call Persistence->getRowCount()
* Grid->setModelLimitFromPaginator() should use $model->getRowCount() instead of action() method.

**Comment by mvorisek** [comment]
I belive this issue is fixed
