### ISSUE TITLE
Implement "Lookup" form field decorator

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#550]
This is a replacement for AutoComplete decorator which adds a pretty cool support for filtering. 

## Basic Usage:

```
$lookup = $form->add('city_id', ['Lookup']);
$lookup->setModel(new City($app->db));
$lookup->addFilter('country');
```

Would display this:

<img width="310" alt="screen shot 2018-08-27 at 19 30 48" src="https://user-images.githubusercontent.com/453929/44678194-badc8880-aa2f-11e8-9d6a-be43bc1f6fc3.png">

We assume that City model has 'country' field, which could be imported:

```
// in City Model
$this->hasOne('country_id', new Country())->addTitle();
```

## Multiple Filters

It's possible to define multiple filters for a lookup:

``` php
$lookup = $form->add('country_id', ['Lookup']);
$lookup->setModel(new Country($app->db));
$lookup->addFilter('currency');
$lookup->addFilter('is_eu', 'EU?');  // second argument is label
$lookup->addFilter('language');
```

<img width="578" alt="screen shot 2018-08-27 at 19 33 43" src="https://user-images.githubusercontent.com/453929/44678378-23c40080-aa30-11e8-9cf2-3f7fb45565eb.png">

Filters will filter themselves out too. If you select "Yes" under EU, then you will only see Languages from the EU countries. Filters will also have option 'All' on top of them to reset a filter.

Quirk: selecting filters will only affect drop-down options. They will not reset current values. If you select "Thailand" and after that select 'Is EU' this will not reset "Thailand". That is so that implementation is simple and quick.

### Non-title field
When calling setModel, the second argument should be able to specify field to display in the drop-down:

``` php
$lookup->setModel(new Country($app->db), '[name]');
```

### Counts
When displaying drop-down values, display number of results for each value, e.g.:

```
Is EU ▼
  [ Yes (28) ]
  [ No (167) ]
   ¯¯¯¯¯¯¯¯¯¯
```

### Callbacks
Specify manual condition setting callback:

$lookup->addFilter('gdp', 'GDP', [
  '> 10000' => function($m) { $m->addCondition('gdp', '>', 10000; },
  '< 10000' => function($m) { $m->addCondition('gdp', '<', 10000; },
]);

### Calllback second argument

When specifying callback, second argument should contain selected value:

``` php
$yr = function($m, $v) {
  $m->addCondition($m->expr('year([date]) = []', [$v]));
}
$lookup->addFilter('date', 'Year', [ '2000'=>$yr, '2001'=>$yr ]);
$lookup->addFilter('date', 'Month', [ 'Jan'=>$m, ... ]);
```

This implies that we can have multiple filters with same field.

**Comment by skondakov** [comment]
This looks an interesting addon. I did not have the use for such component yet. I did integrate filtering in our ECommerce platform, but customers prefer the filtering to be done with checkboxes and do they are able to filter on more than one entry from filter category.

But this seems helpful for some basic filtering though.

**Comment by gowrav-vishwakarma** [comment]
Looks really helpful !!!

**Comment by PhilippGrashoff** [comment]
This was implemented a year ago, think we can close this?

**Comment by DarkSide666** [comment]
Not all features Romans mentioned above are supported by our Lookup field.

**Comment by mvorisek** [comment]
> This was implemented a year ago, think we can close this?

closing
