### ISSUE TITLE
In CRUD form->error() is not treated correctly

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#558]
Full example (copy in /demos folder and you can test right away):
```
<?php
require 'init.php';
require 'database.php';

$fn = function ($form)  {
    if ($form->model['numcode'] < 10) {
        return $form->error('numcode', 'Code is to small');
    }
};

// custom form
$f = new \atk4\ui\Form();
$f->onSubmit($fn);			
$c = $app->add(['CRUD', 'formDefault' => $f]);
$c->setModel(new Country($db));
```

**Issue**

When you enter small numcode value in form and try to submit, then as response from server you get:
```
{"success":true,"message":null,"atkjs":"$(\"#atk_admin_crud_edit_userform\").form(\"add prompt\",\"numcode\",\"Code is to small\");\n$(\".atk-dialog-content\").trigger(\"close\");\n$.atkNotify({\"content\":\"Data is saved!\",\"color\":\"green\"});\n$(\"#atk_admin_crud_view\").atkReloadView({\"uri\":\"a.php?atk_admin_crud=2\\x26__atk_reload=atk_admin_crud_view\",\"uri_options\":[],\"afterSuccess\":null})"}
```
As you can see - it contains _add prompt_ part, but right after that it closes dialog and reloads. It also saves that small code in data model / database.

**Expected**

It should simply throw error prompt saying that code is to small and not storing and closing anything. Like in normal Form case.

**Comment by romaninsh** [comment]
The problem here is that onSubmit sets a hook which executes twice. Probably you could break the hook. 

The proper solution for the CRUD is to see if the form has onSubmit handler already and only set a new one if it's not set.

**Comment by DarkSide666** [comment]
If we do like this
```
            if (!$this->formUpdate->hookHasCallbacks('submit')) {
                $this->formUpdate->onSubmit(function ($form) {
                    $form->model->save();

                    return $this->jsSaveUpdate();
                });
            }
```
in CRUD, then CRUDs hook is never added even if validation hook doesn't give error.

Solution:
1. require developer to add `$form->model->save()` in his custom submit hook
or
2. don't change CRUD, but implement somehow that if any submit hook calls `$form->error()`, then it automatically calls `$form->breakHook($form->error('field','message'))`. With breakHook it works fine.

**Comment by romaninsh** [comment]
how about if we suggest user to write this in his custom code as a work-around:

```
$form->onSubmit(function($f) {
  $f->breakHook( $f->error('field', 'message');
});
```

also is there a method `hookHasCallbacks` ?  Perhaps simply looking if the hook is set (isset($form->hooks['submit']) ?

**Comment by DarkSide666** [comment]
yes both versions will work (there is hookHasCallbacks method actually), but i am not sure which solution would be better.
theoretically there could be more than one submit hooks set.

**Comment by romaninsh** [comment]
my preference in fixing this is to check for the hook and if hook is not set, then crud can set it's own hook.

**Comment by DarkSide666** [comment]
But if hook is already set, then CRUD will not do anything (not save model and not close modal dialog) so developer will have to do this in his custom form. This is how developer will have to do - that's ugly.

```
$fn = function ($form)  {
    if ($form->model['numcode'] < 10) {
        return $form->error('numcode', 'Code is to small');
    }
    
    $form->model->save();
    return $form->owner->owner->jsSaveUpdate(); // owner->owner = CRUD object
};

// custom form
$f = new \atk4\ui\Form();
$f->onSubmit($fn);			
$c = $app->add(['CRUD', 'formDefault' => $f]);
$c->setModel(new Country($db));
```
