### ISSUE TITLE
Disabled fields can still be focused and edited

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#575]
**Issue:**

Disabled (read only) form fields adds CSS class `disabled` and these fields can't be clicked anymore. So if you can't click, you can't edit, right? WRONG !

You can easily navigate to such field with Tab key and edit it's value because `disabled` class is added to field container (div) and field as such doesn't have `disabled="disabled"` attribute set.

**Possible solution:**

I think simplest solution would be to add `disabled='disabled'` attribute to input fields in case their container has `disabled` CSS class. That way fields can't be focused anymore and will not be submitted when form will submit. That's what I call read_only or disabled form field and not just some gray background field with something like `on('click', function(){this.blur();});

**Comment by romaninsh** [comment]
ATK Data shouldn't save those fields because they are read-only , right? Or is it actually possible to change the values in the database?

**Comment by DarkSide666** [comment]
Data don't save them, but if form submits them (input element don't have disabled attribute), then Data will throw appropriate _validation_ exception.
