### ISSUE TITLE
Modal without any action buttons at the bottom still shows action div

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#583]
in the modal template there is the section
```
<div class="actions">
  <div>{$actions}</div>
</div>
```
To which buttons can be added via Modal::addButtonAction().

If no buttons were added, this 'actions' div is still shown. IMHO it shouldnt be there if no action button was added, its just an empty div with padding at the bottom of the modal.

**Comment by DarkSide666** [comment]
I completely agree with @PhilippGrashoff
