### ISSUE TITLE
Need ability to show form field groups as tabs in accordion

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#589]
One of our clients (LT) requested ability in UI to show form field groups as accordion tabs.
This could be useful in case of long forms which contain a lot of fields.

Currently we don't have accordion view implemented in UI so I made a little workaround:

Form layout template - based on generic.html. Only for labeled groups:
```
{LabeledGroup}
<div class="title"><i class="dropdown icon"></i>{$label}</div>
<div class="content {$field_class} field atk-form-group">
  <div class="{$width} {$class} fields">{$Content}</div>{$Hint}
</div>{/}
```

When create form do like this:
```
$f = $app->add('Form');
$f->addClass('styled fluid accordion'); // or set other accordion style here
$f->js(true)->accordion(); // initiate accordion widget
```

Here is video of how it looks by doing like i explained above: https://www.useloom.com/share/c2ef553b41924326a0a6cd81ddf20bfd

This way it kind of works, but there are numerous things to consider when fully implementing this ability:
1. Need ability to show fields in accordion tab (field group) not all in one line as in field group, but also one below another. Probably this can be done by adding some css class to field group container.
2. If form validation fails on some fields (maybe more than one), then need to expand all these accordion tabs which contain fields with errors and collapse tabs which contain only valid fields.

**Comment by PhilippGrashoff** [comment]
there is a PR linked to this issue, did it solve the problem?

**Comment by DarkSide666** [comment]
Yes I guess it's fine. It was developed and works.
Probably need some additional documentation or some tweaks, but these can be requested by using separate github issues.
