### ISSUE TITLE
Message view Icon placement is strange

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#592]
Currently template message.html is like this:
```
<{_element}div{/} id="{$_id}" class="{_ui}ui{/} {$class} {_class}{/}" style="{$style}" {$attributes}>{$Icon}
<div class="content">
  <div class="header">{$header}</div>{$Content}
</div></{_element}div{/}>
```
This means that icon is completely separated from other content and as result you get icon in one line and header text in next line (it wraps) etc.

If icon is meant for header, then my proposal is to move icon inside header block like this:
```
<{_element}div{/} id="{$_id}" class="{_ui}ui{/} {$class} {_class}{/}" style="{$style}" {$attributes}>
<div class="content">
  <div class="header">{$Icon}{$header}</div>{$Content}
</div></{_element}div{/}>
```
+ need to change Message class to (maybe) only show icon if there is header text. But not sure about this.

**Comment by ibelar** [comment]
@DarkSide666 - The way message template is done is inline with fomantic-ui (semantic-ui) message collection element. so you should see your icon next to header text and the sub text.

see: https://jsfiddle.net/ibelar/gxqadjo2/

**Comment by DarkSide666** [comment]
I guess I put that message inside wrong parent element and then it started to wrap.
