### ISSUE TITLE
Lister need {empty} ability in it's template

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#606]
Sometimes you would like to see some message if Lister doesn't contain a single item.

Like in Table template we have:
```
  {Empty}
  <tr>
    <td colspan="{$columns}">No records.</td>
  </tr>
  {/}
```
and in renderView method it removes this element if there was some rows and leaves it there if there was no rows.
In Lister we don't have that ability.

We can work around this by selecting model record count before rendering and compare it with `0`, but that would require another time-consuming SQL statement which is bad.

**Comment by PhilippGrashoff** [comment]
Why not simply iterate over rendered rows, and if count === 0 then append {Empty} content to template/{rows} is available? Thats how I do it, that saves a second DB request.

**Comment by romaninsh** [comment]
this would only be supported if lister uses row/rows tags. If lister cannot find that, it simply repeats entire template - thus combining legacy lister with legacy CompleteLister.

So Empty should only work if all tags are present.

**Comment by romaninsh** [comment]
@PhilippGrashoff yes, that's the correct implementation, however ticket talks about how to specify text to be placed inside {rows} if no rows were found. 

The other idea is this:

```
{rows}
{row}
bla bla one row 
{/row}
no rows found!
{/row}

**Comment by DarkSide666** [comment]
@PhilippGrashoff yes that's exactly how it's implemented in Table and should be implemented in Lister.

If we have `{rows}` and `{row}` tags in template, then for consistency we can simply use `{empty}` tag there like it's done in table template.

Issue is with lister templates which don't contain rows and row tags. In that case all template is treated as one `{row}`.

Well there are two options:
1. we still can add `{empty}` tag somewhere (no matter where) in template and take it out before starting to render it.
2. we  don't support empty tag in such templates at all.

Which of these two options do you like more?

**Comment by romaninsh** [comment]
I prefer option #1. 

Also - thinking about it , reliance on {row} detection makes it hard for us to have column with name "row", isn't it? Perhaps we should have an option $completeTemplate = 'true/false/null' and if set to null, detect {row}

**Comment by DarkSide666** [comment]
Not sure what you mean by columns here and I think there is no need for additional property.

I will go with option 1 then and let's see how it works.
