### ISSUE TITLE
Grid relies on Column_Checkbox, but there is no such column class

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#61]
Grid relies on Column_Checkbox, but there is no such column class in UI.
https://github.com/atk4/ui/blob/develop/src/Grid.php#L148

**Comment by romaninsh** [comment]
This may be already resolved

**Comment by DarkSide666** [comment]
commented here: https://github.com/atk4/ui/blob/develop/src/Table.php#L151

**Comment by DarkSide666** [comment]
closing
