### ISSUE TITLE
JS Libraries we could use...

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#62]
We need to find a good JavaScript libraries to:

 - reloading parts of page through AJAX. jQuery.load() is a start, but we need loading progress, time-out handling and working with duplicate DIVs (replacing element itself not just it's content)
 - manipulating URL, so when AJAX load completes, we can update the URL as well as handle "back" button properly.
 - request authentication errors. Intercept jQuery requests and if they contain "non-authorized", then display message 'you have been logged off'

**Comment by romaninsh** [comment]
URL building: http://medialize.github.io/URI.js/, old atk we used our own URL builder.

**Comment by acicovic** [comment]
Is this still relevant or it can be closed?
I can't close issues so I'll be asking from the poster to do so.

**Comment by romaninsh** [comment]
we adopted vue.
