### ISSUE TITLE
CRUD and read_only field

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#620]
In latest release the behaviour of read_only fields in CRUD form create/update form change.

In previous released these fields was excluded from form. Currently these fields are partialy visible in the create/update form - the inputs are not presented, but the labels are still there. Is this a bug?

**Comment by romaninsh** [comment]
possibly related to #603

**Comment by mvorisek** [comment]
> 
> 
> possibly related to #603

Probably not related, even standard Input field is affected. Mark any field in CRUD model as read_only and the field label will be still visible in the create/update form.

**Comment by DarkSide666** [comment]
Why did you close this issue?
I agree about create form - readonly fields are useless there, but in update form they can be useful. For example, to show some calculated expression field etc.

**Comment by mvorisek** [comment]
I have solved it locally, but I will reopen this issue and submit the solution as a PR

**Comment by DarkSide666** [comment]
I am a bit lost now. You closed/deleted #622 and now what to do with this issue?

**Comment by romaninsh** [comment]
@mvorisek you don't need issue to submit PR. Open new issue with more details if there is still an issue.
