### ISSUE TITLE
Modal dialogs have <div dimmer which breaks rounded corners

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#621]
Full description here: 

https://github.com/fomantic/Fomantic-UI/issues/308

Possibly can be fixed in atkjs

**Comment by lubber-de** [comment]
This is a fomantic issue and i fixed this by https://github.com/fomantic/Fomantic-UI/pull/310

**Comment by acicovic** [comment]
@romaninsh this seems to be fixed?
I that case I think we should close the issue.

**Comment by PhilippGrashoff** [comment]
closing as this was fixed by Fomantic
