### ISSUE TITLE
FormField_DropDown selects all fields from database even if uses only title field

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#629]
See line: https://github.com/atk4/ui/blob/fa52a365d6806898643452f08afcffda12186f1e/src/FormField/DropDown.php#L182

It runs select of all model fields in database, but uses only title field (or id field if title field doesn't exist). This is not optimal.

Possible solution:
```
$m = clone $this->model;
$m->onlyFields([$m->id_field, $m_title_field]);
foreach ($m as $key=> $row) {
    ....
```

**Comment by PhilippGrashoff** [comment]
Thinking about the possibility to add an icon to the dropdown: currently this is only possible when defining values property, not when iterating a model. Could be nice to have this functionality for model iterating, too using a callback. This callback would usually use other fields than id_field and title_field... Just a thought

**Comment by DarkSide666** [comment]
Yeah having callback there would be nice to be able to create your own dropdown item template.

**Comment by PhilippGrashoff** [comment]
something like
```
if (isset($this->model)) {
	foreach ($this->model as $key => $row) {
		if(is_callable($this->modelRowRenderCallback)) {
			$options[] = call_user_func($this->modelRowRenderCallback, $row);
		}
		else {
			$title = $row->getTitle();
			$item = ['div', 'class' => 'item', 'data-value' => (string) $key, $title || is_numeric($title) ? [(string) $title] : []];
			$options[] = $item;
		}
	}
}
```

**Comment by romaninsh** [comment]
I think it should simply fetch "id" and "title" field. Nothing else (maybe system fields, not sure)

**Comment by DarkSide666** [comment]
Yes - id and title_field is enough in most cases, but if you want to add icon in dropdown, then it would be good if you could select it also and use it in dropdown item template.
`select id,name,type from table`
and in dropdown item something like this:
```
$item = [
    'div',
    'class' => 'item' . ($type=='car' ? ' icon car' : 'icon foo'),
    'data-value' => (string) $key,
    $title || is_numeric($title) ? [(string) $title] : []
];
```

**Comment by PhilippGrashoff** [comment]
How about this:
1) if no custom line render function is defined, just use id_field and titile_field
2) if custom line render function is defined, load the complete model to give atk users full flexibility to adjust dropdown options

**Comment by DarkSide666** [comment]
that sounds good
