### ISSUE TITLE
dev-develop branches should require other dev-develop branches for all atk/* repositories

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/ui#641]
dev-develop branch should always point to other dev-develop branch or it gets conflicts while developing on the nightly build system

example:
I was trying to include login module in atk/ui and:

Let's assume I am creating an application and since right-now a lot in development is going on in ui/data develop branches and these branches are my best option to include in my composer requirements.

Now, with a dev-develop requirement of ui /schema and login, the composer gets conflicts in minimum stability requirements.

So my requirements as follows

```
"minimum-stability": "dev",
"require": {
        "myapp/namespace":"dev-master",
        "atk4/ui": "dev-develop",
        "atk4/login": "dev-develop"
    },
    "require-dev": {
        "atk4/schema": "^1.1.1",   <= or even dev-develop both giving errors
        "phpunit/phpunit": "<6",
        "phpunit/phpcov": "^3.0",
        "codeclimate/php-test-reporter": "*",
        "behat/behat": "^3.4",
        "behat/mink-extension": "^2.2",
        "fzaninotto/faker": "*"
    }
```

never gets installed/updated with composer
Opened an issue there also.

**Comment by gowrav-vishwakarma** [comment]
For now, updating composer and treating dev-develop as recent branch solves the problem 

```
"require": {
        "my/repo":"dev-master",
        "atk4/ui": "dev-develop as 1.6.1",
        "atk4/login": "dev-develop"
    },
```

**Comment by DarkSide666** [comment]
Duplicate with https://github.com/atk4/login/issues/16

**Comment by romaninsh** [comment]
It's recommended that you always use stable versions in your application. If you have to use develop - then use "..as.." as described.

The reason why we have "dev-develop" in develop branch is because Travis won't be picking latest dependencies. This is only relevant for the 4 core repositories. Everything else is using stable branches (add-ons and projects).
