### ISSUE TITLE
With Fomantic UI 2.7.2 jsNotify hides at once

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#647]
Hi,

as we will surely update to the newest Fomantic UI version, I just noticed trying it that jsNotify hides at once no matter what value I set the duration to. Switching back to the currently used 2.6.4 solves the problem.

**Comment by romaninsh** [comment]
@PhilippGrashoff Can you capture rendered HTML, create a demo on jsFiddle and post it to Fomantic github while keeping link to this article. They usually look into issues quickly.

**Comment by PhilippGrashoff** [comment]
Hi Romans,
I would have done that already, but it seems Notify is an atk thing, didnt find notify in Fomantic.

**Comment by PhilippGrashoff** [comment]
I actually like the Toast they introduced very much. Its quite similar to jsNotify. Maybe its an Idea to ditch jsNotify in future versions and use the Fomantic-UI native toast instead? The more native Modules we use the less UI maintenance we will have.

**Comment by ibelar** [comment]
@PhilippGrashoff - Please note that Fomantic Toast module is already implement in atk 
http://ui.agiletoolkit.org/demos/toast.php

**Comment by PhilippGrashoff** [comment]
Yeah I know, all the more reason to use Toast as Notify :)

**Comment by ibelar** [comment]
fix in #673

**Comment by DarkSide666** [comment]
@PhilippGrashoff can you confirm that this is fixed now?

**Comment by romaninsh** [comment]
re-open if problem persists.
