### ISSUE TITLE
This must be in RecursiveRender

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/ui#661]
https://github.com/atk4/ui/blob/79337b47b03564564162b54eb01bec347288d7d5/src/CRUD.php#L112

As a core for ATK goal, we must be able to alter functionality until it is rendered. 
Current method do not allow us to do some logic later on and remove the CRUD functionalities like add/edit/delete.

It should be in recursiveRender like

=========
public function setModel(\atk4\data\Model $m, $defaultFields = null)
    {
        if ($defaultFields !== null) {
            $this->fieldsDefault = $defaultFields;
        }

        parent::setModel($m, $this->fieldsRead ?: $this->fieldsDefault);
        $this->model->unload();
        return $this->model;
    }

    function recursiveRender(){

        if ($this->canCreate) {
            $this->initCreate();
        }

        if ($this->canUpdate) {
            $this->initUpdate();
        }

        if ($this->canDelete) {
            $this->initDelete();
        }

        return parent::recursiveRender();
    }
======

**Comment by gowrav-vishwakarma** [comment]
If it sounds okay, I can create a pull request

**Comment by romaninsh** [comment]
problem is that initCreate adds actions and buttons and if it's not called during "INIT" then you won't have access to them after init.  Also if you add more buttons they appear BEFORE the create button, which is inconvenient. 

I tried this approach before and wasn't happy with result. Using similar logic you could say - let's not add "save" button to a form until Render and that also would be quite bad.

**Comment by romaninsh** [comment]
Also I don't see what is the problem other than "concept".

**Comment by gowrav-vishwakarma** [comment]
1. If we move it in the recursive render, things are working
2. Yep, Agreed, Add button comes in back but that can be brought first by some order
3. The concept is THE MOST important.

So, in previous versions what came a lot handy was
$crud->isEditing(null/'add'/'edit'){
$crud->form->getElement .... 
}

etc

now I am creating a controller that is supposed to add/change some functionality in CRUD like remove "add button" or remove edit/delete in some conditions (Like we were used to do in 4.3 with renderRow hook)

**Comment by romaninsh** [comment]
Closing for now. Might be idea for alternative CRUD. Existing one is quite stable.
