### ISSUE TITLE
Incorrect ids for elements

### ISSUE THREAD

**Issue by pkly** [atk4/ui#667]
I'm writing something bigger, using ATK as the ui toolkit, since I found that it was nice enough.
ATK kind of takes over GET, so I added some code, as following:

```php
// Tools.php
public static function getGETAdmin(bool $clearATK = false): array {
    $args = [];
    foreach ($_GET as $key => $item)
        if ((!$clearATK || mb_strpos(mb_strtolower($key), 'atk') === false) && $key !== 'json')
            $args[$key] = $item;

    return $args;
}
```

```php
// \atk4\ui\View.php

public function jsURL($page = []) {
    return $this->app->jsURL($page, false, array_merge(array_merge($this->_getStickyArgs($this->name), $this->stickyArgs), Tools::getGETAdmin(true)));
}

public function url($page = []) {
    return $this->app->url($page, false, array_merge(array_merge($this->_getStickyArgs($this->name), $this->stickyArgs), Tools::getGETAdmin(true)));
}
```

Said code helped me easily push my arguments (which sit in the url and were getting lost on ATK refreshes and js requests), but then I got an element with an id/name like: `_8831cbe5___2_popup_button`, this happened inside a popup which was attached like this

```php
// Custom Element
// \My\Ui\FilePreview.php

public function init() {
    $menuButton = $this->add(['Button', 'icon' => 'ellipsis vertical', 'ui' => 'button compact mini basic right floated']);
    $popupMenu = $this->add(['Popup', $menuButton])->addClass('compact possible-wide');

    $this->registerButton = $popupMenu->add(['Button', self::ts("Register file for usage"),
            'ui' => 'button fluid compact mini ' . (!empty($this->file->getDbInfo()) ? 'hide-me' : '')]);
}
```

I don't really understaind why the "registerButton" suddenly got a way different id/name, that doesn't include the 'atk' string, and why it has that set of numbers.
I've looked around the ContainerTrait and various other places, but I've found nothing that should cause this to happen. The name simply appears.

This is on PHP 7.1 / ATK4UI 1.6.2 (Modified to allow for proper localization)

This element is contained within a modal (elements added with `set()`), then another dummy element (elements added with regular `add()`)

If a test case is necessary please let me know and I'll do my best to reproduce it.

If it's possible, how can I list all names/ids for elements in the whole application? I could remove things that way and it'd be better, I believe.

Is this caused by the fact my class is not inside the `\atk4\ui` namespace?

**Comment by DarkSide666** [comment]
Why do you need this at all?
Can't you just use `$app->stickyGet('your_get_parameter')` to make it _sticky_ and in that case it should be memorized in all URLs you generate.

**Comment by pkly** [comment]
I don't like this approach, as it limits what I do and what kinds of parameters I pass. It's rather irritating to have to remember to keep track of everything I've ever wanted to use, in case I need it, otherwise it'll simply get erased.

Shouldn't it be too hard to make it available to list all ids to allow for this, should it?
I've found that doing it this way made it easier for me to simply add code, instead of going back and looking around for a single spot where I missed a call to `stickyGet`

**Comment by romaninsh** [comment]
@pkly Thanks for trying ATK. I do not really understand the problem you are facing. What it is that you try to achieve and why you want to meddle in the GET arguments?

To answer your question about the names - longer names are automatically folded, which is a mechanic of ATK Core trait.

You could recursively walk through all the objects of ATK (those that implement container) and you should be able to collect their names.

Finally - if something is "hard" in ATK then that's an indication of a wrong approach.

Closing this issue as it does not describe a problem. You can open another one with a description and a test-case. For questions please use the forum.
