### ISSUE TITLE
App->url() have hard-coded .php extension

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#68]
`App->url()` have hardcoded `.php` extension for pages. Sometimes we want to use different extension, `.html` for example.

**Comment by romaninsh** [comment]
App->url() must be redefined by a host framework / application, so that's a normal behaviour.

**Comment by DarkSide666** [comment]
Workaround is to use Template formatter for grid, not Link formatter:
```
$grid->addColumn('name', new \atk4\ui\Column\Template('<td><a href="page.html?id={$id}">{$name}</a></td>'));
```
