### ISSUE TITLE
😈 - I'll document your PR if you link it in this issue

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#683]
ALRIGHT - I'll update documentation with all the missing bits myself. I just need to know what's missing, so **HELP ME FIND MISSING BITS**:

 - [ ] guide on how to create VUE component (internal and external)
 - [ ] jsFunction not documented (#70)
 - [ ] Full documentation on MultilineForm (#700)
 - [ ] How to customize jsSearch (https://github.com/atk4/ui/pull/707)
 - [ ] Explain how to use custom routing (https://github.com/atk4/ui/pull/706)
 - [ ] $form->addFields() is now possible (https://github.com/atk4/ui/pull/714)
 - [ ] https://github.com/atk4/ui/pull/643/files#diff-4b67e9492f67665780c2571ad53ebb68R102

See also: https://github.com/atk4/ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22Documentation+%3Abooks%3A%22

**Comment by acicovic** [comment]
Hi Romans,

https://agile-ui.readthedocs.io/en/latest/core.html

Theres a "documentation coming soon" under "Virtual Page" section on the left. I don't know if this should be removed or if there's documentation to write there.

By the way, if I find typos and fix them, would you accept those as pull requests?

**Comment by acicovic** [comment]
The page https://agile-ui.readthedocs.io/en/latest/quickstart.html leads to the money lending tutorial.

The tutorial's part 2 is marked as coming soon.
https://github.com/atk4/money-lending-tutorial/blob/step2/tutorial/en/step2.md

The application itself seems incomplete (for example nothing happens when clicking the edit button).

**Comment by DarkSide666** [comment]
@acicovic if you find any issues then please report them or even better fix them and make pull request. Of course we will gladly accept it and merge in if it's correct.

**Comment by acicovic** [comment]
See related PR #692 and let me know.

**Comment by romaninsh** [comment]
awesome. merged!

**Comment by acicovic** [comment]
Related issue: jsFunction class is not documented. #70

**Comment by acicovic** [comment]
Related issue: #180

**Comment by acicovic** [comment]
Also #342

**Comment by DarkSide666** [comment]
About #180 we planned to more or less refactor that total calculation implementation and I think that's why I didn't document it yet. That was quite some time ago :)

**Comment by romaninsh** [comment]
from @ibelar: @PhilippGrashoff - did you try - $form->formConfig = ['fields' => ['email' => ['empty', 'email']]];

**Comment by romaninsh** [comment]
i think it's not serving the purpose.
