### ISSUE TITLE
RawGit is shutting down. The latest example defaults to RawGit shared resources.

### ISSUE THREAD

**Issue by Steveorevo** [atk4/ui#685]
Follow the initial example on the readme.md. Note the header javascript and css references to:
```
<script src="https://cdn.rawgit.com/atk4/ui/1.6.5/public/atkjs-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/atk4/ui/1.6.5/public/agileui.css">
```

Suggest changing the links to a **_trusted_** cdn or pull locally.

**Comment by DarkSide666** [comment]
All info in http://rawgit.com.

{quote}
GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
{quote}

**Comment by acicovic** [comment]
I can update the docs if someone else takes care of the rest.
