### ISSUE TITLE
App->url() can't reference current page

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#69]
`App->url()` can't reference current URL.

What if I want to just refer current URL and add some additional GET arguments.
For example, this won't work to get current page
```
$url = $app->url([null, ['new_id' => 123]]);
```

**Comment by romaninsh** [comment]
Again - App does not do any black magic to detect current page, so it cannot do it reliably. Just like #68, method url() must be re-defined by the host application.

Probably this ticket can remain open, because we can figure out name of executed script and use it if 'null' is used with the url.

**Comment by DarkSide666** [comment]
Also see `Paginator->url()` method

**Comment by romaninsh** [comment]
See also #115

**Comment by romaninsh** [comment]
Fixed in #115
