### ISSUE TITLE
addFields() doesn't work for forms

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#695]
According to Form documentation (https://agile-ui.readthedocs.io/en/latest/form.html) we can have the following code:

```
$form->setModel(new User($db), false);
$form->addFields(['name', 'surname']);

$gr = $form->addGroup();
$gr->addFields(['city', 'country']);
```

However, none of those work for me and I see no addFields() function in _Abstract.php. This means that we should either remove those examples from the documentation or implement the feature. I would propose to implement the feature because it helps us to write concise code.

Any takers? :)

**Comment by DarkSide666** [comment]
Yes this sounds good. I will add that shortly.

**Comment by acicovic** [comment]
Great!

**Comment by acicovic** [comment]
Unless there's already a better way to do this, I think this should also be implemented for tabs, accordions and addGroup(). This reduces code. For example:

```
$tabs = $form->layout->addSubLayout('Tabs');
$tabReservation = $tabs->addTab('Réservation');
$group = $tabReservation->addGroup(['width'=>'three'])
$group->addField('date_from');
$group->addField('date_to');
$group->addField('status_id');
```
Would become:
```
$tabs = $form->layout->addSubLayout('Tabs');
$tabReservation = $tabs->addTab('Réservation');
$tabReservation->addGroup(['width'=>'three'])
    ->addFields(['date_from', 'date_to', 'status_id']);
```

Currently I have a form with many groups so for each group I use $tabReservation->addGroup(['width'=>'three'])->setModel($grid->model, ['date_from', 'date_to', 'status_id']); so I can set all fields in one line but it's a really ugly hack. @DarkSide666 what do you think of this?

**Comment by DarkSide666** [comment]
Yes good point. I will reopen issue and implement that soon.
