### ISSUE TITLE
Grid HTML entity display problem

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#709]
Hi,

I am fetching data from my database and displaying it into a Grid. One of the fields contains the ampersand HTML entity. But the grid displays it as text.

![image](https://user-images.githubusercontent.com/23142906/57696575-b4437f00-7659-11e9-8ca7-3e54aa1cba07.png)

**Comment by DarkSide666** [comment]
It's kind of _as expected_ because grid should encode value to avoid "bad hackers" :)

But in this case it looks that for some reason it encodes ampersand twice maybe?
Do you have `&amp;` in your database or `&` ?

**Comment by acicovic** [comment]
In my database it's `&amp;`. So this is expected behavior?

**Comment by DarkSide666** [comment]
sure. if it's like that in your database then it will show the same on screen. Text is sanitized to avoid any HTML entities.

Probably you can use TableColumn\Template decorator to show it like HTML (without sanitizing) if you're really sure about your data.
