### ISSUE TITLE
Demo problems

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#724]
Hello, the following demo pages don't work.

https://ui.agiletoolkit.org/demos/form-section.php
https://ui.agiletoolkit.org/demos/field2.php

**Comment by acicovic** [comment]
Related to #114?

**Comment by DarkSide666** [comment]
@acicovic What exactly is not working in these pages? Currently I can open both of them and all looks fine.

**Comment by acicovic** [comment]
@DarkSide666 I was getting some kind of 404. This is no longer the case so I'm closing this.
