### ISSUE TITLE
\atk4\ui\CheckBox does not contain the required declaration for \atk4\ui\Exception

### ISSUE THREAD

**Issue by pkly** [atk4/ui#730]
Add the following line to \src\FormField\CheckBox.php

```php
use atk4\ui\Exception;
```

Otherwise if the `->set()` function is called incorrectly an error is printed saying:

Error: Class 'atk4\ui\FormField\Exception' not found (in /srv/apache/www/virtual_git/wego2-x/lib/atk4/Ui/src/FormField/CheckBox.php:64)

**Comment by abbadon1334** [comment]
thanks @pkly
