### ISSUE TITLE
ui breaks after update to recent develop branch

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/ui#732]
Hi,

I recently updated to dev-develop and found that a complete running system is broken now.  Attaching image for further digging. as you can see it now using "Object Illuminate\Support\Facades\View" as an object, while it should use \atk4\ui\View I guess.

Since Atk is used with Laravel here or can be used with any other framework, this looks an Urgent issue to me.

here is an image for review
![Image of Yaktocat](https://pasteboard.co/IhSNmza.png)

https://pasteboard.co/IhSNmza.png

For now, I have to revert back to the previous version.

**Comment by DarkSide666** [comment]
This looks like some namespace issue in Laravel integration repository.
Please try to track it down.

**Comment by romaninsh** [comment]
@gowrav-vishwakarma please re-test and if recent changes in namespaces not solve it, re-open.
