### ISSUE TITLE
App->normalizeClassNameApp doesn't support 2nd parameter - $prefix

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#740]
Currently atk4\core\FactoryTrait calls $app->normalizeClassNameApp() method and pass 2nd $prefix parameter, but \atk4\ui\App->normalizeClassNameApp() method doesn't support this argument and completely ignores $prefix.

This is bad and can be seen, for example, if you get some exception and it calls App->caughtException() which tries to initLayout('Centered').

Fix is here: https://github.com/atk4/ui/pull/739

**Comment by romaninsh** [comment]
I think this issue is old now. @DarkSide666 can you re-open if you can't make it work?
