### ISSUE TITLE
add ContainsOne support for Form

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#754]
Showing up as a group of fields (like Address)

```
$client->containOne('address', [Address::class, 'editable'=>true]);  

$client->ref('address')['street'] = 'ABC';

$client->save(); // also saves address.
```

**Comment by romaninsh** [comment]
On meeting - agreed that this would be insanely useful.

**Comment by PhilippGrashoff** [comment]
This was integrated with #784, so I think we can close this

**Comment by acicovic** [comment]
@PhilippGrashoff ContainsOne would need to enforce a minimum of 1 row within Multiline. Currently the code doesn't seem to include this. See #809

**Comment by acicovic** [comment]
@PhilippGrashoff in a scenario of an optional containsOne (may contain one or none) max 1 is enough so you are right. I was talking about a mandatory containsOne scenario (contains exactly 1) but I'm not sure ATK provides this anyway.

**Comment by mvorisek** [comment]
duplicate of https://github.com/atk4/ui/issues/1860
