### ISSUE TITLE
Data loss: 0 as textarea value

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#755]
I have a field in my model which shows as a textarea and is of type TEXT in a MySQL backend.

When you add a value of 0 into the textarea, it stores it in the database. However, when the textarea is reloaded it is empty. If the user doesn't notice this and saves the record, data loss occurs because an empty string is saved over the 0.

This issue might also occur in text inputs but I haven't tested it.

**Comment by acicovic** [comment]
The correct behavior would be to display the 0.

**Comment by acicovic** [comment]
This should be reopened because the PR was reverted due to #760 issue.

**Comment by DarkSide666** [comment]
fixed by https://github.com/atk4/ui/pull/783
