### ISSUE TITLE
Form HTML output in textareas

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#760]
On the latest UI dev update, HTML code is inserted in textareas instead of being rendered as FUI controls. For example that's the content that might be in a textarea:
```
</div>

</div>
<div class=" field">
  <label for="atk_admin_studentform_generic_generic_4_personality_type_id_input">Personnalité</label>
<div id="atk_admin_studentform_generic_generic_4_personality_type_id" class="ui fluid search selection dropdown  " style="" >
```

**Comment by acicovic** [comment]
I have no idea how and why, but this works now. Closing this and will re-open if I notice it again.

Thanks!

**Comment by acicovic** [comment]
This happens only when the form is in create mode. If a record has been loaded all fields display correctly.

**Comment by acicovic** [comment]
The cause is #756

**Comment by DarkSide666** [comment]
Generated HTML in /demos/form.php looks good to me:

```
<div class=" field">
  <label for="atk_admin_tabs_tabssubview_form_2_generic_description_input">Description</label><div id="atk_admin_tabs_tabssubview_form_2_generic_description" class="ui  input" style="">
<textarea name="description" type="text" rows="2" placeholder="" id="atk_admin_tabs_tabssubview_form_2_generic_description_input">0</textarea>
</div>

  
</div>
```

**Comment by acicovic** [comment]
I didn't have the time to test this further to find the cause but reverting TextArea.php solves the specific issue for me.

**Comment by acicovic** [comment]
Note that I'm speaking about latest develop version, not 1.7.1

**Comment by romaninsh** [comment]
I can confirm this too.

**Comment by romaninsh** [comment]
i checked the PR and I can't immediatelly think of a reason why this could happen. Looks like tag not closed.

**Comment by acicovic** [comment]
This PR has been reverted so I'm closing the issue

**Comment by DarkSide666** [comment]
Related issues: #755, #781
I still can't think of reason why this change could possibly change HTML markup. So I don't think reverting this was good choice. Probably issue is somewhere else - maybe getTag method or something?

**Comment by acicovic** [comment]
Reverting this did solve the issue but I wonder about that as well.

**Comment by acicovic** [comment]
Important finding: this issue occurs for textareas which try to fill from a null value in database. Are you able to reproduce?

**Comment by DarkSide666** [comment]
Will be fixed by https://github.com/atk4/ui/pull/783/commits/8ada11c8f068dade02a19aedaec78b0315159d96

**Comment by DarkSide666** [comment]
fixed by https://github.com/atk4/ui/pull/783
