### ISSUE TITLE
required StickyGet arguments

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#779]
Currently if you define stickyGet argument and it wasn't supplied, then it is simply null. 

How about if we declare that some sticky Get arguments are required and framework would ask user to enter them if they are missing? I'm thinking it could use centered layout and a form for that.

**Comment by DarkSide666** [comment]
No I don't think it's good. GET arguments are something which should be supplied by URL not user input.

Also security aspect - if app will ask for missing arguments, then user will know which arguments this page requires and can try to guess them.

**Comment by gowrav-vishwakarma** [comment]
Totally agree with imants.

**Comment by abbadon1334** [comment]
Agree to Imants too, but i want to know what's the reason.
One of the reason of choosing atk is because we always have the control of the workflow, if at some point this flow is broken from some automation we can lose control, which is not good, ask for user to insert some missing data is like an Exception on the flow.
I think if the dev want this, it will implement it by itself.

**Comment by romaninsh** [comment]
The reason is to make it easy to ask user for required arguments if page is opened directly. 

For example, consider this:

``` php

$app = new MyApp();

$app->add('Table')
    ->setModel('Orders')
    ->addCondition('item_code', $app->stickyGet('item_code', ['ask'=>true]));

```

Page would ask for a code, then once entered proceed with normal render. 

This is VERY SIMILAR to how authentication works. Well, just wanted to hear thoughts on this. It can be also implemented as an add-on.

**Comment by DarkSide666** [comment]
If it's as separate switch `ask=>true` then maybe that can be implemented, but still don't think it's useful.
Maybe as add-on, but not in a core repo.

**Comment by romaninsh** [comment]
ok, thanks for your feedback everyone!

**Comment by romaninsh** [comment]
unpopular proposition, so closing it down.
