### ISSUE TITLE
CRUD Delete button doesn't work

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#785]
CRUD delete button results in "Uncaught TypeError: $.atkConfirm is not a function" JS error. This is in latest development release. Worked correctly some time ago.

**Comment by acicovic** [comment]
@abbadon1334 provided built files which resolves the problem so I'm closing this.

**Comment by paranoiasystem** [comment]
I have the same issue, I have write about this on gitter. How I can fix this? this is my composer.json file
```
{
    "require": {
        "php": ">=7.2.0",
        "atk4/ui": "dev-develop as 1.7.1",
        "atk4/login": "dev-develop@dev",
        "atk4/schema": "dev-develop as 1.1.6"
    },
    "minimum-stability": "dev",
    "prefer-stable": false,
    "autoload": {
        "psr-4": {
            "": "src/",
            "Model\\": "Model/"
        }
    }
}
```

**Comment by acicovic** [comment]
1. Download this: [js-compiled.zip](https://github.com/atk4/ui/files/3478342/js-compiled.zip)
2. Unzip the files and put them in a public directory 
3. In your App add the following line:
    `$app->cdn['atk'] = 'http://your.path'`

This way the app will load ATK assets from : 
http://your.path/agileui.js
http://your.path/agileui.css
http://your.path/atkjs-ui.min.js

Note: this currently works for me but might brake in a future development version.
