### ISSUE TITLE
Suggestion: Issues cleanup

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#787]
Hi,

I think that our repository has too many open issues. This might give the impression of a project that has many bugs and that's not being cleaned up or looked after (which is not the case at all). For a project that has 240 closed issues, 145 open issues is a lot.

Some of the aforementioned issues might already be resolved, others have not received response or closure from the original poster, and others might be out of scope, outdated or wontfix. They also might be questions which should be a better fit for the Gitter channel.

I think that most of the issues that fall within the above categories should be closed so we can focus on the stuff that is important. Focusing on 50 issues is far easier than having a list of 150 issues and not knowing where to start. Closing and re-opening if needed is better than leaving open indefinitely.

I can start reading some issues and proposing closure if I think that the thread should be closed. @romaninsh, @DarkSide666 let me know if you agree. If there's anyone who wants to help let's share the work.

Thanks!

**Comment by PhilippGrashoff** [comment]
Hi Alex,

a thought I share since at least a year :) 150 sounds like a terribly unstable software... I really like the idea.

Especially in UI, many things might have been implemented differently by now, or there is new ways to solve a problem, as there have been so many additions lately.

**Comment by DarkSide666** [comment]
@acicovic I would simply love that !!! Please start with older ones - I bet that 90% of them can be closed.

**Comment by romaninsh** [comment]
Will love to help out, but we should probably tackle a handful of old issues every week during our meeting and decide what should be done with them.

Many of them are not issues but just "wishes", we can probably find a better place for them, i think I used to have something like a trello board. 

Anyways - appreciate if you tackle them, it's really useful.

**Comment by acicovic** [comment]
OK, I will be proposing closure for various issues at a slow pace because this will also need feedback from you guys. It's certain that some of them will need to be discussed in meetings. I'll start from the old ones.

About "wishes", I think that some of them should be cleaned up and others could be converted to feature requests with a "Feature Request:" prefix in the subject. However, if the feature request is accepted then it should be assigned quickly and have a visible horizon of implementation. Feature requests which get categorized as wontfix for any reason (not useful, not implementable at the time being etc) should be closed. They can be reopened in the future if needed.

This is to avoid "open lingering wishes that might be implemented someday". For that type of wishes we could create a list or a single "Wishes" Github issue where the first post would contain them all. When they are to be implemented they can be submitted as feature requests in their own thread if needed.
