### ISSUE TITLE
Docs: Refer to Form Fields as 'FormField' always?

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#794]
Currently writing some documentation for Multiline Component, I remember how much I struggled differing atk4\data\Fields and atk4\ui\FormFields as the latter usually represent the former.

I thought it might be a good Idea to refer to form fields as 'FormField' always in the docs. Data fields are already referred to as 'Field' usually. This would make it more clear if we are talking about the data field storing the data or the ui form field representing that data.

**Comment by abbadon1334** [comment]
Agree!

**Comment by acicovic** [comment]
Anything that enhances clarity is a good thing, so I agree.

**Comment by romaninsh** [comment]
Agree to this.

**Comment by DarkSide666** [comment]
100% agree

**Comment by georgehristov** [comment]
I would propose using `$form->inputs` instead of `$form->fields` to clearly differentiate.

**Comment by DarkSide666** [comment]
Not `inputs`. Better `getFormField()` as synonym for forms `getField()`, but do not remove `getField` method too, because it's quite straightforward and I do not see reason to remove it and introduce another backward incompatibility issue.
