### ISSUE TITLE
Bug: Decorated Messages don't display when added to Form

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#797]
Demo code:

```
<?php

use atk4\ui\Form;
use atk4\ui\App;

require '../vendor/autoload.php';

$form = new Form();
$form->add(['Text', 'Add to Form']);
$form->add(['Message', '', 'text'=>'Regular message']); //  Works
$form->add(['Message', '', 'success', 'text'=>'Success!!!']); // hidden by CSS display:none (semantic.min.css:179)
$form->add(['Message', '', 'warning', 'text'=>'Warning!!!']); // hidden by CSS display:none (semantic.min.css:179)


$app = new App();
$app->initLayout('Centered');
$app->add($form);

$app->add(['Text', 'Add to App']);
$app->add(['Message', '', 'text'=>'Regular message']); //  Works
$app->add(['Message', '', 'success', 'text'=>'Success!!!']); // Works
$app->add(['Message', '', 'warning', 'text'=>'Warning!!!']); // Works
```
All messages added to `App` work. From the messages added to `Form`, only the default one displays. Decorated messages (warning, success, error) do not display and are hidden by a CSS rule (semantic.min.css:179).

**Comment by PhilippGrashoff** [comment]
I think that's intended. I guess these message classes are automatically hidden/displayed if firm is successful/has errors. Check fomantic ui Form, guess it's documented there

**Comment by acicovic** [comment]
You're right.

https://fomantic-ui.com/collections/form.html#message

This is not an ATK UI issue so I'm closing this.

**Comment by acicovic** [comment]
If anyone stumbles upon this, you just have to do a `$form->addClass('warning') to see warnings. More information here: https://fomantic-ui.com/collections/form.html#success.
