### ISSUE TITLE
UI representation of \atk4\data\Field with custom typecast set fails

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#798]
Hi, I have a Model with a field with custom typecasts set, in this case encryption and decryption:
```
/*
     * encryption and decryption taken from PHP manual
     *
     */
    public function encryptField(\atk4\data\Field $field, string $key) {
        $field->typecast = [
            function($value, $field, $persistence) use ($key) {
                if($value === null) {
                    $value = '';
                }
                $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
                $cipher = base64_encode($nonce.sodium_crypto_secretbox($value, $nonce, $key));
                sodium_memzero($value);
                sodium_memzero($key);
                return $cipher;
            },
            function($value, $field, $persistence) use ($key) {
                $decoded = base64_decode($value);
                if(mb_strlen($decoded, '8bit') < (SODIUM_CRYPTO_SECRETBOX_NONCEBYTES + SODIUM_CRYPTO_SECRETBOX_MACBYTES)) {
                    //temporary for migrating EOO settings
                    return $value;
                    throw new \atk4\data\Exception('An error occured decrypting an encrypted field: '.$field->short_name);
                }
                $nonce = mb_substr($decoded, 0, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES, '8bit');
                $ciphertext = mb_substr($decoded, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES, null, '8bit');

                $plain = sodium_crypto_secretbox_open($ciphertext, $nonce, $key);
                if($plain === false) {
                    //temporary for migrating EOO settings
                    return $value;
                    throw new \atk4\data\Exception('An error occured decrypting an encrypted field: '.$field->short_name);
                }
                sodium_memzero($ciphertext);
                sodium_memzero($key);
                return $plain;
            },
        ];
    }
```

Its about storing sensitive data which at some point is needed plain (e.g. Key for an API) encrypted in database.

When used in a Form, the user should be able to see the plain value and modify it. Here this issue comes in:
1) When the Model is loaded, the field's value is already decrypted, so available plain.
2) FormField/Input::getValue() is used get the value for the <input> tag.
3) getValue() calls Persistence::typecastSaveField(), which encrypts the value again.
4) The encrypted value is set to the input.

**Comment by PhilippGrashoff** [comment]
Reading the code, I think in `FormField\Input::getValue()`, calling 
```
$this->app->ui_persistence->_typecastSaveField
```
instead of 
```
$this->app->ui_persistence->typecastSaveField
```
seems correct. `_typecastSaveField` is called most of the time anyway unless
1) a custom typecast is set to the field
2) the value is null.

Testing this quickly works fine.

**Comment by PhilippGrashoff** [comment]
From gitter chat:

Persistence is passed as param to typecast closure
so
```

if($p instanceof \atk4\ui\Persistence\UI) {
    return $value;
}
```

but I dont really like this
either include or exclude all Persistences where typecast should/shouldnt happen
as more persistences follow the chance of messing that accidently up increases a lot
like only include SQL persistence
then you code some excel export using your nice persistence
and accidently leak sensitive data

**Comment by abbadon1334** [comment]
this is yours @DarkSide666 ;) i agree for separation of class purpose

**Comment by DarkSide666** [comment]
Hmm....
What I don't remember now is why did we need getValue() to call Persistence::typecastSaveField() at all.
Will have to dig into this issue at some point.
