### ISSUE TITLE
'datetime' field doesn't display seconds

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#817]
I'm loading a datetime value from the database into an input of type 'datetime'. The field always truncates seconds to 0 although the value is correctly passed into its HTML.

This is the HTML generated by ATK:

```
<input
    name="test_updated" type="text" placeholder="" 
    id="_468381cb___generic_generic_5_test_updated_input"
    value="14/10/19 15:13:17" class=""
>
```

And this is what is shown on screen:

![image](https://user-images.githubusercontent.com/23142906/66752452-1539e200-ee9a-11e9-85f1-5d94e9407e26.png)

**Comment by ibelar** [comment]
It look like Fomantic-UI calendar module does not display second by default and will prevent second value from being display when formatInput option is true (default).

You need to explicitly set Calendar to not reformat value by setting the formatOption to false:

```
$calendar_field->setOption('formatInput', false);
```

see: https://jsfiddle.net/ibelar/0n875tz6/15/

**Comment by DarkSide666** [comment]
@ibelar is it possible to set formatInput=false as default option in ATK side?

**Comment by ibelar** [comment]
We could but I have no idea on the impact it could have over the other format like date, time etc. 

Perhaps the best way would be to address this issue directly with Fomantic-UI.

**Comment by acicovic** [comment]
The workaround provided by @ibelar works. I may post an issue to Fomantic to resolve this from Fomantic's side.
