### ISSUE TITLE
App->initIncludes() adds <script>/<link> several times

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#827]
If App->initLayout() is called more than once (and so initIncludes() by initLayout()), the HTML tags for including JS/CSS are set several times.

That can easily happen when your App has a standard layout and on some pages its destroyed and another layout is set using initLayout().

Possible fix: check inside initIncludes() if it was already called; if so, do not execute again.

**Comment by acicovic** [comment]
Would you be willing to post a PR for it?

**Comment by romaninsh** [comment]
why would you call initLayout multiple times? I suppose the correct behaviour would be to throw exception if $app->layout already exists.

**Comment by mvorisek** [comment]
clean html before like in `App::caughtException`:
https://github.com/atk4/ui/blob/f03023cbff02df654c277a0af25a7b0ea0c31fcb/src/App.php#L264
