### ISSUE TITLE
WIP - improvements to invocation of UserAction Executor.

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#828]
User Action (introduced and then refactored #820 ) is great but needs a bit of change on the interface:

# Triggering

currently assignTrigger is a swiss army knife. You can pass event and scope etc, but what if you want to trigger Action Executer from a call-back? There are still limitations, so I suggest to do this differently.

``` php
$ex = $app->add('ActionExecutor');
$ex->setAction($model->getAction('delete'));

$button = $app->add('Button');

$button->on('click', $ex->jsExecute(4));
```

In the code above, jsExecute() retursn JS chain and will take two optional arguments:
 - ID (either scalar or jsExpression for where to get ID)
 - Args (array of scalar or expressions)

Arguments cannot be optional, because jsExecute may need to know if we have supplied all the arguments and if we must show argument form or not.

Here is another useCase:

``` 
$form->onSubmit(function($f) use ($ex) {
  return $ex->jsExecute(null, $f->model->get()); 
});
```

in this case we use a custom form's submit handler to trigger executor.

**Comment by mvorisek** [comment]
issue is too broad
