### ISSUE TITLE
WIP - integration of User Action Executor

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#829]
User action executor (#768 #820 ) allow to easily trigger actions on models. We want more of our UI elements to be executed, so this issue proposes multiple ways:

## View

``` php
$button->on('click', $model->getAction('register'), ['args'=>['accept_tos'=>$jsInput->val()]]);
```

View would create new Executor bind to it's jsExecute method #828 making it really simple to bind actions to buttons or other UI elements such as menu items.

## Form

``` php
$form->onSubmit($f) {
  return $f->jsAction('save');
}); 
```

new method of the form - jsAction will accept either name of the action (must be present in $form->model) and would allow us to execute any action and even pass some arguments too. The scope will be determined based on the load satus of the model. (if model was loaded or not).

## Console

``` php
$console->jsExecuteAction($action, $id, $args);
```

similar to $console->set(callback), but would execute model action instead. While executing the output would be captured and displayed. 

We can also add $console->executeAction() which would be similar to runMethod();

## Table

It should be possible to link table with an action. Clicking on table row would trigger the action, easy as that:

``` php
$table->setClickAction('delete'); 
```

method can accept optional arguments, but ID will be that of clicked row. 

## Grid

In Grid we introduce concept of Action column. It contains button with icons by default, but we should also be able to use menu. Additionally menu should be used if there more than 3 actions in a column. 

``` php
$grid->addAction('delete');
$grid->addAction('edit');
````

It is also possible to create a separate ActionColumn, so you can have edit/delete in first column, and another column with other (many) actions. 

when menu is used - show three vertical dot icon and when clicked open menu with all the actions there.

**Comment by romaninsh** [comment]
This is mostly done as if 2.1

**Comment by mvorisek** [comment]
Issue is too broad, mostly implemented.
