### ISSUE TITLE
Table columns order

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#836]
I'm researching different frameworks currently for a project. I came across Agile Toolkit and I'm really impressed!
Some questions concerning tables: 
1) Our client wants to have the columns draggable (means to move e.g. column 5 to position 2). In addition he wants to show/hide certain columns (and save the view). Is this easily do-able with Agile?
2) Why are you using tables instead of div tables? In terms of responsiveness div-tables would be  better (like in Bootstrap).
3) There exists a pretty awesome table plugin for Bootstrap I've been using several times (https://examples.bootstrap-table.com). Is using Bootstrap with Agile possible? And does it make sense? Do you have any experience with it?

Thanks for your reply and keep up the great work!

**Comment by acicovic** [comment]
Hi,
ATK UI uses Fomantic UI (https://fomantic-ui.com/). Thus all components and markup you see are based on that framework.

1. I don't think it's possible
2 and 3. As ATK UI uses Fomantic, it is built upon its controls. So if you want to use ATK UI with a ready-made interface, you are obliged to use what comes with it. If you want to use Bootstrap with ATK, it is possible by using ATK data (handles the data layer only), but you'll have to build all the interface yourself. So this would significantly more work.

**Comment by bedengler** [comment]
Ok thanks, I'll try it myself and report if it works...

**Comment by romaninsh** [comment]
@bedengler You could implement it similarly to this:

https://github.com/atk4/ui/blob/22e00dfc72506aff63ba09585a9e12b71bc046ec/js/src/plugins/column-resizer.plugin.js
