### ISSUE TITLE
Make a model with all fields of a db table

### ISSUE THREAD

**Issue by bedengler** [atk4/ui#841]
Question regarding reading out a database and tables for a creation of a model.
Here's what I want to achieve:

- I have a table with let's say 10 columns
- I want to create a modeI but want to prevent writing 10 times "$this->addField('..."
- Instead I'd like to run a db query reading all the fields of the table and putting them in an array
- I run through the array and for each element I'm doing "$this->addField('..." automated.

Is this possible? How?
Is there any function that does a query like "SHOW COLUMNS FROM [table name]"?

Btw: is this the right place to ask such questions? If not, where is it?

**Comment by acicovic** [comment]
Hi,
The project's chat room is here:
https://gitter.im/atk4/atk4

**Comment by PhilippGrashoff** [comment]
this could be in atk4/schema, thats a place to look for that. Though I think it works in the other direction.
As a atk4 field stores more information than the DB column, I doubt this approach will fulfill all your needs in the long term.

**Comment by bedengler** [comment]
I realized there's a function in the Model class of atk/data that's called "allFields".
How's this intended to work? I can't find any documentation anywhere...

**Comment by romaninsh** [comment]
@bedengler - see https://github.com/atk4/schema/blob/develop/src/Migration.php#L423

**Comment by romaninsh** [comment]
@bedengler - could you improve documentation, so that it would be easier for others to find answer for this?

**Comment by bedengler** [comment]
> @bedengler - could you improve documentation, so that it would be easier for others to find answer for this?

Ok, I'll try my best!
