### ISSUE TITLE
Calling $view->render() multiple times duplicate content

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#85]
**Test case:**
```
$g = new \atk4\ui\Table();
$g->setModel([
    ['name' => 'foo'],
    ['name' => 'bar'],
]);
$g->render(); // render but not output
echo $g->render(); // render one more time and output - as result all grid rows are duplicated
```

**Solution**
render() should not append rendered results, but should re-render everything from scratch each time it is called.

**Comment by romaninsh** [comment]
I suppose we can del() it.

Can you create a test-script that calls render twice then compares results against each-other before fixing this?

**Comment by DarkSide666** [comment]
Ok will do hopefully today

**Comment by DarkSide666** [comment]
Added simple test case which shows that if we render view multiple times, then content is duplicated.
https://github.com/atk4/ui/commit/a6fa4d28573975c01b46a468be101777d22ca892
https://travis-ci.org/atk4/ui/jobs/214838511

```
1) atk4\ui\tests\ViewTest::testMultipleRender
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<div id="atk" class="  " style="" >foo</div>'
+'<div id="atk" class="  " style="" >foofoo</div>'

/home/travis/build/atk4/ui/tests/ViewTest.php:16
/home/travis/build/atk4/ui/vendor/atk4/core/src/PHPUnit_AgileTestCase.php:10
```

**Comment by romaninsh** [comment]
nice.
