### ISSUE TITLE
Inconsistent behaviour in calendar: You can't reliably input dates for days lower than 12 with a custom dateformat

### ISSUE THREAD

**Issue by karakal** [atk4/ui#858]
I have an inconsistent behaviour for the calendar component when using localized date formats.

I have the date_format in ui_persistence defined as 'd.m.Y'.
When I input a date in the datefield in a form the following things are happening:

When I type into the field: 12.12.2019 everything is okay and a date with 12.12.2019 is created
When I type into the field: 19.12.2019 everything is okay
When I type into the field: 5.12.2019 the calendar picker jumps to May and creates a date 12th of May. When I select the correct date from the calendar-picker and press save, it is saved correctly as 5th of December to the database But as soon as I open this entry the date is "corrected" to 12th of May and when I press Enter without changing anything, this wrong "corrected" date is saved.

Therefore it is not possible to use this function reliably!

**Comment by PhilippGrashoff** [comment]
Hi karakal,

there have been many changes, fixes and updates to Fomantic UI's date picker in the past month. Maybe you can try to manually use the newest version and see it the problem still exists? My guess would be that the FUI version used by ATK might still have a bug which was already fixed in some never release of FUI.

**Comment by karakal** [comment]
Hi, thx for the quick answer. Which files should I use and overwrite? I am using the development version of UI from the beginning of November.

**Comment by PhilippGrashoff** [comment]
Hi,
in your app the JS of Fomantic-UI is included. If you extended App class, simply put this line in the beginning of the contructor to get the current FUI js included:
```
        $this->cdn['semantic-ui'] = 'https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.2/dist';
```

What you want to achieve is this line in the HTML source code:
```
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.2/dist/semantic.min.js"></script>
```

**Comment by karakal** [comment]
No, that didn't work. But maybe I found a pointer to the right solution:
https://stackoverflow.com/questions/55573373/semantic-ui-calender-formatter-function-reads-the-date-wrong

There is a option, one can set one on the Calendar that is called monthFirst that should be set to false, when the dateformat is something other than starting with month (In my case it is day.month.year)

How can I achieve that?

**Comment by karakal** [comment]
I found the calendar_options in ui_persistence...

**Comment by PhilippGrashoff** [comment]
excellent, does it work?

**Comment by romaninsh** [comment]
New fomantic released today! Lets bump our version and release ATK.

**Comment by acicovic** [comment]
@karakal so, has the issue been resolved?

**Comment by romaninsh** [comment]
old / stale.
