### ISSUE TITLE
Add Table Column Decorator for HTML code

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#875]
Hi,

I think its nice to have some Decorator that just outputs HTML, e.g. if you have some pre-rendered HTML in a model field that you want to output as-is.
If you think thats good to have, here is a working implementation:

```
<?php

namespace atk4\ui\TableColumn;

/**
 * Class HTML
 * @package atk4\ui\TableColumn
 * 
 * Use this decorator if you have HTML code that you just want to put into the table cell
 */
class HTML extends Generic
{

    /**
     * 
     */
    public function getDataCellHTML(\atk4\data\Field $f = null, $extra_tags = [])
    {
        return '{$_'.$f->short_name.'}';
    }


    /**
     *
     */
    public function getHTMLTags($row, $field)
    {
        return ['_'.$field->short_name => '<td>'.$row->get($field).'</td>'];
    }
}
```

**Comment by romaninsh** [comment]
Looks good enough for PR :D

**Comment by DarkSide666** [comment]
> Looks good enough for PR :D just use $field->short_name without underscore, then you don't need to override getDataCellHTML.

Not really. Then it will break table header row markup.
