### ISSUE TITLE
There is no not[checked] validation rule in Fomantic

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#878]
It looks that Semantic/Fomantic don't have `not[checked]` validation rule :(
Maybe we can extend and implement something on our own there or at least give them a shout that this is needed in some situations.

So currently this is not possible:
```
// sadly this way it don't work because Semantic don't support that
$form->setFieldsDisplayRules([
    'clients' => ['all_clients' => 'not[checked]'],
]);
```

**Comment by mvorisek** [comment]
how important this is? I think better to implement live server side validation

**Comment by DarkSide666** [comment]
It's important for UI to show `clients` field only if `all_clients` checkbox is **not** checked.
There are workarounds by adding some JS event listeners, but this way it would be better.
Probably that's more like Fomantic issue (enchancement) not ATK.

**Comment by mvorisek** [comment]
yes, it will always be limited, only live server side validation can cover all scenarios

**Comment by mvorisek** [comment]
closed in favor of https://github.com/atk4/ui/issues/1259
