### ISSUE TITLE
Upload file to database BLOB field

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#890]

**Comment by mvorisek** [comment]
implement once BLOB field is added, see https://github.com/atk4/data/issues/506

**Comment by romaninsh** [comment]
Storing files in a database is a bad practice. Database is for structured data, for raw data use S3

**Comment by mvorisek** [comment]
> Storing files in a database is a bad practice. Database is for structured data, for raw data use S3

Why it is a bad practice? - https://softwareengineering.stackexchange.com/questions/150669/is-it-a-bad-practice-to-store-large-files-10-mb-in-a-database as long as the target DB have enought resources (and also for backups), then I do not see any. But of course, the BLOB field can support also persistence to a FS or even S3.

**Comment by romaninsh** [comment]
SQL is for storing structured data and storing files in SQL is bad practice, I've seen cases when that was done and it's not fun to deal with once the database is bloated up.

We support "filestore" implementation in ATK - where meta-data is stored in SQL while files themselves are uploaded into a persistent data storage.

Said that - ATK is persistence agnostic, so Blob as a file type does make sense. Luckily this can be implemented as an add-on, but I don't think it will gain much popularity.

**Comment by mvorisek** [comment]
Makes sense where ACIDity is an requirement?

Databases like MSSQL are optimized for this usecase, even MySQL stores BLOB/TEXT values outside main table.
