### ISSUE TITLE
Add option to set precision to datetime/time type

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#891]
Proposal:
- `0` = integer seconds precision
- `1 .. 6` = fraction of seconds precision like in the database types, i.e. 1 - 6 extra digits
- `-2` = round to whole even seconds
- `-5` = round to `0`, `5`, ... seconds
- `-60` = round to whole minutes
- `-3600` round to whole hours

and format the datetime/time values accordingly, i.e. if rounded to whole hours, do not display minutes and do not offer to seconds/minutes in the datetime picker (or allow to choose minutes in 5 minutes increments if the precision is set so)

**Comment by DarkSide666** [comment]
First need to implement at least part of these properties in atk4/data side after Fields refactor PR in atk4/data will be merged.

**Comment by romaninsh** [comment]
Agree and any enhancements to field decorator could be contributed in an addon.

**Comment by mvorisek** [comment]
currently some customization is possible with flatpickr
