### ISSUE TITLE
integrate selenium testsuite

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#9]

**Comment by romaninsh** [comment]
Almost done. 

Need help with http://stackoverflow.com/questions/41337139/allow-phpunit-test-to-access-actual-environment-variable?noredirect=1#comment69877502_41337139

**Comment by DarkSide666** [comment]
temporary removed in https://github.com/atk4/ui/commit/23674faefdb500a62f2fc6ced88ae16c60449102
