### ISSUE TITLE
Bad link / Actions demo issue

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#904]
In README in https://github.com/atk4/ui#bundled-and-planned-components table there is a link to "Actions" with `https://ui.agiletoolkit.org/demos/actions.php` target.

But when this link is opened, it keeps redirecting to `https://ui.agiletoolkit.org/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/demos/index.php` (and probably more levels if the browser will allow).

**Comment by DarkSide666** [comment]
Link is correct.
I guess issue is that UI demo site is still on 1.7.1 version and not 2.0.x releases.
@ibelar @romaninsh please check!

**Comment by mvorisek** [comment]
related with https://github.com/atk4/ui/pull/873
