### ISSUE TITLE
Form submit not working

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#91]
Form submit is not working when form is made like this:
```
$form = $app->layout->add('Form');
$form->addField('foo');
$form->onSubmit(....);
```
When I click on [save] button in form nothing happens. No ajax request to server is made :(

**Comment by romaninsh** [comment]
Dark, can you confirm if that's a bug in 1.0 branch or develop (or both)

**Comment by DarkSide666** [comment]
i think it was in 1.0 branch. It was in school courses where they simply did `composer require atk4/ui`.

**Comment by romaninsh** [comment]
Confirmed the following to work on 1.0.2:

``` php
$form = $app->layout->add('Form');
$form->addField('foo');
$form->onSubmit(function($f) {
    return $f->success('yep, '.$f->model['foo']);
});
```
