### ISSUE TITLE
CRUD - delete not working

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#911]
Consider this model:
```
class User extends BaseModel
{
    /** @var string */
    public $table = 'user';

    public function init()
    {
        parent::init();

        $this->addField('email', ['required' => true]);
    }
```

Currently, when:
- User model is present/saved and:
- delete button is pressed and delete is confirmed

then:

the CRUD shows edit dialog, instead of sending a request to server to delete the model immediatelly.

**Comment by romaninsh** [comment]
Fixed?

**Comment by mvorisek** [comment]
Fixed, closing.
