### ISSUE TITLE
Disable the default message from update-docs

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#918]
Is there any significant advantage of the autogenerated messages like
> 
> 
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.

? If no, disable adding this chatbot message for any new PR.

**Comment by DarkSide666** [comment]
I don't see any advantage of that. @romaninsh added it I guess.

**Comment by PhilippGrashoff** [comment]
The significant advantage is that people are encouraged to update docs :)

**Comment by mvorisek** [comment]
> The significant advantage is that people are encouraged to update docs :)

But who does based on that? :)

**Comment by romaninsh** [comment]
@mvorisek the message is only displayed if you make absolutely no change in the /docs/ folder.

If you have a better idea how to encourage PR documentation, please propose.

**Comment by mvorisek** [comment]
@romaninsh I checked the last 50 closed tickets and almost all of them contains this message. I think this message does not solve anything and it should be removed. All PRs are reviewed by you, the core team, so I propose disabling this GH chatbot as PR review seems enought to me and this decision improves the PR space/distraction vs. value ratio.

**Comment by romaninsh** [comment]
> > The significant advantage is that people are encouraged to update docs :)
> But who does based on that? :)

I do myself. That nag message is great reminder for me. We would be lost without the docs. Only @gowrav-vishwakarma was brave enough to use ATK before docs were written. 😄
