### ISSUE TITLE
UserAction: Problem with model loading

### ISSUE THREAD

**Issue by badrboukri** [atk4/ui#919]
In "UserAction->doSteps()" expects the records's ID to be sent via GET method (stickyGet).
https://github.com/atk4/ui/blob/7087083ede2d51d9260d7b2b27ab64a58a350a7f/src/ActionExecutor/UserAction.php#L144

However the UserAction->jsStepSubmit function is sending the ID and step via POST method.
https://github.com/atk4/ui/blob/7087083ede2d51d9260d7b2b27ab64a58a350a7f/src/ActionExecutor/UserAction.php#L554

**Comment by ibelar** [comment]
@badrboukri -  Even if jsLoad is done using a POST request, the model id will still be sent as a query string parameter. The POST is required to carry form data over from one action step to the other. 
Could you please explain, with sample code if possible, what problem you are having?

**Comment by badrboukri** [comment]
> @ibelar  The problem is the following:
When the edit action is called in the context of the CRUD component, an empty form is shown.
The cause is that the $id of the model is expected to be retrieved as a GET parameter:
https://github.com/atk4/ui/blob/7087083ede2d51d9260d7b2b27ab64a58a350a7f/src/ActionExecutor/UserAction.php#L144
but in fact, it is sent in the POST payload:
https://github.com/atk4/ui/blob/7087083ede2d51d9260d7b2b27ab64a58a350a7f/src/ActionExecutor/UserAction.php#L554

**Comment by ibelar** [comment]
@badrboukri - Please provide more information, i.e. sample code and how your edit action is defined.

**Comment by badrboukri** [comment]
> @ibelar this is a code sample of a view called model "ServiceModel":
$mainLayout = $app->layout;
/** @var \atk4\ui\XCRUD $card_services */
$card_services = $mainLayout->add(['CRUD']);
$m = (new ServiceModel($db));
$card_services->setModel($m);

RESULT:
=> rows are charged without problem
=> add a new row is ok
=> the update of an existing record gives an empty form (even if the "id" is found in the POST)

**Comment by badrboukri** [comment]
below is the error that appears when hitting the save button
![image](https://user-images.githubusercontent.com/19587734/74267324-24c11e80-4d06-11ea-8ebb-9451a122125f.png)

**Comment by ibelar** [comment]
Quick question, what is your ServiceModel id_field property is set to? Is it using default 'id' value or something else?

**Comment by badrboukri** [comment]
By using default 'id'

**Comment by ibelar** [comment]
Sorry but I can't help you with provided information. Based on your code above, everything is working fine. What atk4/ui release are you using? What atk4/data release? Can you provide the url when form from edit action is submit? Have you change anything in edit action configuration?

**Comment by badrboukri** [comment]
>@ibelar
Thank you for your assistance;
The source of the problem was a former atk js
