### ISSUE TITLE
Accessing a field that can be null

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#920]
https://github.com/atk4/ui/blob/3d561f2b63f282f7bb324b9e0830bdaa4715ab60/src/FormField/DropDown.php#L229

If the field is not set PHP currently shows a notice warning.

If field can be set without a model, then extra null check should be added, otherwise it should be moved to the condition right below which checks if model is set.

**Comment by PhilippGrashoff** [comment]
duplicate of #830

**Comment by mvorisek** [comment]
@DarkSide666 Is field not-null if and only if model is set?
