### ISSUE TITLE
Important: Call to undefined method PDOException::getHTML()

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#921]
```
Error: Call to undefined method PDOException::getHTML() (in .../src/ActionExecutor/UserAction.php:562)
```

**Comment by mvorisek** [comment]
There should be a check like:
```
$m->text->content = $e instanceof \atk4\core\Exception ? $e->getHTML() : $e->getMessage();
```

but review the escaping, not sure, if `content` accepts text to escape or escaped HTML.

**Comment by mvorisek** [comment]
Does the try/catch here make any sense?

If yes. there should be a check like here:

https://github.com/atk4/ui/blob/fa94b89c986bec4936846e63dff69c3f28a463b8/src/App.php#L265

- this code should be put in a separate method
- it should be possible to configure the App to either display full debug info or to display only the exception message

**Comment by mvorisek** [comment]
The preffered way should be to not render the exception there but throw a new custom exception like `ActionException`. This exception can have then a special render format in the global exception handler/render.

**Comment by mvorisek** [comment]
@DarkSide666 What is the best way to fix this?

**Comment by DarkSide666** [comment]
But there is such a check in UserAction.php: https://github.com/atk4/ui/blob/develop/src/ActionExecutor/UserAction.php#L570

**Comment by mvorisek** [comment]
@DarkSide666 Ahh, fixed 2 months ago. But the fix does not escape HTML.

Is this intended for js response? Or what about reusing: https://github.com/atk4/ui/blob/fa94b89c986bec4936846e63dff69c3f28a463b8/src/App.php#L265

**Comment by DarkSide666** [comment]
Do you think it should escape HTML?

**Comment by mvorisek** [comment]
Yes. the `$e->getMessage()` from here:
https://github.com/atk4/ui/blob/7e0c0aa2948b614a252e8d82666cd1072b9f1bc4/src/ActionExecutor/UserAction.php#L570
is currently not HTML, but it is set as HTML/content without escaping.

**Comment by mvorisek** [comment]
Related with - https://github.com/atk4/ui/issues/925 - Exception rended should be probably centralized.

**Comment by romaninsh** [comment]
Exceptions render themselves because we must minimise the possibility of repeated exception. It’s a bit ugly but works well
