### ISSUE TITLE
Conditions from model should be removeable

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#923]
Usecase:

model with soft deleteable field has condition by default and if this conditions is not needed (for example for some auditing script), it should be possible to remove that condition.

**Comment by DarkSide666** [comment]
Most of the time conditions are there to not be removable. They set a scope of model and if you're allowed to remove/change scope then a lot of bad things can accidentally happen :)

Your use-case is kind of legit, but still - if you allow to access deleted records, then model behaviour is no more as it should be (do not allow accessing soft deleted records).

Audit script should use hooks to get record before or even after it goes outside of model scope defined by conditions.

So in my opinion this requirement should not be implemented.

**Comment by mvorisek** [comment]
I currently ended up with:
```
class User extends BaseModel
{
    /** @var array */
    private $_softDeleteCondition;

    public function init()
    {
        parent::init();

        ... add fields and delete hook here...

        $this->addCondition('passState', '>=', 0);
        $this->_softDeleteCondition = end($this->conditions);
    }

    public function getUserWithoutSoftDeleteCondition(): self
    {
        $user = clone $this;
        foreach ($user->conditions as $k => $cond) {
            if ($cond == $this->_softDeleteCondition) {
                unset($user->conditions[$k]);
            }
        }

        return $user;
    }
}
```

I understand that the current concept is like "extent/restrict" the conditions only, but there are a lot of usecases where you want to remove the conditions. Based on my research the conditions are not copied to somewhere else in the `init()` so removing them is technically very simple - for me, the question is only what should be the input of the `removeCondition` method
- index?
- value?
- value & always create and return a condition object, so it can be later removed, i.e. compared for strict equality?
- some name/key that could be possible to pass into the `addCondition`?

**Comment by romaninsh** [comment]
This came up several times.

Clone your model before you have your conditions added. Removing conditions from the model is anti-pattern. Also - use "saveAs" or "saveAndUnload" if you need to ignore condition on save.
