### ISSUE TITLE
Critical: atkReloadView does encode URL values twice

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#924]
Example:
```
        $button = $this->app->add('Button')->set('click me');
        $button->on('click', $button->js()->atkReloadView(
            ['uri' => $button->url(), 'uri_options' => ['move' => 'next']]
        ));
```

How to reproduce?
- navigate to URL: `https://xxx/yyy.php?crud_model=AppAtk4%5CModel`
- click the button and notice, that the new URL of that request is URL encoded twice

Currently this URL is requested:
```
https://xxx/yyy.php?crud_model=AppAtk4%255CModel
```
vs. (expected)
```
https://xxx/yyy.php?crud_model=AppAtk4%5CModel
```

Btw: where is the `atkReloadView` JS method defined? It seems that there is only `atkjs-ui.min.js`.

**Comment by ibelar** [comment]
The sample code provides will not work correctly for button to reload because you are missing the '__atk_reload' argument. A suggestion would be to use the View::jsReload() method, which will properly render the argument.

**Comment by mvorisek** [comment]
@ibelar Thanks, but if I wrap reading the of the value in urldecode, it works well.

Did you fully understant the issue, that some characters are encoded twice? I have analysed the issue and it seems that the `atkReloadView()` method is the source of it (as input is ok, and output is bad).

**Comment by ibelar** [comment]
@mvorisek - Thanks for the clarification.
