### ISSUE TITLE
Add support to display nested exceptions by default

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#925]
Example:

```
// <init App here>

try {
    (function(){ throw new \Exception('x'); })();
} catch (\Exception $ex) {
    throw new \Exception('y', 0, $ex);
}
```

help wanted

**Comment by romaninsh** [comment]
To my knowledge exception will recursively render nested exception. Is this broken?

**Comment by mvorisek** [comment]
Closing, fully solved by exception renderers from core with unrestricted/`\Throwable` catch in `App`.
