### ISSUE TITLE
Tests are failing on develop

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#932]
see https://travis-ci.org/atk4/ui/builds/647286179

help wanted

**Comment by mvorisek** [comment]
Issue introduced in PR #900

**Comment by DarkSide666** [comment]
should be fixed by #942

**Comment by mvorisek** [comment]
#942 fixed the original issue, but there is still one more test to fix: https://travis-ci.org/atk4/ui/jobs/649098810#L919

And do not merge any failing PR then :)

**Comment by DarkSide666** [comment]
Travis tests are now fixed.
That atk4/ui-demo is unfinished integration with codefresh.io.

**Comment by mvorisek** [comment]
> Travis tests are now fixed.
Perfect!

Closing this issue and opened an separate one for the `atk4/ui-demo`.

**Comment by DarkSide666** [comment]
Closing in favor of #946
