### ISSUE TITLE
[IMPROVEMENT] renaming hook addHook method

### ISSUE THREAD

**Issue by georgehristov** [atk4/ui#966]
I find the hook methods (`hook` and `addHook`) a bit confusing for newcomers.

How about renaming the `addHook` to `onHook` (keeping BC) to make it more intuitive?
IMHO this would improve the DX.

If agreed with the change you can assign me to that issue.

**Comment by georgehristov** [comment]
Maybe I am a bit obsessed with semantics but starting to think that `onHook` should even be simply `on`
WDYT?

**Comment by PhilippGrashoff** [comment]
Dont like it, as "on" does not give any hint what it does. "onHook" states clearly that it has something to do with a hook.
There also is "on" in ATK UI, definitely that could confuse new ATK users.

**Comment by georgehristov** [comment]
Good, then we can close the issue
