### ISSUE TITLE
Column Filtering Not Working?

### ISSUE THREAD

**Issue by woolfrom20** [atk4/ui#971]
After pulling the latest dev code to fix the delete issue, the ability to have column filtering has appeared to stop working.  The dropdown arrows in each column heading are no longer there.

This code used to work and no longer does:

```
require 'lib.php';
$app = new Portal();
//$g = $app->add(['CRUD', 'canCreate' => false, 'canDelete' => false, 'canUpdate' => false]);
$g = $app->add(['Grid']);
$g->setModel(new Host($app->db));
$g->setIpp([10, 25, 50, 100]);
$g->addFilterColumn();
```

**Comment by woolfrom20** [comment]
![ColFilter](https://user-images.githubusercontent.com/61597118/75571130-98616c00-5a26-11ea-9a3d-6a08bb6fdc27.PNG)

**Comment by georgehristov** [comment]
Have you rebult and deployed the latest assets (js and css)?

**Comment by woolfrom20** [comment]
I am using composer to pull the updates and was under the assumption it handle that for me.

**Comment by georgehristov** [comment]
You will need to build them to make sure they are the latest version and you need to make sure browser does not have the old version in cache.
Previously Chrome loaded fresh version on refresh page but now I have to clear the cache. 
For Firefox refresh only works.
 No experience with other browsers.

**Comment by woolfrom20** [comment]
I have tried both browers (FF and Chome) and cleared the cache in both.  How do I ensure they are the latest version (I have never had to do this before)?

**Comment by georgehristov** [comment]
See #900 
You need to rebuild the css from less using lessc and js using npm

**Comment by woolfrom20** [comment]
Thanks.  I was able to rebuild both and it appears to be working again.
