### ISSUE TITLE
Implement average for table totals

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#973]
Currently, there is no "avg" for table totals. Implementation would be easy, I can take care of it when I update to current versions. Code is quite finished:

1) new property `avgCount` for table:` $this->avgCount = 0;`
2) that code in updateTotals:
```
case 'avg':
    if($this->model[$key] !== null) { //only use non null values for sensible average calculation
        $this->totals[$key] = (($this->totals[$key] * $this->avgCount) + $this->model[$key]) / ($this->avgCount + 1);
        $this->avgCount++;
    }
    break;
```

**Comment by DarkSide666** [comment]
Well I guess it's a bit to much calculations.
Probably better would be to use two protected (for internal use) table properties:
```
case 'avg':
    if($this->model[$key] !== null) { //only use non null values for sensible average calculation
        $this->avgSum += $this->model['key'];
        $this->avgCount++;
        $this->totals[$key] = $this->avgSum / $this->avgCount;
    }
    break;
```

**Comment by PhilippGrashoff** [comment]
definitely the more sensible approach!

**Comment by PhilippGrashoff** [comment]
aaaah, avgSum and avgCount need to be arrays, as we might calculcate an avg for more than one column :)

**Comment by DarkSide666** [comment]
Oh, yes, correct.
Can you create PR for this?

**Comment by PhilippGrashoff** [comment]
Will do when I switch to newest ATK versions, still on 1.7

**Comment by romaninsh** [comment]
Related #286

**Comment by mvorisek** [comment]
@PhilippGrashoff should be possible with extra expression column, but of course only as workaround for now

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/ui/pull/286
