### ISSUE TITLE
Table displays all records, even if only one is loaded

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [atk4/ui#974]
(The same applies to Grid/CRUD)

This works: (record 3035 is displayed)
`$t->setModel($m)->addCondition('NIC_ID', '=', 3035);`

This doesn't: (all records are displayed)
`$t->setModel($m)->load(3035);`

This is the complete example:

```
class myapp extends \atk4\ui\App {
  public $db;

  function __construct() {
    parent::__construct();
    global $dsn, $dbuser, $dbpasswd;

    $this->db = \atk4\data\Persistence::connect($dsn, $dbuser, $dbpasswd);
    $this->initLayout('Admin');
  }
}

class Nic extends \atk4\data\Model {
  public $table = T1;
  public $id_field = 'NIC_ID';
  public $table_alias = 'INVNIC';

  function init() {
    parent::init();
    $this->addField('NIC_MAC');
  }
}

$app = new myapp();
$m = new Nic($app->db);
$t = $app->add('Table');

$t->setModel($m)->addCondition('NIC_ID', '=', 3035); // this works
//$t->setModel($m)->load(3035); // this doesn't
```

**Comment by DarkSide666** [comment]
This is as expected. Please read documentation of atk4/data more carefully.
This is how agile data models work. When you add condition it's like setting scope of model. But loading particular record is not scope, it's just an active record.
