### ISSUE TITLE
Make App->isJsonRequest() public

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#978]
Hi,

at the moment this function is protected. However, we might want to know from inside a View if the request is a full page reload or a JSON request. Hence I think this function should be public. Also the name without a leading _ supposes the function is public.

What do you think? any counter-arguments?

**Comment by mvorisek** [comment]
Please provide several real use-cases.

**Comment by PhilippGrashoff** [comment]
Taken from my code:
```
            if(!$this->app->isJsonRequest()) {           
                $this->itemList = $this->getRecordView($this->mainFormModel);
                $this->add($this->itemList, 'LeftLister');
            }
```
In this case its a page which is either rendered in a Modal or as full page. If the page is rendered as full page, a record list View is added to the left side, when rendered in a Modal not.
To solve the protected issue here I extended isJsonRequest() in my own App and made it public.

**Comment by mvorisek** [comment]
@PhilippGrashoff Will be made public in #1051
