### ISSUE TITLE
/demos/table.php - Exception Value should be scalar 

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#987]
Related code:
https://github.com/atk4/ui/blob/ad62e4488da24996016c6f12678d22d9799453b6/demos/table.php#L40

But `\DateTime` value should be supported.

**Comment by DarkSide666** [comment]
Fixed in https://github.com/atk4/ui/pull/1048.
I think that's correct fix because in demos we're directly importing values in persistence, so no typecasting works there at this point.

**Comment by acicovic** [comment]
Should we close this?

**Comment by mvorisek** [comment]
@acicovic I belive yes, thanks!
