### ISSUE TITLE
All UI elements should extend View

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#989]
Currently some classes like `Callback` are not extended from `View`.

This break things a litte bit as strict type checking is not possible. Is there any significant reason or can all UI elements than can be added to the render tree be based on the `View` class?

Afftected (top-most only) classes:
- `atk4/ui/Callback`
- `atk4/ui/Template`
- `atk4\ui\TableColumn\Generic`

Once fixed, change no class (unsafe) checking to check if the new objects extends at least `self`/`View` - see https://github.com/atk4/ui/pull/929/files#diff-248b7e363055cfdcca5a52260252ef41R425

**Comment by romaninsh** [comment]
I think this is non issue. All listed class have a good reason not to extend View. 

Callback is non visual and does not facilitate itself as an entity in html tree. 

Template is too abstract and is an utility class

TableColumn is also an utility for rendering cells and is part of Table therefore cannot exists without it. Field is also part do Form but they can be individually used and therefore extend View

**Comment by mvorisek** [comment]
> I think this is non issue. All listed class have a good reason not to extend View.

For me, it is, as long we want a consistent code - see for ex. this PR: https://github.com/atk4/ui/pull/1047/files

> `Callback` is non visual and does not facilitate itself as an entity in html tree.
> Template is too abstract and is an utility class

Yes, it seems `Template` should not/can not extend `View`.

This issue needs to be further analysed. We need at least these interfaces:
- `IRenderableItem` (for `App::terminateHTML()`, `render()`, `getHTML()`)
- `ITreeItem` (for `App::add()`)

Please provide feedback for this. Basically every common method should be called on checked type (class or interface).

**Comment by romaninsh** [comment]
`instanceof \atk4\ui\View` is a good ol' way to check.

I do not see how ATK would benefit from this suggestion, but I can see lot of issues with this change.

**Comment by mvorisek** [comment]
But you can not then enforce this type as request type for any render tree item. Makes sense so?
