### ISSUE TITLE
Improve UX - Add arrow to all/between Wizard items

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#992]
![image](https://user-images.githubusercontent.com/2228672/76843064-890e5b00-683b-11ea-9e2f-b007bc119ba5.png)

With arrows the Wizard components seems much more understandable to me (/w arrows = wizard, /wo = menu). Wdyt?

**Comment by DarkSide666** [comment]
I agree.

**Comment by DarkSide666** [comment]
Strangely in https://semantic-ui.com/elements/step.html it's already working like that, but in our UI it's not.

**Comment by ibelar** [comment]
This is a Fomantic Ui issue that has been fixed in their 2.7.7 release. We are still on 2.7.2 because of our issue with Tabs see PR #979. It will be resolved by itself when we can upgrade Fomantic UI release.

**Comment by mvorisek** [comment]
Great, I have added "Fixes <this issue>" to that PR, this issue will be closed once merged.
