### ISSUE TITLE
Fix security alert - minimist node package

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#994]
Alert: https://github.com/atk4/ui/network/alert/package-lock.json/minimist/open

File: https://github.com/atk4/ui/blob/develop/package-lock.json

Introduced by @ibelar - is this file needed at all? It seems like a mistake - https://github.com/atk4/ui/commit/e38e0c0e22815d60707f38377861c7c154878ebb , the commit title says "updated", but in reality it adds this file.

**Comment by mvorisek** [comment]
The mentioned lock file in the security alert was not fixed - @ibelar, is the fix really a fix to that issue?

And for me that lock file looks like a mistake, it should be probably removed and maybe even added to `.gitignore`.
> It seems like a mistake - e38e0c0 , the commit title says "updated", but in reality it adds this file.

**Comment by ibelar** [comment]
@mvorisek -thks. Not sure how package-json.lock file end up in main directory, but should not be there anyhow.
